### PR TITLE
Fix NegativeParForIncrTest case for unix

### PR DESCRIPTION
**Pull request by deroneriksson**
Change "NegativeParforIncrTest" to "NegativeParForIncrTest" so NegativeParForIncrTest.dml and NegativeParForIncrTest.R are found on Linux.

### CODE REVIEW

**Comment by deroneriksson** [comment]
Tests started [here](https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/349/).

**Comment by deroneriksson** [comment]
Looks like a hotfix for this was just committed. So I will close this.

**Comment by mboehm7** [comment]
sorry for the trouble - the test ran fine in my win environment but just saw the build issue. Thanks.

**Comment by deroneriksson** [comment]
Thanks for the quick fix!

**Pull request closed without merging**
