### PR TITLE
[SYSTEMML-688] Update dml file packaging in artifacts

### PR DESCRIPTION
**Pull request by deroneriksson**
Move dml to scripts dir for main, in-memory, sources, and standalone jars.
Include algorithms, datagen, and utils directories.
Exclude obsolete algorithms, perftest, and staging.
Update distrib.xml and standalone.xml to reflect similar packaging.
Update ScriptUtils.scala and LogisticRegression.scala for these changes.

### CODE REVIEW

**Comment by deroneriksson** [comment]
My Eclipse currently isn't set up for Scala development. Would it be possible for someone to verify the ScriptUtils and LogisticRegression updates look good?

**Comment by lresende** [comment]
Looks like we are changing to explicitly choose the scripts to put on the packages, to now put all except for the ones on specific folders. I am ok with that, but what to double check if all the scripts are ready to be first class scripts on the release package, otherwise we could move them to other folders as I do like your solution better.

@mboehm7 @niketanpansare  thoughts on the comment above ?

**Comment by deroneriksson** [comment]
@lresende Thanks for checking on this. The 'first-class' algorithms go in the primary scripts/algorithms directory. The 'second-class' scripts go in scripts/staging, which is excluded from all the artifacts (except in the src artifacts). By including scripts/algorithms/* and excluding scripts/staging/*, all first-class scripts are automatically included, and all second-class scripts are excluded. When an algorithm script has graduated, it is moved from scripts/staging/ to scripts/algorithms/ and will automatically be placed in each build artifact. A benefit of this PR is that we no longer need to manually add each first-class script to the assemblies, which can be error-prone.

@mboehm7 @niketanpansare Let me know if this is correct or if anything needs to be modified.

**Comment by lresende** [comment]
Thanks @deroneriksson , LGTM

**Comment by niketanpansare** [comment]
Thanks Deron, LGTM :)

**Comment by mboehm7** [comment]
@deroneriksson I absolutely agree. Just one thing: If I'm not mistaken it needs to be "/scripts/..." instead of "scripts/..." when loaded from the resource stream.

**Comment by deroneriksson** [comment]
@mboehm7 I'll check this when I get to SF (getResourceAsStream with and without the initial "/")

**Comment by deroneriksson** [comment]
@mboehm7 You are correct WRT requiring the "/" for getResourceAsStream. I'll update to prepend the "/".

**Comment by deroneriksson** [comment]
@gweidner Could you check and see if this is working correctly from Scala? Thank you.

**Comment by deroneriksson** [comment]
@gweidner Thank you for the help testing. Could you test the latest commit? Thanks!

**Comment by gweidner** [comment]
Verified with test program that dml scripts read successfully from jar.  LGTM.
Thanks @deroneriksson !

**Comment by deroneriksson** [comment]
Thanks for all the help @gweidner ! I'll merge the PR.

**Comment by gweidner** [comment]
Sounds good!  Note Windows environment used.

**Pull request closed without merging**
