### PR TITLE
[SYSTEMML-1228] Cleanup monitoring util and switch to Spark 2.1.0

### PR DESCRIPTION
**Pull request by niketanpansare**
@bertholdreinwald  @mboehm7 @gweidner @dusenberrymw  @asurve  @deroneriksson

### CODE REVIEW

**Comment by deroneriksson** [comment]
LGTM. I am fine with this since I am not aware of anyone using this functionality and removing it gives cleaner code. The monitoring util is saved in git history for those wishing to reference it or if it needs to be restored.

**Comment by fschueler** [comment]
Always happy to remove stuff! 
You can link it to [SYSTEMML-1128](https://issues.apache.org/jira/browse/SYSTEMML-1228)

**Comment by gweidner** [comment]
Thank you for initiating the switch including cleanup of monitoring util!

I've pasted Jenkins test summary which is similar to PR build results for SYSTEMML-1128.
18:59:49 Tests in error: 
18:59:49   DataFrameRowFrameConversionTest.testRowLongConversionMultiDenseUnknown:173->testDataFrameConversion:237 Runtime
18:59:49   DataFrameRowFrameConversionTest.testRowDoubleConversionMultiDense:88->testDataFrameConversion:237 Runtime
18:59:49   DataFrameRowFrameConversionTest.testRowLongConversionMultiDense:168->testDataFrameConversion:237 Runtime
18:59:49   DataFrameRowFrameConversionTest.testRowDoubleConversionMultiDenseUnknown:93->testDataFrameConversion:237 Runtime
18:59:49   DataFrameRowFrameConversionTest.testRowLongConversionMultiSparseUnknown:183->testDataFrameConversion:237 Runtime
18:59:49   DataFrameRowFrameConversionTest.testRowLongConversionMultiSparse:178->testDataFrameConversion:237 Runtime
18:59:49   DataFrameRowFrameConversionTest.testRowDoubleConversionMultiSparse:98->testDataFrameConversion:237 Runtime
18:59:49   DataFrameRowFrameConversionTest.testRowDoubleConversionMultiSparseUnknown:103->testDataFrameConversion:237 Runtime
18:59:49   MLContextTest.testCreateDMLScriptBasedOnURL:186 » MLContext Error trying to re...
18:59:49 
18:59:49 Tests run: 6543, Failures: 0, Errors: 9, Skipped: 0

**Comment by niketanpansare** [comment]
@gweidner Are you able to reproduce these on your machine ?

**Comment by deroneriksson** [comment]
I'll start an on-demand build/test and see if it happens again for Jenkins. https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/

**Comment by gweidner** [comment]
For comparison, the tests failed in my local environment with java.lang.OutOfMemoryError: Java heap space:
Tests in error:
  DataFrameRowFrameConversionTest.testRowLongConversionMultiDenseUnknown:173->testDataFrameConversion:237 Runtime
DataFrameRowFrameConversionTest.testRowDoubleConversionMultiDense:88->testDataFrameConversion:237 Runtime
DataFrameRowFrameConversionTest.testRowLongConversionMultiDense:168->testDataFrameConversion:237 Runtime
DataFrameRowFrameConversionTest.testRowDoubleConversionMultiDenseUnknown:93->testDataFrameConversion:237 Runtime
DataFrameRowFrameConversionTest.testRowLongConversionMultiSparseUnknown:183->testDataFrameConversion:237 Runtime
DataFrameRowFrameConversionTest.testRowLongConversionMultiSparse:178->testDataFrameConversion:237 Runtime
DataFrameRowFrameConversionTest.testRowDoubleConversionMultiSparse:98->testDataFrameConversion:237 Runtime
DataFrameRowFrameConversionTest.testRowDoubleConversionMultiSparseUnknown:103->testDataFrameConversion:237 Runtime

Tests run: 24, Failures: 0, Errors: 8, Skipped: 0

Partial stack trace:

**Comment by gweidner** [comment]
Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1435)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1423)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1422)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1422)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
        at scala.Option.foreach(Option.scala:257)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:802)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1650)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1605)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1594)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
        at java.lang.Thread.getStackTrace(Thread.java:1203)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:628)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1918)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1931)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1944)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1958)
        at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:935)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
        at org.apache.spark.rdd.RDD.collect(RDD.scala:934)
        at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:275)
        at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$execute$1$1.apply(Dataset.scala:2371)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:57)
        at org.apache.spark.sql.Dataset.withNewExecutionId(Dataset.scala:2765)
        at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$execute$1(Dataset.scala:2370)
        at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collect(Dataset.scala:2377)
        at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2405)
        at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2404)
        at org.apache.spark.sql.Dataset.withCallback(Dataset.scala:2778)
        at org.apache.spark.sql.Dataset.count(Dataset.scala:2404)
        at org.apache.sysml.runtime.instructions.spark.utils.FrameRDDConverterUtils.dataFrameToBinaryBlock(FrameRDDConverterUtils.java:247)
        at org.apache.sysml.runtime.instructions.spark.utils.FrameRDDConverterUtils.dataFrameToBinaryBlock(FrameRDDConverterUtils.java:236)
        at org.apache.sysml.test.integration.functions.mlcontext.DataFrameRowFrameConversionTest.testDataFrameConversion(DataFrameRowFrameConversionTest.java:22
6)
        at org.apache.sysml.test.integration.functions.mlcontext.DataFrameRowFrameConversionTest.testRowDoubleConversionMultiSparseUnknown(DataFrameRowFrameConv
ersionTest.java:103)
Caused by: org.spark_project.guava.util.concurrent.ExecutionError: java.lang.OutOfMemoryError: Java heap space
        at org.spark_project.guava.cache.LocalCache$Segment.get(LocalCache.java:2261)
        at org.spark_project.guava.cache.LocalCache.get(LocalCache.java:4000)
        at org.spark_project.guava.cache.LocalCache.getOrLoad(LocalCache.java:4004)
        at org.spark_project.guava.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4874)
        at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$.compile(CodeGenerator.scala:890)
        at org.apache.spark.sql.catalyst.expressions.codegen.GenerateUnsafeProjection$.create(GenerateUnsafeProjection.scala:405)
        at org.apache.spark.sql.catalyst.expressions.codegen.GenerateUnsafeProjection$.create(GenerateUnsafeProjection.scala:359)
        at org.apache.spark.sql.catalyst.expressions.codegen.GenerateUnsafeProjection$.create(GenerateUnsafeProjection.scala:32)
        at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator.generate(CodeGenerator.scala:874)
        at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.extractProjection$lzycompute(ExpressionEncoder.scala:266)
        at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.extractProjection(ExpressionEncoder.scala:266)
        at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.toRow(ExpressionEncoder.scala:290)
        at org.apache.spark.sql.SparkSession$$anonfun$3.apply(SparkSession.scala:547)
        at org.apache.spark.sql.SparkSession$$anonfun$3.apply(SparkSession.scala:547)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.agg_doAggregateWithoutKey$(Unknown Source)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:126)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1170)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:640)
        at java.lang.Thread.run(Thread.java:853)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at org.codehaus.janino.util.ClassFile.loadAttribute(ClassFile.java:1508)
        at org.codehaus.janino.util.ClassFile.loadAttributes(ClassFile.java:644)
        at org.codehaus.janino.util.ClassFile.loadFields(ClassFile.java:623)
        at org.codehaus.janino.util.ClassFile.<init>(ClassFile.java:280)
        at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$$anonfun$recordCompilationStats$1.apply(CodeGenerator.scala:967)
        at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$$anonfun$recordCompilationStats$1.apply(CodeGenerator.scala:964)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$.recordCompilationStats(CodeGenerator.scala:964)
        at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$.org$apache$spark$sql$catalyst$expressions$codegen$CodeGenerator$$doCompile(CodeGener
ator.scala:936)
        at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$$anon$1.load(CodeGenerator.scala:998)
        at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$$anon$1.load(CodeGenerator.scala:995)
        at org.spark_project.guava.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3599)
        at org.spark_project.guava.cache.LocalCache$Segment.loadSync(LocalCache.java:2379)
        at org.spark_project.guava.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2342)
        at org.spark_project.guava.cache.LocalCache$Segment.get(LocalCache.java:2257)
        at org.spark_project.guava.cache.LocalCache.get(LocalCache.java:4000)
        at org.spark_project.guava.cache.LocalCache.getOrLoad(LocalCache.java:4004)
        at org.spark_project.guava.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4874)
        at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$.compile(CodeGenerator.scala:890)
        at org.apache.spark.sql.catalyst.expressions.codegen.GenerateUnsafeProjection$.create(GenerateUnsafeProjection.scala:405)
        at org.apache.spark.sql.catalyst.expressions.codegen.GenerateUnsafeProjection$.create(GenerateUnsafeProjection.scala:359)
        at org.apache.spark.sql.catalyst.expressions.codegen.GenerateUnsafeProjection$.create(GenerateUnsafeProjection.scala:32)
        at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator.generate(CodeGenerator.scala:874)
        at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.extractProjection$lzycompute(ExpressionEncoder.scala:266)
        at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.extractProjection(ExpressionEncoder.scala:266)
        at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.toRow(ExpressionEncoder.scala:290)
        at org.apache.spark.sql.SparkSession$$anonfun$3.apply(SparkSession.scala:547)
        at org.apache.spark.sql.SparkSession$$anonfun$3.apply(SparkSession.scala:547)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.agg_doAggregateWithoutKey$(Unknown Source)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:126)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1170)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:640)
        at java.lang.Thread.run(Thread.java:853)

**Comment by deroneriksson** [comment]
The re-run of Jenkins reported the issues with DataFrameRowFrameConversionTest.
```
19:59:18 Results :
19:59:18 
19:59:18 Failed tests: 
19:59:18   FullReblockTest.testCSVMultipleMSparseMR:407->runReblockTest:467 26 values are not in equal
19:59:18 
19:59:18 Tests in error: 
19:59:18   DataFrameRowFrameConversionTest.testRowLongConversionMultiDenseUnknown:173->testDataFrameConversion:237 Runtime
19:59:18   DataFrameRowFrameConversionTest.testRowDoubleConversionMultiDense:88->testDataFrameConversion:237 Runtime
19:59:18   DataFrameRowFrameConversionTest.testRowLongConversionMultiDense:168->testDataFrameConversion:237 Runtime
19:59:18   DataFrameRowFrameConversionTest.testRowDoubleConversionMultiDenseUnknown:93->testDataFrameConversion:237 Runtime
19:59:18   DataFrameRowFrameConversionTest.testRowLongConversionMultiSparseUnknown:183->testDataFrameConversion:237 Runtime
19:59:18   DataFrameRowFrameConversionTest.testRowLongConversionMultiSparse:178->testDataFrameConversion:237 Runtime
19:59:18   DataFrameRowFrameConversionTest.testRowDoubleConversionMultiSparse:98->testDataFrameConversion:237 Runtime
19:59:18   DataFrameRowFrameConversionTest.testRowDoubleConversionMultiSparseUnknown:103->testDataFrameConversion:237 Runtime
19:59:18 
19:59:18 Tests run: 6543, Failures: 1, Errors: 8, Skipped: 0
```

**Comment by niketanpansare** [comment]
The error is related to OOM caused by code generation in Spark SQL:
```bash
12:45:10 testRowLongConversionMultiDenseUnknown(org.apache.sysml.test.integration.functions.mlcontext.DataFrameRowFrameConversionTest)  Time elapsed: 13.378 sec  <<< ERROR!
12:45:10 java.lang.RuntimeException: org.apache.spark.SparkException: Job aborted due to stage failure: Task 7 in stage 0.0 failed 1 times, most recent failure: Lost task 7.0 in stage 0.0 (TID 7, localhost, executor driver): org.spark_project.guava.util.concurrent.ExecutionError: java.lang.OutOfMemoryError: Java heap space
12:45:10 	at org.spark_project.guava.cache.LocalCache$Segment.get(LocalCache.java:2261)
12:45:10 	at org.spark_project.guava.cache.LocalCache.get(LocalCache.java:4000)
12:45:10 	at org.spark_project.guava.cache.LocalCache.getOrLoad(LocalCache.java:4004)
12:45:10 	at org.spark_project.guava.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4874)
12:45:10 	at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$.compile(CodeGenerator.scala:890)
12:45:10 	at org.apache.spark.sql.catalyst.expressions.codegen.GenerateUnsafeProjection$.create(GenerateUnsafeProjection.scala:405)
12:45:10 	at org.apache.spark.sql.catalyst.expressions.codegen.GenerateUnsafeProjection$.create(GenerateUnsafeProjection.scala:359)
12:45:10 	at org.apache.spark.sql.catalyst.expressions.codegen.GenerateUnsafeProjection$.create(GenerateUnsafeProjection.scala:32)
12:45:10 	at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator.generate(CodeGenerator.scala:874)
12:45:10 	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.extractProjection$lzycompute(ExpressionEncoder.scala:266)
12:45:10 	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.extractProjection(ExpressionEncoder.scala:266)
12:45:10 	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.toRow(ExpressionEncoder.scala:290)
12:45:10 	at org.apache.spark.sql.SparkSession$$anonfun$3.apply(SparkSession.scala:547)
12:45:10 	at org.apache.spark.sql.SparkSession$$anonfun$3.apply(SparkSession.scala:547)
12:45:10 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
12:45:10 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
12:45:10 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
12:45:10 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.agg_doAggregateWithoutKey$(Unknown Source)
12:45:10 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
12:45:10 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
12:45:10 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
12:45:10 	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
12:45:10 	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:126)
12:45:10 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
12:45:10 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
12:45:10 	at org.apache.spark.scheduler.Task.run(Task.scala:99)
12:45:10 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
12:45:10 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
12:45:10 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
12:45:10 	at java.lang.Thread.run(Thread.java:745)
12:45:10 Caused by: java.lang.OutOfMemoryError: Java heap space
12:45:10 	at org.codehaus.janino.util.ClassFile.loadAttribute(ClassFile.java:1508)
12:45:10 	at org.codehaus.janino.util.ClassFile.loadAttributes(ClassFile.java:644)
12:45:10 	at org.codehaus.janino.util.ClassFile.loadFields(ClassFile.java:623)
12:45:10 	at org.codehaus.janino.util.ClassFile.<init>(ClassFile.java:280)
12:45:10 	at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$$anonfun$recordCompilationStats$1.apply(CodeGenerator.scala:967)
12:45:10 	at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$$anonfun$recordCompilationStats$1.apply(CodeGenerator.scala:964)
12:45:10 	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
12:45:10 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
12:45:10 	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
12:45:10 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
```

Setting the configuration [spark.sql.codegen.wholeStage to false](https://github.com/apache/incubator-systemml/pull/376/commits/3be3553a25dac040c03a775d123105f786556dec#diff-ca6fceb83dfd9c92c83c9bf8de937cdaR219) didnot help.

**Comment by asurve** [comment]
@niketanpansare Can you do explain on data frame involved in the test case to get explain statement?
e.g. df.explain(true)
This will generate explain output which will have multiple sections. Please get those sections and we can request Spark SQL team to look at it.

**Comment by niketanpansare** [comment]
Here is the output of `df.explain(true)` which as inserted at [DataFrameRowFrameConversionTest](https://github.com/niketanpansare/incubator-systemml/blob/fb99746a63e2a66b95474e1df4342c5de4f6c6e3/src/test/java/org/apache/sysml/test/integration/functions/mlcontext/DataFrameRowFrameConversionTest.java#L226):
```bash
== Parsed Logical Plan ==
LogicalRDD [__INDEX#1265, C1#1266L, C2#1267L, C3#1268L, C4#1269L, C5#1270L, C6#1271L, C7#1272L, C8#1273L, C9#1274L, C10#1275L, C11#1276L, C12#1277L, C13#1278L, C14#1279L, C15#1280L, C16#1281L, C17#1282L, C18#1283L, C19#1284L, C20#1285L, C21#1286L, C22#1287L, C23#1288L, ... 1241 more fields]

== Analyzed Logical Plan ==
__INDEX: double, C1: bigint, C2: bigint, C3: bigint, C4: bigint, C5: bigint, C6: bigint, C7: bigint, C8: bigint, C9: bigint, C10: bigint, C11: bigint, C12: bigint, C13: bigint, C14: bigint, C15: bigint, C16: bigint, C17: bigint, C18: bigint, C19: bigint, C20: bigint, C21: bigint, C22: bigint, C23: bigint, ... 1241 more fields
LogicalRDD [__INDEX#1265, C1#1266L, C2#1267L, C3#1268L, C4#1269L, C5#1270L, C6#1271L, C7#1272L, C8#1273L, C9#1274L, C10#1275L, C11#1276L, C12#1277L, C13#1278L, C14#1279L, C15#1280L, C16#1281L, C17#1282L, C18#1283L, C19#1284L, C20#1285L, C21#1286L, C22#1287L, C23#1288L, ... 1241 more fields]

== Optimized Logical Plan ==
LogicalRDD [__INDEX#1265, C1#1266L, C2#1267L, C3#1268L, C4#1269L, C5#1270L, C6#1271L, C7#1272L, C8#1273L, C9#1274L, C10#1275L, C11#1276L, C12#1277L, C13#1278L, C14#1279L, C15#1280L, C16#1281L, C17#1282L, C18#1283L, C19#1284L, C20#1285L, C21#1286L, C22#1287L, C23#1288L, ... 1241 more fields]

== Physical Plan ==
Scan ExistingRDD[__INDEX#1265,C1#1266L,C2#1267L,C3#1268L,C4#1269L,C5#1270L,C6#1271L,C7#1272L,C8#1273L,C9#1274L,C10#1275L,C11#1276L,C12#1277L,C13#1278L,C14#1279L,C15#1280L,C16#1281L,C17#1282L,C18#1283L,C19#1284L,C20#1285L,C21#1286L,C22#1287L,C23#1288L,... 1241 more fields]
```

**Comment by niketanpansare** [comment]
@mboehm7 @asurve Setting [spark.sql.codegen.wholeStage and spark.memory.offHeap.enabled](https://github.com/apache/incubator-systemml/pull/376/files#diff-ca6fceb83dfd9c92c83c9bf8de937cdaR219) to false didn't work. Still getting the same error.

**Comment by bertholdreinwald** [comment]
To move forward with this PR, I'd suggest to modify the test case, and put a note in the Release Notes suggesting a different memory configuration as a work around.

**Comment by niketanpansare** [comment]
Modified the test to use smaller data and [all tests passed](https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1103/).

**Pull request closed without merging**
