### PR TITLE
Update spark-mlcontext-programming-guide.md

### PR DESCRIPTION
**Pull request by romeokienzler**
added creation of sqlContext, otherwise it was not running on my Spark 1.6 jupyter notebook (datascience experience of IBM)

### CODE REVIEW

**Comment by akchinSTC** [comment]
Can an Admin verify this patch?

**Comment by romeokienzler** [comment]
Yes, just run the example and it should run without errors

**Comment by bertholdreinwald** [comment]
Thanks, Romeo. LGTM. But please change your comment in line 2290 from "in case it does not compile ..." to something like: "For Spark version <= 1.6.0 use createDataFrame(), and for Spark version >= 1.6.1 use .toDF()"

**Comment by romeokienzler** [comment]
ok, done, thanks for the suggestion, please let me know in case you want me to change something else..

**Comment by deroneriksson** [comment]
@romeokienzler Welcome to SystemML! Would you mind committing these changes on the master branch rather than the gh-pages branch? The master copy of the documentation lives on the master branch, and we push the docs subtree to gh-pages for publishing on GitHub. Since gh-pages has a different base directory from the master branch, this makes merging difficult.

**Comment by romeokienzler** [comment]
Ok, [done](https://github.com/apache/incubator-systemml/pull/246)

**Comment by deroneriksson** [comment]
add to whitelist

**Pull request closed without merging**
