### PR TITLE
Corrected typo in documentation

### PR DESCRIPTION
**Pull request by ethanyxu**
Correct syntax typo in 'if statement' documentation.
Added if - else if syntax.

### CODE REVIEW

**Comment by akchinSTC** [comment]
Can an Admin verify this patch?

**Comment by mboehm7** [comment]
thanks @ethanyxu - the addition of "if-else if-else" is useful but the "[ ]" indicates that the else branch is optional. Maybe you can merge both into meta level (both else-if and else branches are optional but else-if can occur many times)

**Comment by ethanyxu** [comment]
Ah I see thanks for the clarification. I included both 'else if' and 'else' both in the main syntax body with '[]'. Also reworded the description to reflect the change.

**Comment by mboehm7** [comment]
@ethanyxu could you please do one more cleanup: remove the sentence starting "The statement(s) in any of three bodies must be surrounded by braces ..." as this is not required and maybe even add a hint that we actually support this.

**Comment by ethanyxu** [comment]
Sure. It's edited accordingly.

**Comment by mboehm7** [comment]
LGTM - thanks @ethanyxu

**Pull request closed without merging**
