### PR TITLE
[SYSTEMML-838] Spark Shell docs for new MLContext

### PR DESCRIPTION
**Pull request by deroneriksson**
Updated Spark Shell documentation for new MLContext API.

Preview [here](http://deroneriksson.github.io/incubator-systemml/spark-mlcontext-programming-guide.html).

### CODE REVIEW

**Comment by dusenberrymw** [comment]
In general, this looks great!  Two quick things:

1. Can we swap the "Spark Shell" and "Statements" tabs, and show the "Statements" content by default?  Additionally, can we rename "Statements" to "Scala", in anticipation or also including Python syntax at some point?
2. Let's remove the Java example -- data scientists won't be using Java, and so it would be a good opportunity to slim down the docs.

**Comment by deroneriksson** [comment]
Thank you for reviewing @dusenberrymw 

1. I agree, Statements tab as the default increases readability. I'll make this change. Also I'll change Statements to Scala.
2. Agreed about the Java example. I'll remove it for now. We can create a new Java page if users express a need for it.

**Comment by deroneriksson** [comment]
Made requested updates. Preview [here](http://deroneriksson.github.io/incubator-systemml/spark-mlcontext-programming-guide.html).

**Comment by dusenberrymw** [comment]
LGTM.

**Pull request closed without merging**
