### PR TITLE
[SYSTEMML-922] Upgrade to latest ANTLR

### PR DESCRIPTION
**Pull request by gweidner**
Upgraded ANLTR to latest version 4.5.3 released March 2016.

### CODE REVIEW

**Comment by gweidner** [comment]
All unit tests passed with version 4.5:
https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/206/

Also ran Linear Regression example (genLinearRegression, sample, splitXY, LinearRegDS, GLM-predict) against spark-submit 1.6.1.

**Comment by gweidner** [comment]
Note spark 2.0 bundles antlr4-runtime-4.5.3.jar.

**Comment by gweidner** [comment]
Switched back to 4.5 used on test branch for on demand build 206 due to below error when using 4.5.3:

[INFO] --- antlr4-maven-plugin:4.5.3:antlr4 (antlr) @ systemml ---
[INFO] ANTLR 4: Processing source directory /a/workspace/SystemML-PullRequestBuilder/src/main/java
[INFO] Processing grammar: org/apache/sysml/parser/dml/Dml.g4
[INFO] Processing grammar: org/apache/sysml/parser/pydml/Pydml.g4
[ERROR] error(159): org/apache/sysml/parser/pydml/Pydml.g4:407:0: cannot declare a rule with reserved name SKIP
[ERROR] /a/workspace/SystemML-PullRequestBuilder/org/apache/sysml/parser/pydml/Pydml.g4 [407:0]: cannot declare a rule with reserved name SKIP

**Comment by gweidner** [comment]
Unit tests again passed in [PR build 659](https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/659/).

**Comment by deroneriksson** [comment]
Hi @gweidner. Would you mind seeing if the main SystemML artifacts will work after upgrading the ANTLR version? I have some examples at http://apache.github.io/incubator-systemml/release-process.html (search for the "# build distribution artifacts"). ANTLR has a couple compile-scope dependencies (see pom's antlr4-runtime entry) which can sometimes make things tricky.

**Comment by gweidner** [comment]
Great catch @deroneriksson!  Let me test those as well.  Also big thank you for showing license impact so more for me to do here.

**Comment by gweidner** [comment]
Clarification on differences between 4.5.x releases available here:
https://github.com/antlr/antlr4/releases

**Comment by gweidner** [comment]
From 4.5 section at https://github.com/antlr/antlr4/releases:
"Be aware that we no longer deploy a maven antlr4-annotations artifact and in fact we no longer use Java annotations in the Java runtime and so that code is disappeared."

So assemble/license files to be updated accordingly in additional commit under this PR.

**Comment by deroneriksson** [comment]
@gweidner Thank you for tracking down the dependency change. Removal of a compile-scope dependency is always a very welcome change. :-)

**Comment by gweidner** [comment]
In ANTLR 4.5.1, an issue was reported when rule used reserved name (e.g., SKIP).
    https://github.com/antlr/antlr4/issues/967
This was fixed in ANTLR 4.5.2:
    https://github.com/antlr/antlr4/issues/996
    https://github.com/antlr/antlr4/issues/1015
Pushed PyDML.g4 and pom.xml so rule name no longer conflicts with reserved name.
All tests passed with on-demand build https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/207/.

**Comment by gweidner** [comment]
Rebased/pushed new commits with updated LICENSE files to remove references to antlr4-annotations and switch jar version to 4.5.3.  Also changed standalone.xml to eliminate build warning:
[INFO] Reading assembly descriptor: src/assembly/standalone.xml
[WARNING] The following patterns were never triggered in this artifact exclusion filter:
'*:antlr4-annotations*'

**Comment by deroneriksson** [comment]
Hi @gweidner. If I run a "hello world", I see console output like the following:
```ANTLR Tool version 4.3 used for code generation does not match the current runtime version 4.5.3ANTLR Tool version 4.3 used for code generation does not match the current runtime version 4.5.3hello world```
Is that the expected output?

**Comment by deroneriksson** [comment]
WRT those messages I see, when I do a 'mvn clean package -P distribution', I see the following:
```
...
[INFO] --- antlr4-maven-plugin:4.5.3:antlr4 (antlr) @ systemml ---
[INFO] No grammars to process
[INFO] ANTLR 4: Processing source directory /Users/deroneriksson/Documents/workspace2/incubator-systemml/src/main/java
...
```

So does that mean that the Java files aren't being properly generated by the maven plugin since it says "No grammars to process"?

**Comment by gweidner** [comment]
Hi @deroneriksson,
Thanks for reviewing and testing.  The 'No grammars to process' occurs since the src/main/java/*.tokens files don't get deleted when doing a mvn clean.  You need to manually delete them before doing your distribution build.  This is also why I didn't catch the initial issue when switching between 4.5.3 in my development environment as compared to build machine which starts with clean workspace.  So manually delete the 4 .tokens files to get them processed under new antlr.

**Comment by gweidner** [comment]
Also - for the previous question regarding the ANTRL mismatch warning.  That's exactly the message that this patch fixes.  I was able to test the first cases described at http://apache.github.io/incubator-systemml/release-process.html using artifacts from https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/679/org.apache.systemml$systemml/ and do not see that message.

**Comment by gweidner** [comment]
I'm pasting the results so far for standalone tar.gz, main jar, standalone jar:

[bigdata@duque1 build]$ cd systemml-0.11.0-incubating-SNAPSHOT-standalone
[bigdata@duque1 systemml-0.11.0-incubating-SNAPSHOT-standalone]$ echo "print('hello world');" > hello.dml
[bigdata@duque1 systemml-0.11.0-incubating-SNAPSHOT-standalone]$ ./runStandaloneSystemML.sh hello.dml
16/09/21 15:10:23 INFO api.DMLScript: BEGIN DML run 09/21/2016 15:10:23
hello world
16/09/21 15:10:24 INFO api.DMLScript: SystemML Statistics:
Total execution time:		0.330 sec.
Number of executed MR Jobs:	0.
16/09/21 15:10:24 INFO api.DMLScript: END DML run 09/21/2016 15:10:24

[bigdata@duque1 systemml-0.11.0-incubating-SNAPSHOT-standalone]$ cd ..
[bigdata@duque1 build]$ mkdir lib
[bigdata@duque1 build]$ cp -R systemml-0.11.0-incubating-SNAPSHOT-standalone/lib/* lib/
[bigdata@duque1 build]$ rm lib/systemml-0.11.0-incubating-SNAPSHOT.jar

[bigdata@duque1 build]$ java -cp ./lib/*:systemml-0.11.0-incubating-SNAPSHOT.jar org.apache.sysml.api.DMLScript -s "print('hello world');"
log4j:WARN No appenders could be found for logger (org.apache.hadoop.util.Shell).
log4j:WARN Please initialize the log4j system properly.
hello world

[bigdata@duque1 build]$ java -jar systemml-0.11.0-incubating-SNAPSHOT-standalone.jar -s "print('hello world');"
16/09/21 15:19:45 INFO api.DMLScript: BEGIN DML run 09/21/2016 15:19:45
16/09/21 15:19:45 INFO api.DMLScript: HADOOP_HOME: null
16/09/21 15:19:45 INFO conf.DMLConfig: Using internal default configuration settings.  If you wish to customize any settings, please supply a `SystemML-config.xml` file.
hello world
16/09/21 15:19:45 INFO api.DMLScript: SystemML Statistics:
Total execution time:		0.184 sec.
Number of executed MR Jobs:	0.
16/09/21 15:19:45 INFO api.DMLScript: END DML run 09/21/2016 15:19:45
[bigdata@duque1 build]$ 

[bigdata@duque1 build]$ ls -la
total 74164
drwxrwxr-x 5 bigdata bigdata     4096 Sep 21 15:19 .
drwxrwxr-x 5 bigdata bigdata     4096 Sep 21 10:00 ..
drwxrwxr-x 3 bigdata bigdata     4096 Sep 21 15:15 lib
drwxrwxrwx 2 bigdata bigdata     4096 Sep 21 15:18 scratch_space
-rw-rw-r-- 1 bigdata bigdata  4757155 Sep 21 09:03 systemml-0.11.0-incubating-SNAPSHOT.jar
drwxrwxr-x 5 bigdata bigdata     4096 Sep 21 15:10 systemml-0.11.0-incubating-SNAPSHOT-standalone
-rw-rw-r-- 1 bigdata bigdata 33337481 Sep 21 09:03 systemml-0.11.0-incubating-SNAPSHOT-standalone.jar
-rw-rw-r-- 1 bigdata bigdata 28489606 Sep 21 09:03 systemml-0.11.0-incubating-SNAPSHOT-standalone.tar.gz
-rw-rw-r-- 1 bigdata bigdata  4568633 Sep 21 09:03 systemml-0.11.0-incubating-SNAPSHOT.tar.gz

**Comment by deroneriksson** [comment]
Great! I will try this out very soon! Perhaps in a separate PR we can work deleting those files into the build. Otherwise people may see the same warnings I saw and get confused.

**Comment by deroneriksson** [comment]
Great job Glenn! Removing the tokens files took care of that message during the build and took care of the ANTLR warning messages for me.

LGTM.

As a couple followups:
1) Perhaps we could create a JIRA to delete the tokens files and regenerate new ones during the build (and handle this as a separate PR).
2) I believe the previous antlr transitive dependency org.abego.treelayout.core may no longer be needed. I saw a couple warnings about "The following patterns were never triggered in this artifact exclusion filter: '*:org.abego.treelayout.core*'" for the standalone.xml assembly. So we probably need to remove this from the assembly and the LICENSE files if this is indeed the case. This would be good as a separate JIRA/PR if this is true.
(BTW I can look into this too if you are busy.)

**Comment by gweidner** [comment]
Thank you @deroneriksson for review!  Yes - I also encountered the org.abego.treelayout exclusion warning so thanks in advance for cleaning that up in separate jiras/pr.

**Pull request closed without merging**
