### PR TITLE
[SYSTEMML-1213][WIP] scalable linear algebra

### PR DESCRIPTION
**Pull request by iyounus**
This PR implements several scalable linear algebra algorithms described in epic:

https://issues.apache.org/jira/browse/SYSTEMML-1213

TODO: Implement SVD and Eigen

### CODE REVIEW

**Comment by niketanpansare** [comment]
Thanks @iyounus ... looking forward for this PR to be merged in :)

@prithvirajsen @bertholdreinwald  can you please review this PR ?

**Comment by deroneriksson** [comment]
@iyounus @dusenberrymw 
I'm not an ML expert but I'm inclined to merge this contribution. It's been here for 3 months and given the high quality of the DML, we should move it to staging.

**Comment by iyounus** [comment]
I think we should merge this to staging.

**Comment by deroneriksson** [comment]
Great! Thank you @iyounus

**Comment by deroneriksson** [comment]
I'll merge.

**Pull request closed without merging**
