### PR TITLE
[SYSTEMML-999] Include tests in MLContext package suite

### PR DESCRIPTION
**Pull request by gweidner**
Included references to MLContextMultipleScriptsTest and MLContextScratchCleanupTest for MLContext package test suite.

### CODE REVIEW

**Comment by gweidner** [comment]
This will enable both classes to be included in test harness run which should result in 12 more tests.  After the release, I can check changing the pom to run the tests instead of package suite.

Daily build:
13:53:52 Tests run: 130, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 50.635 sec - in org.apache.sysml.test.integration.mlcontext.MLContextTest
13:54:01 Tests run: 21, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.515 sec - in org.apache.sysml.test.integration.mlcontext.MLContextFrameTest

**Comment by gweidner** [comment]
[PR build 712](https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/712/) in progress.

**Comment by deroneriksson** [comment]
LGTM.

**Comment by gweidner** [comment]
Thank you for reviewing Deron!  I've also synchronized the Frame functions package suite test class which won't impact the test harness.  I will merge after the initial PR build completes.

**Comment by gweidner** [comment]
Also updated legacy MLContext functions package test suite class which will not impact the test harness as those are already being included.  Wish I had caught those before and combined into one commit to prevent multiple PR builds...

**Comment by gweidner** [comment]
[PR build 712](https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/712/) completed successfully.

17:31:52 Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.489 sec - in org.apache.sysml.test.integration.mlcontext.MLContextMultipleScriptsTest
17:32:18 Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 25.612 sec - in org.apache.sysml.test.integration.mlcontext.MLContextScratchCleanupTest

18:01:37 Tests run: 6320, Failures: 0, Errors: 0, Skipped: 0

**Comment by mboehm7** [comment]
LGTM - thanks for catching this

**Comment by gweidner** [comment]
Thank you @mboehm7 for reviewing - much appreciated!  The tests were helping me gain better understanding of Frame's usage related to docs for SYSTEMML-565.

**Pull request closed without merging**
