### PR TITLE
[SYSTEMML-1211] Update Hadoop 2.6.0 Windows 64-bit binaries

### PR DESCRIPTION
**Pull request by gweidner**
Updated each existing file in src\test\config\hadoop_bin_windows to Hadoop 2.6.0 Windows 64-bit.

### CODE REVIEW

**Comment by deroneriksson** [comment]
cc @mboehm7

**Comment by gweidner** [comment]
Tested from console with functions.data test suite (minus RandRuntimePlatformTest):

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
AutomatedTestBase has detected a Windows OS and is overriding
hadoop.home.dir and java.library.path.
Running org.apache.sysml.test.integration.functions.data.FullReblockTest
Tests run: 54, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 167.086 sec - in org.apache.sysml.test.integration.functions.data.FullReblockTest
Running org.apache.sysml.test.integration.functions.data.FullStringInitializeTest
Tests run: 39, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.32 sec - in org.apache.sysml.test.integration.functions.data.FullStringInitializeTest
Running org.apache.sysml.test.integration.functions.data.RandTest1
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.14 sec - in org.apache.sysml.test.integration.functions.data.RandTest1
Running org.apache.sysml.test.integration.functions.data.RandTest2
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.09 sec - in org.apache.sysml.test.integration.functions.data.RandTest2
Running org.apache.sysml.test.integration.functions.data.RandTest3
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.05 sec - in org.apache.sysml.test.integration.functions.data.RandTest3
Running org.apache.sysml.test.integration.functions.data.RandTest4
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.14 sec - in org.apache.sysml.test.integration.functions.data.RandTest4
Running org.apache.sysml.test.integration.functions.data.RandTest5
Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 39.6 sec - in org.apache.sysml.test.integration.functions.data.RandTest5
Running org.apache.sysml.test.integration.functions.data.RandVarMinMaxTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 41.98 sec - in org.apache.sysml.test.integration.functions.data.RandVarMinMaxTest
Running org.apache.sysml.test.integration.functions.data.RandVarSeedTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.44 sec - in org.apache.sysml.test.integration.functions.data.RandVarSeedTest
Running org.apache.sysml.test.integration.functions.data.ReadMMTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.81 sec - in org.apache.sysml.test.integration.functions.data.ReadMMTest
Running org.apache.sysml.test.integration.functions.data.ReblockTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.11 sec - in org.apache.sysml.test.integration.functions.data.ReblockTest
Running org.apache.sysml.test.integration.functions.data.VariableTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.13 sec - in org.apache.sysml.test.integration.functions.data.VariableTest
Running org.apache.sysml.test.integration.functions.data.WriteMMTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.282 sec - in org.apache.sysml.test.integration.functions.data.WriteMMTest
Running org.apache.sysml.test.integration.functions.data.SequenceTest
Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 55.786 sec - in org.apache.sysml.test.integration.functions.data.SequenceTest
Running org.apache.sysml.test.integration.functions.data.WriteTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.37 sec - in org.apache.sysml.test.integration.functions.data.WriteTest
Running org.apache.sysml.test.integration.functions.data.SampleTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.75 sec - in org.apache.sysml.test.integration.functions.data.SampleTest
getting access token
  [getToken] got user access token
getting user info
  [getUser] Got TokenUser info
  [getUser] userName: gweidner, domainName = SVL-GWEIDNER
  [getUser] userSid: S-1-5-21-733788388-244427222-2762894592-1000
  [getUser] domainSid: S-1-5-21-733788388-244427222-2762894592
getting primary group
  [getPrimaryGroup] Got TokenPrimaryGroup info
  [getPrimaryGroup] primaryGroup: S-1-5-21-733788388-244427222-2762894592-513
getting supplementary groups
  [getGroups] Got TokenGroups info
  [getGroups] group 0: S-1-5-21-733788388-244427222-2762894592-513
  [getGroups] group 1: S-1-1-0
  [getGroups] group 2: S-1-5-114
  [getGroups] group 3: S-1-5-21-733788388-244427222-2762894592-1002
  [getGroups] group 4: S-1-5-32-544
  [getGroups] group 5: S-1-5-32-545
  [getGroups] group 6: S-1-5-4
  [getGroups] group 7: S-1-2-1
  [getGroups] group 8: S-1-5-11
  [getGroups] group 9: S-1-5-15
  [getGroups] group 10: S-1-5-113
  [getGroups] group 11: S-1-5-5-0-1047349
  [getGroups] group 12: S-1-2-0
  [getGroups] group 13: S-1-5-64-10
  [getGroups] group 14: S-1-16-12288
getting impersonation token
  [getImpersonationToken] token = 2336

Results :

Tests run: 183, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- maven-failsafe-plugin:2.17:verify (default) @ systemml ---
[INFO] Failsafe report directory: C:\git\incubator-systemml\target\failsafe-reports
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:48 min
[INFO] Finished at: 2017-02-17T17:05:37-08:00
[INFO] Final Memory: 100M/499M
[INFO] ------------------------------------------------------------------------

**Comment by mboehm7** [comment]
LGTM - works like a charm; thanks @gweidner

**Comment by gweidner** [comment]
Great! I will merge.

**Pull request closed without merging**
