### PR TITLE
Delete unused GLM test files

### PR DESCRIPTION
**Pull request by deroneriksson**
Deleted 2 crc files and 2 mtd files.

Test build completed successfully [here](https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/34/).

### CODE REVIEW

**Comment by oza** [comment]
How about also updating .gitignore not to include crc file?

**Comment by shirisht** [comment]
LGTM

**Comment by deroneriksson** [comment]
PR merged.

**Comment by deroneriksson** [comment]
Excellent idea @oza . That's a great way to prevent crc files from accidentally being committed in the future. Perhaps you'd like to do a PR? Thank you!

**Comment by oza** [comment]
@deroneriksson Opened #20. Could you check it? Thanks!

**Pull request closed without merging**
