### PR TITLE
Add an entry of crc files to .gitignore

### PR DESCRIPTION
**Pull request by oza**

### CODE REVIEW

**Comment by deroneriksson** [comment]
Test build completed successfully [here](https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/35/).

LGTM.

**Comment by deroneriksson** [comment]
PR merged. Thank you @oza !

**Comment by deroneriksson** [comment]
Hello @oza . Could you close this PR since it has been merged in? I didn't have it automatically done by asfgit. Thank you!

**Comment by oza** [comment]
@deroneriksson closing this. thank you!

**Pull request closed without merging**
