### PR TITLE
[SYSTEMML-1524] Move `nn` library to `scripts/nn`

### PR DESCRIPTION
**Pull request by dusenberrymw**
This moves the SystemML `nn` deep learning library from the staging directory to the top-level `scripts` directory.  The aim is to have the library ready for full release by the 1.0 release, alongside Caffe2DML, GPU support, and native BLAS.

### CODE REVIEW

**Comment by dusenberrymw** [comment]
cc @niketanpansare, @deroneriksson, @nakul02, @frreiss, @mboehm7, @prithvirajsen, @bertholdreinwald

**Comment by mboehm7** [comment]
in general, I think it's fine to graduate this nn library in 1.0 (predicated on sufficient performance testing), but why not put it into /scripts/algorithms/nn?

**Comment by deroneriksson** [comment]
Putting it in scripts allows the source statements to utilize package-style imports (SYSTEMML-1476) with nn as the base, such as `source("nn/examples/mnist_softmax.dml") as mnist_softmax`

**Comment by deroneriksson** [comment]
LGTM. Thank you for this great contribution to the project @dusenberrymw.

**Comment by niketanpansare** [comment]
LGTM :+1:

**Comment by dusenberrymw** [comment]
Thanks, I'll merge this.  The plan is to start running all algorithms from `scripts`, rather than from inside `scripts/algorithms`.  Therefore, `nn`, `algorithms`, `datagen`, etc. become DML packages that can be sourced from other DML scripts.

**Comment by akchinSTC** [comment]
Build successful

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1384/

**Pull request closed without merging**
