### PR TITLE
[SYSTEMML]Systemml package api code polish

### PR DESCRIPTION
**Pull request by GrapeBaBa**
I created this PR for polishing some codes which when I looked through using intellij. You can comment on it, review it and merge it.

### CODE REVIEW

**Comment by akchinSTC** [comment]
Can an Admin verify this patch?

**Comment by shirisht** [comment]
Most changes are cleanups and cosmetic. They look good.
LGTM

**Comment by dusenberrymw** [comment]
add to whitelist.

**Comment by deroneriksson** [comment]
Thank you @GrapeBaBa for the updates. They look good.

If you could make the following updates, that would be great:
1) Add "import java.util.Collections" to DMLScript.java
2) Add "import java.util.Collections" to PreparedScript.java
3) For readability, could you revert SparkMonitoringUtil's isInterestingCP method back to its original form?

**Comment by GrapeBaBa** [comment]
@deroneriksson Done.

**Comment by deroneriksson** [comment]
Looks good to me. Thank you @GrapeBaBa

**Pull request closed without merging**
