### PR TITLE
[SYSTEMML-568] Frame Schema support through MLContext

### PR DESCRIPTION
**Pull request by asurve**
Schema propagation through DataFrame/JavaRDD/RDD has been handled.

### CODE REVIEW

**Comment by mboehm7** [comment]
please fix the modified dataFrameToBinaryBlock - if the schema is given but no column names, you miss to extract the column names.

**Comment by asurve** [comment]
ok, added.

**Comment by mboehm7** [comment]
thanks - one thing you might wanna double check though, is the integration of this extended converter. Right now there is not a single invocation with a schema other than DF schemas (which was the functionality provided before).

**Comment by mboehm7** [comment]
LGTM - thanks @asurve

**Pull request closed without merging**
