### PR TITLE
[SYSTEMML-1266] Replace README.txt In Release Package

### PR DESCRIPTION
**Pull request by gweidner**
Replaced contents with readme.md as requested/directed.

### CODE REVIEW

**Comment by gweidner** [comment]
@asurve

**Comment by deroneriksson** [comment]
LGTM. Thanks @gweidner!

When there is more time, we should consider changing src/main/standalone/* to src/main/resources/bin/*, or move it to src/main/resources/standalone/*. We can do string substitution variables with maven filtering to avoid hardcoding version numbers, since we can pull the version number from the pom.

**Comment by gweidner** [comment]
Thank you @deroneriksson for reviewing!  That's a good idea regarding resource filtering.  I'll merge this PR but keep the JIRA open for that.

**Comment by deroneriksson** [comment]
Cool! Thanks @gweidner

**Pull request closed without merging**
