### PR TITLE
[SYSTEMML-847] Remove LogisticRegression and LogisticRegressionModel

### PR DESCRIPTION
**Pull request by gweidner**
The Java classes in api/javaml can be removed since corresponding Scala versions exist in api/ml.

### CODE REVIEW

**Comment by gweidner** [comment]
This incorporates comments from PR #202 and simplifies potential issues between different Spark versions, e.g., [SYSTEMML-744].

**Comment by niketanpansare** [comment]
+1 for removing api/javaml

**Comment by dusenberrymw** [comment]
LGTM.

**Comment by gweidner** [comment]
Thank you Mike and Niketan!  I will merge.

**Pull request closed without merging**
