### PR TITLE
[SYSTEMML-296] Add elif (else if) to PyDML

### PR DESCRIPTION
**Pull request by nishi-t**
This patch adds "elif" to PyDML for addressing the [SYSTEMML-296](https://issues.apache.org/jira/browse/SYSTEMML-296). The "elif" statements are used as follows:
```
x = 6
if (x == 1):
    print('A')
elif (x == 2):
    print('B')
elif (x == 3):
    print('C')
elif (x == 4):
    print('D')
elif (x == 5):
    print('E')
else:
    print('F')
```

Please review @deroneriksson .

### CODE REVIEW

**Comment by deroneriksson** [comment]
Thank you @nishi-t. I tried it out and it works great. This is a very useful contribution!

@dusenberrymw That is a great suggestion (to add some short tests for this). @nishi-t, in case it helps, for a script like:
```
def ifTest(x: int):
    if (x == 1):
       print('A')

z = ifTest(1)
```
you can set the expected output in the Java test using something like:
```
setExpectedStdOut("A");
```

**Comment by nishi-t** [comment]
@dusenberrymw, @deroneriksson Thank you for your comments. I add tests in the commit			  436e26c. Please review again.

**Comment by nishi-t** [comment]
Sorry, I closed this PR by mistake.

**Comment by deroneriksson** [comment]
LGTM. Thank you @nishi-t!

**Pull request closed without merging**
