### PR TITLE
[SYSTEMML-137] Add Java format profile

### PR DESCRIPTION
**Pull request by deroneriksson**
Add "SystemML Format" profile for standardizing Java formatting in project.
Add Java Format and DML Format sections to Contributing to SystemML document.

### CODE REVIEW

**Comment by deroneriksson** [comment]
For more information, see https://www.mail-archive.com/dev@systemml.incubator.apache.org/msg01723.html

Note: original I was going to base our Java style on the Google StyleGuide (https://github.com/google/styleguide), but its license (https://creativecommons.org/licenses/by/3.0/) appears to be "weak copyleft" which probably is not compatible with the Apache license when including source code (see https://www.apache.org/legal/resolved.html).

Therefore, this style template is an export based on the current Eclipse standard format. It utilizes tab characters for indentation, as discussed on the mailing list.

cc @mboehm7 @lresende

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1474/

**Comment by nakul02** [comment]
I am already using this in intellij, thanks @deroneriksson. LGTM 👍

**Comment by deroneriksson** [comment]
Thank you for reviewing @nakul02! I'll merge.

**Pull request closed without merging**
