### PR TITLE
autoencoder script for acoustic signal modeling

### PR DESCRIPTION
**Pull request by prithvirajsen**
Script learns a 2-layer, bowtie autoencoder. Meant for acoustic signal modeling use case.

### CODE REVIEW

**Comment by prithvirajsen** [comment]
@bertholdreinwald can you please review this PR ?

**Comment by bertholdreinwald** [comment]
Thanks, @prithvirajsen . Couple of minor comments.
* expand on the alg description a little more, pretty much the stuff that you put under “OTHER DETAILS”.
* formatting of input/output parameter description (use table format as in PCA.dml), show default values.
* document parameter “HIDDEN”
* formatting of DML
* please consider using approach scripts/utils/shuffle.dml for randomization.
* can you print out current epoch# in loop

**Comment by prithvirajsen** [comment]
@bertholdreinwald:

Implemented most of your comments (HIDDEN is an output param and was documented).

I didn't implement the resuffling mechanism from shuffle.dml because this script (possibly) reshuffles 2 times. The first time is to reshuffle the input. The second time is to reshuffle the hidden layer representations (if the user asks for it). The second reshuffle is to get back the original order of rows. Essentially, the script ensures that the ith input's hidden representation is produced at the ith row of HIDDEN. If this is not the case then the output will be less useful.

Currently, the script generates a permutation matrix to shuffle the input and then uses the transpose of the same permutation matrix to get back the original order. This requires 1 transpose and 1 mat-mult. The same can be achieved by using the ops in shuffle.dml (store the rand col of numbers, append it, and the order in 'DESCENDING' order I guess) but I'm not sure it guarantees the reverse shuffling. Specifically, I'm worried about randomly generating the same numbers and then trying to reverse the order given these random numbers. The current reshuffling in the script guarantees the shuffling and re-shuffling.

Please take a look when you get a chance.

**Comment by bertholdreinwald** [comment]
LGTM, but for epochs please output (as.integer(floor(iter / num_iters_per_epoch))+1), other we get funny output.

epochs=0.0 BATCH beg=1 end=36 obj=315.2793607485832
epochs=0.3333333333333333 BATCH beg=37 end=72 obj=416.8550718408468
epochs=0.6666666666666666 BATCH beg=73 end=100 obj=234.10341156641397
epochs=1.0 BATCH beg=1 end=36 obj=315.0943812440362
epochs=1.3333333333333333 BATCH beg=37 end=72 obj=416.508133010481
epochs=1.6666666666666667 BATCH beg=73 end=100 obj=233.85472614907434
...

**Comment by deroneriksson** [comment]
Not sure if it's useful here, but `print` can do printf-style formatting now, such as:
```
a=0.3333333333333333;b=37;c=72;d=416.8550718408468;
print("epochs=%5.2f BATCH beg=%d end=%d obj=%f",a,b,c,d);
```
```
epochs= 0.33 BATCH beg=37 end=72 obj=416.855072
```

**Comment by prithvirajsen** [comment]
Thanks @deroneriksson.

Prints now look like this:

epochs=0.3550 BATCH beg=3395585 end=3395840 obj=1115.490457
epochs=0.3550 BATCH beg=3395841 end=3396096 obj=4688.646200
epochs=0.3550 BATCH beg=3396097 end=3396352 obj=876.882540
epochs=0.3550 BATCH beg=3396353 end=3396608 obj=2600.199443
epochs=0.3551 BATCH beg=3396609 end=3396864 obj=1901.713796
epochs=0.3551 BATCH beg=3396865 end=3397120 obj=1131.922849
epochs=0.3551 BATCH beg=3397121 end=3397376 obj=965.788354
epochs=0.3552 BATCH beg=3397377 end=3397632 obj=1038.282066
epochs=0.3552 BATCH beg=3397633 end=3397888 obj=928.889698
epochs=0.3552 BATCH beg=3397889 end=3398144 obj=863.360051
epochs=0.3552 BATCH beg=3398145 end=3398400 obj=997.383946
epochs=0.3553 BATCH beg=3398401 end=3398656 obj=1071.794773
epochs=0.3553 BATCH beg=3398657 end=3398912 obj=938.326127
epochs=0.3553 BATCH beg=3398913 end=3399168 obj=3162.734174
epochs=0.3553 BATCH beg=3399169 end=3399424 obj=1408.637403
epochs=0.3554 BATCH beg=3399425 end=3399680 obj=1779.825666

**Comment by deroneriksson** [comment]
cc @bertholdreinwald

**Comment by bertholdreinwald** [comment]
If I specify EPOCH=5, why wouldn't output something like below?
     
epochs=1 BATCH beg=1 end=36 obj=333.5321282824677
epochs=1 BATCH beg=37 end=72 obj=376.1876087271806
epochs=1 BATCH beg=73 end=100 obj=326.178655631146
epochs=2 BATCH beg=1 end=36 obj=331.9129286464535
epochs=2 BATCH beg=37 end=72 obj=373.56627535210464
epochs=2 BATCH beg=73 end=100 obj=323.35089531556406
epochs=3 BATCH beg=1 end=36 obj=328.47310930175695
epochs=3 BATCH beg=37 end=72 obj=369.2092662046429
epochs=3 BATCH beg=73 end=100 obj=319.2854824307684
epochs=4 BATCH beg=1 end=36 obj=323.99037576269365
epochs=4 BATCH beg=37 end=72 obj=363.91977787672346
epochs=4 BATCH beg=73 end=100 obj=314.607825509929
epochs=5 BATCH beg=1 end=36 obj=319.0495604231955
epochs=5 BATCH beg=37 end=72 obj=358.2880984843614
epochs=5 BATCH beg=73 end=100 obj=309.76786285993416

**Comment by prithvirajsen** [comment]
@bertholdreinwald 

because then it would look like this:

epochs= 0 BATCH beg=412417 end=412672 obj=1069.072806
epochs= 0 BATCH beg=412673 end=412928 obj=1069.850879
epochs= 0 BATCH beg=412929 end=413184 obj=1163.560893
epochs= 0 BATCH beg=413185 end=413440 obj=1343.846801
epochs= 0 BATCH beg=413441 end=413696 obj=12527.075951
epochs= 0 BATCH beg=413697 end=413952 obj=3142.970939
epochs= 0 BATCH beg=413953 end=414208 obj=1943.204630
epochs= 0 BATCH beg=414209 end=414464 obj=1136.792265
epochs= 0 BATCH beg=414465 end=414720 obj=1098.481554
epochs= 0 BATCH beg=414721 end=414976 obj=1393.703967
epochs= 0 BATCH beg=414977 end=415232 obj=1448.993297
epochs= 0 BATCH beg=415233 end=415488 obj=1150.492752
epochs= 0 BATCH beg=415489 end=415744 obj=1359.559109
epochs= 0 BATCH beg=415745 end=416000 obj=7236.440789
epochs= 0 BATCH beg=416001 end=416256 obj=1165.586541
epochs= 0 BATCH beg=416257 end=416512 obj=1066.075759
epochs= 0 BATCH beg=416513 end=416768 obj=3471.969641
epochs= 0 BATCH beg=416769 end=417024 obj=1178.097062
epochs= 0 BATCH beg=417025 end=417280 obj=1353.061137
epochs= 0 BATCH beg=417281 end=417536 obj=1465.652910
epochs= 0 BATCH beg=417537 end=417792 obj=1395.716999

doesn't really inform about progress, IMO.

**Comment by deroneriksson** [comment]
Thank you @prithvirajsen! I'll merge.

**Pull request closed without merging**
