### PR TITLE
[SYSTEMML-1465] Add stain normalization to breast cancer preprocessing.

### PR DESCRIPTION
**Pull request by dusenberrymw**
This function normalizes the staining of H&E histology slides for the
breast cancer project.

### CODE REVIEW

**Comment by dusenberrymw** [comment]
@iyounus Can you review this?

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1477/

**Comment by deroneriksson** [comment]
cc @iyounus

**Comment by iyounus** [comment]
LGTM. The only thing I'm not clear about is the stain_ref. These are hard coded numbers and its not very clear to me where these are coming from. Is it fixed for the whole analysis?

**Comment by dusenberrymw** [comment]
Thanks, @iyounus.  Yeah the `stain_ref` and `max_sat_ref` are constants that represent the stain vectors (i.e. top 2 eigen vectors or SVD directions projected back into optical density space) and saturations (after solving for sats given the optical density values and the computed stain vecs) from a slide with a desired or ideal coloring.

**Pull request closed without merging**
