### PR TITLE
[SYSTEMML-1168] Document printf functionality

### PR DESCRIPTION
**Pull request by deroneriksson**
Add print function's multi-argument printf formatting capabilities
to the DML Language Reference.

### CODE REVIEW

**Comment by deroneriksson** [comment]
Can be previewed here: http://deroneriksson.github.io/incubator-systemml/dml-language-reference.html#other-built-in-functions

**Comment by deroneriksson** [comment]
cc @nakul02

**Comment by nakul02** [comment]
LGTM

**Comment by deroneriksson** [comment]
Thank you for reviewing @nakul02.

**Pull request closed without merging**
