### PR TITLE
[SYSTEMML-1139] Tighten maven integration for python artifact

### PR DESCRIPTION
**Pull request by deroneriksson**
Move first exec-maven-plugin reference under maven-antrun-plugin to attempt to
allow python artifact build to be executed during package phase (since dependent
on presence of SystemML.jar generated by maven-antrun-plugin).

Use maven-resources-plugin version of Apache parent pom.

Increment exec-maven-plugin version to 1.5.0.

Use maven-resources-plugin's copy-resources goal to do string substitutions with
project version number in project-info.py file copied to python directory to
allow python to reference properties from pom.xml.

Consolidate pre_setup.py content into setup.py.

Change python execution to package phase.

Set destination directory of python artifact to target using --dist-dir argument.

Include wink and antlr in python artifact license.

Update setup.py to read maven-based project properties from project-info.py.

Update setup.py to clean up temporary files used to build python artifact.

### CODE REVIEW

**Comment by niketanpansare** [comment]
@deroneriksson  Thanks Deron, this PR certainly makes the build process of python artifact much more maven friendly. A subset of the changes in this PR were addressed in https://github.com/apache/incubator-systemml/pull/290. Please see https://github.com/apache/incubator-systemml/pull/290#issuecomment-261740561 for list of task addressed in that PR. Would you mind waiting until I merge the PR 290 ?

**Comment by deroneriksson** [comment]
@niketanpansare That sounds great. I'll modify this PR as needed once #290 is merged in.

**Comment by deroneriksson** [comment]
cc @lresende

**Comment by dusenberrymw** [comment]
Thanks, @deroneriksson for working on this.  It will definitely be great to have the Python binary distribution created with the Maven for release.  Unfortunately, I'm seeing a regression with this PR that no longer allows for regular Python installations from the folder itself.  For example, `pip install -e src/main/python` should still install the Python package to allow for quick, iterative dev work (of course we'd still have to run PySpark with the JAR included, but that's fine for dev work).

Both of these should work independently still.

* Dev install:
```
# Note: Maven & Python are independent here, i.e., the Python stuff should install without Maven.
mvn clean
pip3 install -e src/main/python
mvn clean package
PYSPARK_PYTHON=ipython3 pyspark --driver-class-path $SYSTEMML_HOME/target/SystemML.jar

import systemml as sml
import numpy as np
m1 = sml.matrix(np.ones((3,3)) + 2)
m2 = sml.matrix(np.ones((3,3)) + 3)
m2 = m1 * (m2 + m1)
m4 = 1.0 - m2
m4.sum(axis=1).toNumPy()
```
* Binary artifact install (for official releases on PyPI):
```
mvn clean package -P distribution
pip3 install target/systemml-0.12.0-incubating-SNAPSHOT.dev0.tar.gz
PYSPARK_PYTHON=ipython3 pyspark

import systemml as sml
import numpy as np
m1 = sml.matrix(np.ones((3,3)) + 2)
m2 = sml.matrix(np.ones((3,3)) + 3)
m2 = m1 * (m2 + m1)
m4 = 1.0 - m2
m4.sum(axis=1).toNumPy()
```

**Comment by deroneriksson** [comment]
@dusenberrymw Thanks for the awesome feedback! I'm experienced with Maven but completely new to Python so your review is extremely helpful. Thank you for the detailed instructions which will help me replicate and fix the issues.

**Comment by deroneriksson** [comment]
@dusenberrymw Would you mind having a look at this PR when you have time? I've taken #290 and your feedback and made several updates.

**Comment by deroneriksson** [comment]
Great! Thanks for all the help with this PR.

**Pull request closed without merging**
