### PR TITLE
[SYSTEMML-1279] Decrease numCols to prevent spark codegen issue

### PR DESCRIPTION
**Pull request by fschueler**
This should work around getting an exception from spark codegen.

### CODE REVIEW

**Comment by deroneriksson** [comment]
LGTM. The underlying issue isn't resolved but this does prevent the current warning which can be disconcerting to a new user. Thanks @fschueler!

**Comment by deroneriksson** [comment]
Would you might updating line 127 (For demonstration purposes, we’ll use Spark to create a DataFrame called df of random doubles from 0 to 1 consisting of 10,000 rows and 1,000 columns.)?

**Comment by deroneriksson** [comment]
And "For performance, we’ll specify metadata indicating that the matrix has 10,000 rows and 1,000 columns."

**Comment by fschueler** [comment]
I updated the two lines - they didn't fit my previous search pattern ;)

**Comment by deroneriksson** [comment]
Thanks @fschueler!

**Pull request closed without merging**
