### PR TITLE
Update spark-mlcontext-programming-guide.md

### PR DESCRIPTION
**Pull request by romeokienzler**
Added code for Spark 1.6 since the example breaks on Spark 1.6

### CODE REVIEW

**Comment by akchinSTC** [comment]
Can an Admin verify this patch?

**Comment by romeokienzler** [comment]
Yes, just run the code on Spark 1.6.X and it breaks, use my two lines and it works on 1.6.X

**Comment by deroneriksson** [comment]
Hi @romeokienzler. In PR245 you also included the import and creation of the sqlContext. Should this be included or should this PR be merged as is?

Thank you for committing to the master branch.

**Comment by deroneriksson** [comment]
add to whitelist

**Comment by deroneriksson** [comment]
Actually, looking at the usage, the current commit looks great since the sqlContext is used in the commented code. LGTM. Thank you @romeokienzler. I will merge.

**Comment by deroneriksson** [comment]
This update is now available publicly here: http://apache.github.io/incubator-systemml/spark-mlcontext-programming-guide.html

**Comment by romeokienzler** [comment]
@deroneriksson I've double checked, the SQL-Context is needed indeed, so I've created a new [pull request](https://github.com/apache/incubator-systemml/pull/248)

**Comment by romeokienzler** [comment]
@deroneriksson [Here](https://apache.github.io/incubator-systemml/spark-mlcontext-programming-guide#helper-methods-1) the sqlContext is needed again, that's the reason I've created it - now I've commited a better solution by importing import sqlContext.implicits._ I don't know (since this tutorial is written for Zeppelin and I'm using jupyther on IBM Data Science Workbench if sqlContext and the import for sqlContext.implicits._ is done by Zeppelin itself, do you know that? But anyways, this solution works for [this](https://apache.github.io/incubator-systemml/spark-mlcontext-programming-guide#generate-linear-regression-test-data) but [this](https://apache.github.io/incubator-systemml/spark-mlcontext-programming-guide#helper-methods-1) definitely doesn't work in Jupyter. Once [this](https://github.com/apache/incubator-systemml/pull/248) pull request is merged I can work on the fix for [this](https://apache.github.io/incubator-systemml/spark-mlcontext-programming-guide#helper-methods-1)  section as well

**Pull request closed without merging**
