### PR TITLE
[SYSTEMML-876] Update RowGenerator in FrameConverterTest

### PR DESCRIPTION
**Pull request by gweidner**
Added schema processing to prevent potential error in newer spark.

### CODE REVIEW

**Comment by gweidner** [comment]
This is valid for both spark 1.x and spark 2.  The original fix was from:
https://github.com/gweidner/incubator-systemml/commit/afcf6cb82daab40b36366b73aca79d2b615c7b23

**Comment by gweidner** [comment]
Note getRowRDD refactored in https://github.com/apache/incubator-systemml/pull/223.

**Comment by gweidner** [comment]
Thank you @asurve for incorporating this into [SYSTEMML-568] including runtime.util.UtilFunctions refactoring.  Closing PR.

**Comment by mboehm7** [comment]
just for the future - it is important to keep files that are used in all backends free from Spark-specific imports; otherwise we get classnotfound errors in settings where spark libs are not in the classpath. Thanks.

**Comment by gweidner** [comment]
Thank you @mboehm7 for the reminder as I just saw your commit.  Note this PR did not introduce/propose the refactoring into runtime.util.UtilFunctions.

**Pull request closed without merging**
