### PR TITLE
Updating pom.xml to have variables of hadoop and antlr versions and to remove tailing spaces. 

### PR DESCRIPTION
**Pull request by oza**
Updating pom.xml to have variables for versions of hadoop and antlr and to remove tailing spaces. 

The versions of Hadoop and antlr are used in multiple sections manually: this PR fixes it and changes to use variable - hadoop.version and antlr.version.

We can also pass the version as arguments of maven command like ```mvn clean package -Dhadoop.verion=2.4.1```.

### CODE REVIEW

**Comment by dusenberrymw** [comment]
Test build started [here](https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/32/).

**Comment by dusenberrymw** [comment]
Hi, thanks for contributing this!  As usual, I've started a test build, and pending the results of that, this looks good to me.

**Comment by oza** [comment]
@dusenberrymw thank you for the review. The test looks to be passed?

**Comment by dusenberrymw** [comment]
Testing successful.

**Comment by dusenberrymw** [comment]
Merged.  Thanks, @oza!

**Comment by oza** [comment]
Thank you for committing :-)

**Pull request closed without merging**
