### PR TITLE
Improve structure of doc presentation

### PR DESCRIPTION
**Pull request by deroneriksson**
Update index.md and global.html to present available docs
in a more structured format, while additionally conveying
more information in index.md about the capabilities to be
found in the existing docs.
Add Apache license to hadoop-batch-mode.md.

Can currently be viewed [here](http://deroneriksson.github.io/incubator-systemml/).
For comparison, current index is [here](http://apache.github.io/incubator-systemml/).

### CODE REVIEW

**Comment by dusenberrymw** [comment]
This is great!  Can we get this into the 0.9 release?  It would be good for our first Apache release to have decently organized documentation.

cc @lresende, @mboehm7

**Comment by deroneriksson** [comment]
@dusenberrymw I'd be happy if it made the 0.9 release. Improvement over the previous layout which was basically a list of files.

**Comment by dusenberrymw** [comment]
@deroneriksson Definitely.  Also, I have a few thoughts:
1. Can you rename `MLContext` to `Spark MLContext`?
2. Can you change the order from `Hadoop Batch, Spark Batch, Spark MLContext` to `Spark Batch, Spark MLContext, Hadoop Batch`?
3.  Can you rename `DML and PyDML Programming Guide` to `DML and PyDML Beginner Programming Guide`?

**Comment by deroneriksson** [comment]
@dusenberrymw 
WRT
1. MLContext is also an API from Java so perhaps the existing generic name covers more ground, although the Spark Shell seems like the natural way to use the MLContext.
2. Emphasizing Spark is nice given the direction of the project.
3. Renaming programming guide is a good idea. I think Shirish and I came to a similar conclusion since that existing doc features language details for beginners, whereas a Programming Guide should probably deal with things such as parallelizing algorithms and things like that.

**Comment by dusenberrymw** [comment]
@deroneriksson 
1.  I  thought `MLContext` was an API for running SystemML on Spark that can be accessed via Scala or Java.  Is it possible to use `MLContext` via Java without Spark?

**Comment by deroneriksson** [comment]
@dusenberrymw 
You are correct. My mistake. I was thinking of "Spark Shell MLContext" rather than "Spark MLContext".

**Comment by dusenberrymw** [comment]
@deroneriksson No problem!  Also, I think it would be good to get the word `Scala` on the page as well.  Perhaps we can make the following changes as well?  Would likely help with SEO.
4. `Spark MLContext is a programmatic API to SystemML.` -> `Spark MLContext is a programmatic API to running SystemML from Spark via Scala or Java.`
5. `See the MLContext Programming Guide for Spark Shell ...` -> `See the MLContext Programming Guide for Spark Shell (Scala) ...`
6. Perhaps change `Spark Shell` to `Spark Shell (Scala)` within the MLContext programming guide itself.

Again, this restructure of the documentation is great!

**Comment by deroneriksson** [comment]
@dusenberrymw
Made requested updates.
Also renamed MLContext Programming Guide to include Spark in the title.
Also added analytics to documentation site.

Updates can be reviewed [here](http://deroneriksson.github.io/incubator-systemml/).

**Comment by dusenberrymw** [comment]
Fantastic.  This LGTM.  Thanks @deroneriksson!

**Pull request closed without merging**
