### PR TITLE
Include guava in standalone distributions

### PR DESCRIPTION
**Pull request by deroneriksson**
Guava needs to be included in the standalone distributions (tar.gz, zip, and uberjar) in order for them to work. Thank you for finding this @dusenberrymw

### CODE REVIEW

**Comment by deroneriksson** [comment]
@dusenberrymw Could you see if the latest commit fixes the issue you ran into?

**Comment by niketanpansare** [comment]
@deroneriksson This PR fixes the guava issue that I was facing on standalone jar. Thanks :+1:

**Comment by deroneriksson** [comment]
Thank you for checking @niketanpansare. I appreciate it!

@dusenberrymw I think this also resolve the protobuf-java jar issue. When you have time, can you let me know if your mnist example with the standalone jar runs successfully for you?

**Comment by dusenberrymw** [comment]
@deroneriksson Thanks, that fixes the issue!

**Comment by deroneriksson** [comment]
Note: I did not commit the NOTICE updates since these are not needed. For more information, see [PR180](https://github.com/apache/incubator-systemml/pull/180).

**Pull request closed without merging**
