### PR TITLE
[systemml-578] refactor ml api package to set scala version as default

### PR DESCRIPTION
**Pull request by Wenpei**
Refactore ml api package. 
org/apache/sysml/api/ml/scala->org/apache/sysml/api/ml
org/apache/sysml/api/ml -> org/apache/sysml/api/javaml (there is build issues when I change to "sysml/api/ml/java", that make "import java.io.File" failed)

@dusenberrymw Please help to take a look.

### CODE REVIEW

**Comment by dusenberrymw** [comment]
Thanks, @Wenpei!

@niketanpansare Do you have any additional thoughts on this?  Moving to Scala for the MLPipeline-style wrappers should help us promote the plans for PR #108.

**Comment by niketanpansare** [comment]
@Wenpei @dusenberrymw +1 for keeping scala as default version and removing java mlpipeline wrappers. 

@Wenpei Please make sure that code works through spark-shell:
import org.apache.spark.ml.Pipeline
import org.apache.sysml.api.ml.LogisticRegression
import org.apache.spark.ml.evaluation.BinaryClassificationEvaluator
import org.apache.spark.ml.feature.{HashingTF, Tokenizer}
import org.apache.spark.ml.tuning.{ParamGridBuilder, CrossValidator}
import org.apache.spark.mllib.linalg.Vector
case class LabeledDocument(id: Long, text: String, label: Double)
case class Document(id: Long, text: String)
val training = sc.parallelize(Seq(
     LabeledDocument(0L, "a b c d e spark", 1.0),
     LabeledDocument(1L, "b d", 2.0),
     LabeledDocument(2L, "spark f g h", 1.0),
     LabeledDocument(3L, "hadoop mapreduce", 2.0),
     LabeledDocument(4L, "b spark who", 1.0),
     LabeledDocument(5L, "g d a y", 2.0),
     LabeledDocument(6L, "spark fly", 1.0),
     LabeledDocument(7L, "was mapreduce", 2.0),
     LabeledDocument(8L, "e spark program", 1.0),
     LabeledDocument(9L, "a e c l", 2.0),
     LabeledDocument(10L, "spark compile", 1.0),
     LabeledDocument(11L, "hadoop software", 2.0)))
val tokenizer = new Tokenizer().setInputCol("text").setOutputCol("words")
val hashingTF = new HashingTF().setNumFeatures(1000).setInputCol(tokenizer.getOutputCol).setOutputCol("features")
val lr = new LogisticRegression(sc, sqlContext)
val pipeline = new Pipeline().setStages(Array(tokenizer, hashingTF, lr))
val crossval = new CrossValidator().setEstimator(pipeline).setEvaluator(new BinaryClassificationEvaluator)
val paramGrid = new ParamGridBuilder().addGrid(hashingTF.numFeatures, Array(10, 100, 1000)).addGrid(lr.regParam, Array(0.1, 0.01)).build()
crossval.setEstimatorParamMaps(paramGrid)
crossval.setNumFolds(2)
val cvModel = crossval.fit(training.toDF)
val test = sc.parallelize(Seq(
      Document(12L, "spark i j k"),
      Document(13L, "l m n"),
      Document(14L, "mapreduce spark"),
      Document(15L, "apache hadoop")))
cvModel.transform(test.toDF).show

You may be missing the logic for getting the rawPrediction (which is required for CrossValidator): https://github.com/apache/incubator-systemml/blob/master/src/main/java/org/apache/sysml/api/ml/LogisticRegressionModel.java#L154

**Comment by mboehm7** [comment]
@niketanpansare could you please cast this test into an actual unit test to avoid those manual steps? Thanks.

**Comment by niketanpansare** [comment]
@mboehm7 Done. 

@Wenpei Please look into https://github.com/apache/incubator-systemml/pull/117 ... Creating a PR as MLPipeline CrossValidator example is failing. When you are done adding the fixes, you can OK both this PR :)

**Comment by niketanpansare** [comment]
@Wenpei Can you please add steps to install ScalaTest in http://apache.github.io/incubator-systemml/developer-tools-systemml.html ?

**Comment by Wenpei** [comment]
@niketanpansare Thanks. I add support for crossvalidator.
Actually, I plan to do some enhancement for current api.
Like parameter, and code clean up. Can be addressed in another pr.

**Comment by niketanpansare** [comment]
Looks good to me.

**Comment by niketanpansare** [comment]
Test this Jenkins.

**Comment by Wenpei** [comment]
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/271/
There is build status here. It pass

**Comment by niketanpansare** [comment]
@Wenpei Sorry, to add one more task ... Can you please add following logic to your PR ?

if the user has not provided DML path to LogisticRegression (for example: setDMLScriptPath(....)), then use https://github.com/apache/incubator-systemml/blob/master/src/main/scala/org/apache/sysml/api/ml/scala/ScriptsUtils.scala#L38 ... else use the user provided one.

Here is an example:
``` python
if(no path provided by user)
   ml.executeScript(ScriptsUtils.getDMLScript("GLM-predict"),paramsMap)
else
   ml.execute(ScriptsUtils.resolvePath(LogisticRegressionModel.scriptPath),paramsMap)
```

This will avoid any hassle of requiring environment variables.

**Comment by Wenpei** [comment]
@niketanpansare I do some check in ScriptsUtils to return full string of file but not a path.
Please help to review.

**Comment by niketanpansare** [comment]
Looks good to me.

@dusenberrymw @deroneriksson Please merge this PR. Thanks :)

**Comment by deroneriksson** [comment]
I'll merge. Thank you @Wenpei

**Comment by niketanpansare** [comment]
thanks @deroneriksson

**Pull request closed without merging**
