### PR TITLE
[SYSTEMML-1208] Mimic main website styles in project documentation

### PR DESCRIPTION
**Pull request by deroneriksson**
Update project documentation styles to be similar to main website styles.

### CODE REVIEW

**Comment by deroneriksson** [comment]
Preview here: http://deroneriksson.github.io/incubator-systemml/

Checked with Firefox, Chrome, and Safari on OS X.

**Comment by fschueler** [comment]
I love that it is integrated, but the orange font-color is making me dizzy! ;)

**Comment by deroneriksson** [comment]
Maybe I could tone down the orange. I darkened the main text font color since it's nice to have a darker color when reading lots of documentation.

**Comment by deroneriksson** [comment]
@fschueler What do you think about dimming the link orange from `#FF5003` to `#FF7032`?

**Comment by fschueler** [comment]
I was looking at the MLContext section and because there are so many links it just made it a big orange wall. I actually like the current green/turquise/whatever color it is.

But I guess that's a matter of taste here ;)

**Comment by deroneriksson** [comment]
I like both. I think toning down the orange is good since it blends in more now when pages have lots of links. It might be good to not use bold/strong font weights with the orange too (we have a lot on the Overview page) since the orange is already such a strong color.

**Comment by deroneriksson** [comment]
@fschueler @gweidner 
Do you think this is ready to merge?

**Comment by gweidner** [comment]
Thank you @deroneriksson !
LGTM

**Pull request closed without merging**
