### PR TITLE
[HOTFIX] Added missing method that caused systemml not to compile

### PR DESCRIPTION
**Pull request by nakul02**

### CODE REVIEW

**Comment by nakul02** [comment]
@deroneriksson, @niketanpansare - Sorry about my previous PR #319. My work got overwritten when I rebased against upstream/master and I didn't compile to check.

**Comment by deroneriksson** [comment]
Thanks for the fix @nakul02! I'll review.

**Comment by deroneriksson** [comment]
LGTM. Thank you @nakul02! I'll merge.

**Comment by nakul02** [comment]
thanks @deroneriksson

**Pull request closed without merging**
