### PR TITLE
[SYSTEMML-868] Switch default to scala 2.10

### PR DESCRIPTION
**Pull request by gweidner**
Reverted default scala version to 2.10 and added scala 2.11 profile.

### CODE REVIEW

**Comment by gweidner** [comment]
Also updated JavaConversion calls.  Adding reflection to resolve differences to be addressed in separate PR.

**Comment by gweidner** [comment]
For additional context, here's link to original JavaConversions commit:
https://github.com/apache/incubator-systemml/commit/955526046e1c1d4057a05e3646ed0f74972bebe1
and original scala profile commit:
https://github.com/apache/incubator-systemml/commit/f2ea8770ea79232e49bd57d9761de2c1f8823300

**Comment by deroneriksson** [comment]
Hi @gweidner.

It turns out I was mistaken about the JavaConversions. Please see https://issues.apache.org/jira/browse/SYSTEMML-866. The seqAsJavaList and mapAsScalaMap are available in both 2.11 and 2.10, so the Java code shouldn't need any modifications.

**Comment by gweidner** [comment]
Thank you Deron for catching!  I will revert the JavaConversion changes.
Initial tests passed:
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/597/

**Comment by gweidner** [comment]
Tests in progress after restoring JavaConversions seqAsJavaList and mapAsScalaMap:
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/598/

**Comment by deroneriksson** [comment]
LGTM. Thank you @gweidner

**Comment by gweidner** [comment]
Thank you for reviewing!  All tests passed - I will merge.

**Pull request closed without merging**
