### PR TITLE
[SYSTEMML-857][SYSTEMML-858] Release process for docs and version

### PR DESCRIPTION
**Pull request by deroneriksson**
Describe release process for documentation.
Update documentation version in _config.yml.
Add version number to global documentation header.

### CODE REVIEW

**Comment by deroneriksson** [comment]
Preview here: http://deroneriksson.github.io/incubator-systemml/release-process.html

**Comment by deroneriksson** [comment]
Renders correctly on OS X with Firefox, Chrome, and Safari. Will try out Windows browsers tonight.

**Comment by deroneriksson** [comment]
Added white-space nowrap to projecttitle class to prevent title from wrapping with IE10 on Windows.

**Comment by gweidner** [comment]
Verified version number shown on Windows with IE11.  Thanks for doing this Deron!

LGTM

**Comment by deroneriksson** [comment]
Thank you for reviewing @gweidner! I will merge.

**Pull request closed without merging**
