### PR TITLE
[SYSTEMML-474] MLContext matrix from URL

### PR DESCRIPTION
**Pull request by deroneriksson**
Initial support reading IJV and CSV matrices into MLContext via URLs.

### CODE REVIEW

**Comment by deroneriksson** [comment]
Basic example:
```
val habermanUrl = "http://archive.ics.uci.edu/ml/machine-learning-databases/haberman/haberman.data"
val typesRDD = sc.parallelize(Array("1.0,1.0,1.0,2.0"))
val scriptUrl = "https://raw.githubusercontent.com/apache/incubator-systemml/master/scripts/algorithms/Univar-Stats.dml"
val uni = dmlFromUrl(scriptUrl).in("A", new java.net.URL(habermanUrl)).in("K", typesRDD).in("$CONSOLE_OUTPUT", true)
ml.execute(uni)
```

**Comment by gweidner** [comment]
This will be a great feature - thanks for adding!  The one thing noticed is it appears the RAT failed, likely due to the new *.ijv data files.  The pom may need updating to include them in the exclude filters.  Thanks!

**Comment by deroneriksson** [comment]
Thank you for reviewing and catching that, @gweidner. I will make the update.

**Comment by gweidner** [comment]
Thank you for the update.  The corresponding PR build has passed the RAT check since tests in progress:
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/560/console

LGTM

**Comment by deroneriksson** [comment]
Thank you @gweidner. All tests pass except the two tests which require IJV matrices on URLs, which will exist when this PR is merged. I will merge.

**Comment by gweidner** [comment]
Thank you for merging Deron!

**Pull request closed without merging**
