### PR TITLE
[SYSTEMML-1408] Add padding parameters to max-pooling layers

### PR DESCRIPTION
**Pull request by dusenberrymw**
This adds padding parameters to the max-pooling layers, along with the
associated tests.  Also, there are some general code formatting updates.

### CODE REVIEW

**Comment by dusenberrymw** [comment]
cc @niketanpansare I found a bug in the built-in `max_pool` function for any padding arguments >= 1.  The correctness test for the case of `pad=1` starting at [line 253 of `nn/test/test.dml`](https://github.com/apache/incubator-systemml/pull/434/files#diff-1bf477d6aaa03d877d364a7b997b9715R253) showcases the error.  This test simply checks the max pooling layers for correctness, using the matrices as described in the file.

Looking at the error and the code in `LibMatrixDNN.java`, I think it may be a striding issue.

To run, please `cd $SYSTEMML_HOME/scripts/staging/SystemML`, then `../../../bin/systemml nn/test/tests.dml`.  The test referenced above will output `"- Testing for correct behavior against known answer w/ pad=1"`.

**Comment by niketanpansare** [comment]
Thanks @dusenberrymw I will look into it :)

**Comment by dusenberrymw** [comment]
@niketanpansare To give the high-level summary, here is the issue:

The test is a manual check of 2x2, stride-2 max pooling with 1 pixel padding on a specified matrix.  The DML version gives the correct answer, while the built-in version does not.  Everything is fine with padding=0.

Matrix:
```
  # -- channel 1
  #  0  0  0  0  0  0
  #  0  1  2  3  4  0
  #  0  5  6  7  8  0
  #  0  9 10 11 12  0
  #  0 13 14 15 16  0
  #  0  0  0  0  0  0
  # -- channel 2
  #  0  0  0  0  0  0
  #  0  1  5  9 13  0
  #  0  2  6 10 14  0
  #  0  3  7 11 15  0
  #  0  4  8 12 16  0
  #  0  0  0  0  0  0
```

Correct output:
```
  # -- channel 1
  #  1  3  4
  #  9 11 12
  # 13 15 16
  # -- channel 2
  #  1  9 13
  #  3 11 15
  #  4 12 16
```

Builtin output:
```
  # -- channel 1
  #  2  3  4
  # 10 11 12
  # 14 15 16
  # -- channel 2
  #  5  9 13
  #  7 11 15
  #  8 12 16
```

**Comment by dusenberrymw** [comment]
@niketanpansare I think I figured out the behavior -- the builtin version is (1) *not* adding the 1st and 6th **columns** of padding, and (2) is performing **stride-1** max-pooling on the partially-padded matrix. 

Partially-padded matrix:
Matrix:
```
  # -- channel 1
  #   0  0  0  0
  #   1  2  3  4
  #   5  6  7  8
  #   9 10 11 12
  #  13 14 15 16
  #   0  0  0  0
  # -- channel 2
  #   0  0  0  0
  #   1  5  9 13
  #   2  6 10 14
  #   3  7 11 15
  #   4  8 12 16
  #   0  0  0  0
```

**Comment by dusenberrymw** [comment]
@niketanpansare I've figured out the issue in `LibMatrixDNN.java`, and I'll update the PR soon with the fix.

**Comment by niketanpansare** [comment]
@dusenberrymw If you have not started, please hold off on working on it. I am working on it: https://github.com/niketanpansare/incubator-systemml/tree/maxpool

**Comment by dusenberrymw** [comment]
@niketanpansare Haha, well I had fixed the forward pass, and looking at your commits, we converged on the same forward solution in terms of `fillIndexesArray` and the zero-padded rows in `doPooling`.  Looks like you've already started on the backward pass as well, so I would suggest just continuing.  I'll push some more DML test cases that I wrote to this PR (negative matrices, etc.)

**Comment by dusenberrymw** [comment]
@niketanpansare Also, I created [SYSTEMML-1428](https://issues.apache.org/jira/browse/SYSTEMML-1428) for the bug.

**Comment by dusenberrymw** [comment]
@niketanpansare Okay, I added more DML test cases.  All tests should run with no `ERROR` messages once the max pooling bugs are fixed.

**Comment by dusenberrymw** [comment]
@niketanpansare Also, here was my max pooling forward pass fix: https://github.com/dusenberrymw/incubator-systemml/commit/d7c5a238c3f6a0c86603e83426a40d9583e1ebbc

**Comment by niketanpansare** [comment]
Hahah ... same fix !! ... there is another corner case, which I am looking into and will deliver the fix soon :)

**Comment by dusenberrymw** [comment]
@niketanpansare Okay I extended the `nn::util::pad_image` function with a `pad_value` parameter, and updated the other max pooling layers to use a negative infinity (`pad_value=-1/0`) as the padding value.  All tests are passing now on top of your PR.  Let's merge these.

Also, are you using `nn::util::pad_image` at all in Barista?

**Pull request closed without merging**
