### PR TITLE
[SYSTEMML-1602] Improve formatting of heavy hitter output

### PR DESCRIPTION
**Pull request by deroneriksson**
Align heavy hitter instruction statistics in columns in tabular format.
Add nanosecond column to display instruction times less than a millisecond.

### CODE REVIEW

**Comment by deroneriksson** [comment]
Example:

Previously:
```
Heavy hitter instructions (name, time, count):
-- 1) 	toString 	0.002 sec 	2	
-- 2) 	*2 	0.001 sec 	2	
-- 3) 	createvar 	0.001 sec 	4	
-- 4) 	sinit 	0.000 sec 	2	
-- 5) 	print 	0.000 sec 	4	
-- 6) 	rmvar 	0.000 sec 	13	
-- 7) 	+ 	0.000 sec 	1	
-- 8) 	- 	0.000 sec 	1	
-- 9) 	* 	0.000 sec 	1	
-- 10) 	assignvar 	0.000 sec 	3	
```

Currently:
```
Heavy hitter instructions:
 #  Instruction  Time(s)   Time(ns)  Count
 1  toString       0.002  1,655,874      2
 2  *2             0.001  1,476,019      2
 3  createvar      0.001    939,814      4
 4  sinit          0.000    309,999      2
 5  print          0.000    260,029      4
 6  rmvar          0.000     79,944     13
 7  +              0.000     13,455      1
 8  -              0.000     12,238      1
 9  assignvar      0.000      9,568      3
10  *              0.000      8,631      1
```

**Comment by mboehm7** [comment]
Please drop the redundant time in nanoseconds. These heavy hitter instructions show aggregates - so anything below millisecond granularity is pretty much irrelevant. We measure times internally at nanosecond granularity because you might have billions of small operations that might take less than a millisecond. Also, please collapse the header to a single line.

**Comment by deroneriksson** [comment]
@mboehm7 @dusenberrymw 
I'll restore the old behavior for all parts of the project except the new MLContext.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1466/

**Comment by mboehm7** [comment]
I would recommend to keep the APIs consistent. What was the motivation for showing the times in nano second resolution?

**Comment by nakul02** [comment]
This new formatting is good, but do we want to consider the possibility of printing out the heavy hitters in different formats? One that is friendly to view on stdout (the way this PR does it) and another that is friendly to copy-pasting into a spreadsheet (tab separated)?

@deroneriksson  - having different outputs for different resolutions (less than 0.001s) might be confusing. If the output format is the same, I can immediately look for change in performance info in iterative experiments at exactly the same (relative) location on my screen.

**Comment by deroneriksson** [comment]
Hi @mboehm7 

My motivation to add ns display was for situations where times are very short (short 'hello world' types of DML scripts), since it can feel a little disconcerting to me to see instructions that take '0.000' time, such as:
```
Heavy hitter instructions:
 #  Instruction  Time(s)   Time(ns)  Count
 1  toString       0.002  1,618,379      2
 2  *2             0.001  1,422,184      2
 3  createvar      0.001    966,002      4
 4  sinit          0.000    339,480      2
 5  print          0.000    319,485      4
 6  rmvar          0.000     90,669     13
 7  +              0.000     17,325      1
 8  -              0.000     10,639      1
 9  assignvar      0.000      9,481      3
10  *              0.000      8,223      1
```

However, I agree that for most situations, the ns display is irrelevant and probably distracting.
```
Heavy hitter instructions:
 #  Instruction  Time(s)  Count
 1  wdivmm         2.324    923
 2  +*             0.937   2749
 3  *              0.746   1876
 4  tak+*          0.448    913
 5  uasqk+         0.402    923
 6  -*             0.292    913
 7  rand           0.065      9
 8  ba+*           0.057      1
 9  createvar      0.025   5554
10  ctable         0.019      1
```

I added a check to only display the ns column in the (rare) occasions where the times are very very small. Perhaps that might be a good compromise?

**Comment by deroneriksson** [comment]
@nakul02 @mboehm7 
It sounds like ns display causes more issues than it solves. I'll remove it.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1471/

**Comment by deroneriksson** [comment]
Thank you for reviewing @dusenberrymw. I'll merge.

@nakul02 @mboehm7 
If the current format causes any issues for anyone, please feel free to modify or revert.

**Pull request closed without merging**
