### PR TITLE
[SYSTEMML-776] Upgrade Spark version

### PR DESCRIPTION
**Pull request by gweidner**
Updated Spark version.

### CODE REVIEW

**Comment by gweidner** [comment]
All tests passed at https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/233/.

**Comment by asurve** [comment]
LGTM

Do we need to create artifacts with Spark version going forward? May be separate thread we can have discussion on.

**Comment by gweidner** [comment]
Thank you Arvind for reviewing!

**Comment by gweidner** [comment]
Tests in progress:
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1021/

**Pull request closed without merging**
