### PR TITLE
Update DML ref for rev, sign, cholesky, and aggregate

### PR DESCRIPTION
**Pull request by deroneriksson**
Also fix a table alignment needed after changing page fonts.

### CODE REVIEW

**Comment by deroneriksson** [comment]
Updates can be viewed [here](http://deroneriksson.github.io/incubator-systemml/dml-language-reference.html).

**Comment by mboehm7** [comment]
LGTM w/ a nice to have cleanup: instead of "in which case X is a regular matrix", we could be more specific "in which case X is a regular (n x m) matrix"

**Comment by deroneriksson** [comment]
@mboehm7 Updated doc with "(n x m)".

**Comment by mboehm7** [comment]
great thanks.

**Pull request closed without merging**
