### PR TITLE
[SYSTEMML-578] [SYSTEMML-580] Adding ScalaTest for MLPipeline wrappers

### PR DESCRIPTION
**Pull request by niketanpansare**
1. Adding ScalaAutomatedTestBase to make sure that ScalaTest run on
Windows environment.
2. Added test("test logistic regression with mlpipeline")

### CODE REVIEW

**Comment by niketanpansare** [comment]
@Wenpei Added MLPipeline test for the wrappers. The test ran successfully on my laptop. Please comment if you have any concerns.

@dusenberrymw @deroneriksson Please merge if @Wenpei is OK with it.

**Comment by dusenberrymw** [comment]
Is this different from #117?

**Comment by niketanpansare** [comment]
@dusenberrymw fixed the formatting and resolved conflicts.

**Comment by Wenpei** [comment]
LGTM.

**Comment by mboehm7** [comment]
it would be great if we could also automatically compare the results - maybe against a manually evaluated ground truth.

**Comment by deroneriksson** [comment]
@mboehm7 @niketanpansare Should I merge this PR or hold off for now?

**Comment by mboehm7** [comment]
LGTM - let's just ensure that over time we extend this to actual tests for correctness.

**Comment by deroneriksson** [comment]
Thank you @mboehm7 and @niketanpansare . I'll merge.

**Comment by niketanpansare** [comment]
Sorry for late reply, I agree with Matthias. We need to check for ground truth. Thanks @deroneriksson.

**Comment by deroneriksson** [comment]
@niketanpansare Could you file a JIRA for the ground truth check?

**Comment by niketanpansare** [comment]
Done. 

@Wenpei Do you want to take a look at https://issues.apache.org/jira/browse/SYSTEMML-646 ?

**Comment by dusenberrymw** [comment]
Also, we still need to adjust the package for these tests to place them in a test package, and then create a new test suite so that they will be run with Maven. There's already a JIRA issue tracking this with more details.

**Comment by deroneriksson** [comment]
Thank you @niketanpansare

**Comment by Wenpei** [comment]
@niketanpansare I will take a look for 646

**Comment by niketanpansare** [comment]
Thanks

**Pull request closed without merging**
