### PR TITLE
[Doc] Change PCA scale value

### PR DESCRIPTION
**Pull request by krishnakalyan3**
Currently in the matrix factorisation docs the value of scale is 10. 
This value can be either `0` or `1`.

### CODE REVIEW

**Comment by akchinSTC** [comment]
Can an Admin verify this patch?

**Comment by krishnakalyan3** [comment]
ping @deroneriksson @nakul02

**Comment by nakul02** [comment]
LGTM :+1: 
I shall merge.

**Comment by mboehm7** [comment]
the fix is fine; down the road, however, we should really consider to make scale, center, and projectdata boolean inputs in order to avoid such issues altogether.

**Pull request closed without merging**
