### PR TITLE
Minor doc changes in prep for the official 0.9 release.

### PR DESCRIPTION
**Pull request by dusenberrymw**
This fixes a few issues with mobile devices, updating Bootstrap and JQuery in the process.

Changes can be viewed [here](https://dusenberrymw.github.io/incubator-systemml).

### CODE REVIEW

**Comment by dusenberrymw** [comment]
cc @deroneriksson

**Comment by deroneriksson** [comment]
@dusenberrymw Good work!

Just have a couple formatting suggestions.

Was wondering about the alignment of the header content all the way to the left and the page text moved towards the left. Previously header area was centered, like [here](http://apache.github.io/incubator-systemml/index.html), which more closely matched main site [here](http://systemml.apache.org/). And the main text region was previously closer to the text alignment on the main site. Could the header area left edge be set to match the main site header left edge, and the left edge of text region be moved to match the main site text region left edge so that it has a more centered feel like the main site?

Also, perhaps for the subjects (that previously had the &nbsp;&nbsp to handle the left margin) in the Documentation dropdown menu, we could add a class to them with a margin-left of 5px or 10px or something to move it away from the left edge a little bit?

Otherwise awesome.

**Comment by dusenberrymw** [comment]
Haha, yeah I just changed the header alignment right as you were commenting.  I've added some left margin to the dropdown subjects as well.

**Comment by dusenberrymw** [comment]
The main website needs to be fixed in a similar manner to this change as well, as it is also a bit broken on tablets and mobile devices.

**Comment by mboehm7** [comment]
great thanks for the changes - just a quick general comment on the overview of "Running SystemML": it currently mixes up a couple of orthogonal dimensions: We support four different apis: command line, mlcontext, jmlc, spark ml. Standalone is just a packaging. Spark, hadoop, and singlenode are execution types - for example you can run the standalone package in hadoop execution mode. Down the road (not necessarily for the 0.9 release), we should clean this up.

**Comment by deroneriksson** [comment]
@dusenberrymw
Alignment looks good. Thank you.

**Comment by dusenberrymw** [comment]
Good thoughts, @mboehm7.  Perhaps after our official release, we can roll that and any user feedback/confusion into one nice update.

**Comment by dusenberrymw** [comment]
@deroneriksson Great, I'll merge this then.

**Comment by deroneriksson** [comment]
@dusenberrymw @mboehm7 
It would be great to have a good discussion regarding "Running SystemML" after this release.

**Comment by dusenberrymw** [comment]
FYI, I opened [SYSTEMML-470](https://issues.apache.org/jira/browse/SYSTEMML-470) to track the usability improvements regarding execution modes/types.

**Pull request closed without merging**
