### PR TITLE
[SYSTEMML-445] [WIP] Initial version of GPU backend

### PR DESCRIPTION
**Pull request by niketanpansare**
This version calls to CuDNN and CuBLAS using JCuda wrappers. Please DO NOT merge until we add sparse matrix multiplication (in LibMatrixCUDA) and ensure that our integration test suite runs successfully with TEST_GPU flag turned on. Currently, the tensor/* tests and binary/matrix/MatrixMultiplicationTest runs successfully.

@mboehm7 @bertholdreinwald @shirisht @dusenberrymw @nakul02  Please review the PR and provide suggestions.

### CODE REVIEW

**Comment by niketanpansare** [comment]
@nakul02 As we per our discussion, I included the dependency in POM rather than using mavenized JCuda. My guess is that included the jars might be throwing License errors (please see https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/391/):
17:28:04 [ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.11:check (default) on project systemml: Too many files with unapproved license: 1 See RAT report in: /a/workspace/SystemML-PullRequestBuilder/target/rat.txt -> [Help 1]

If you have time, can you look into license related issues and provide suggestions regarding packaging of JCuda into SystemML ?

**Comment by nakul02** [comment]
I had an offline discussion with @lresende and @deroneriksson.
There were some concerns about the way the pom file is being done.
I'll let them carry the discussion forward.

**Comment by mboehm7** [comment]
I would strongly recommend to hold off these major features until we actually made the 0.10 release; let's focus on robustness and fixes for now. Thanks.

**Comment by niketanpansare** [comment]
@mboehm7 I agree. This PR should not be part of 0.10 release. 

@nakul02 Sure, the PR is WIP and all suggestions are welcomed :)

As an FYI, if you want to follow the discussion on this topic, here are few links:
1. Link to mailing thread (May 3rd): https://www.mail-archive.com/dev@systemml.incubator.apache.org/msg00479.html
2. Link to JIRA (Jan 10th): https://issues.apache.org/jira/browse/SYSTEMML-445
3. Link to design document (Feb 26): https://docs.google.com/document/d/1eSBzP8dazetySZusH5cubqUurRH3KDjXJqdizLzVejA/edit

**Comment by deroneriksson** [comment]
My primary concern is the addition of actual jars to the project and the use of system scope. The maven 'way' is typically to reference artifacts in a maven repository (not necessarily central). Would it be possible to build these jcuda artifacts and put them in a publicly accessibly maven repo and reference this repo in the pom?

**Comment by niketanpansare** [comment]
Yes, since jcuda is open source, we can certainly create jcuda artifacts. Also, ideally I would prefer that too. However the problem is maintaining a public maven repo and hence I would defer that to Alan and/or Luciano.

**Comment by lresende** [comment]
We could add the jars on Maven central, or check if @akchinSTC can be of any help here. While first is preferable, latest might be easiest as we actually don't own jcuda.

**Comment by niketanpansare** [comment]
Just to clarify, whether we go to mvn central or host repo at STC, there are two options:
1. Deploy both the jar and libs. See https://github.com/MysterionRise/mavenized-jcuda/
2. Deploy just the jar (i.e. the ones that are included). In this case, we expect users to install the libs (example: libJCublas-linux-x86_64.so or JCublas-windows-x86_64.dll).

**Comment by niketanpansare** [comment]
@lresende @mboehm7 @deroneriksson @nakul02 I have removed the jars as well as system scope from our pom.xml. Also, I have updated the documentation to provide installation steps for JCuda. Please see https://github.com/niketanpansare/incubator-systemml/blob/1a52bd8908773593fb8b240b38ed0e81a33ebb3f/docs/devdocs/gpu-backend.md#setup-instructions-for-jcudacontext

**Comment by akchinSTC** [comment]
Test this Jenkins

**Comment by niketanpansare** [comment]
The tests passed: https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/410

**Comment by bertholdreinwald** [comment]
great job for an initial drop. Minor comments:
- the dependency on "mavenized-jcude-mvn-repo" is fragile, and only a snapshot. What is the release strategy for jcuda, and have proper maven coordinates?

- update the help in DMLScript.java to output proper flags

- for later, it would be good to see one example instruction with a cuda xt call.

**Comment by niketanpansare** [comment]
The test passed: https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/423/

**Comment by niketanpansare** [comment]
Closed by the commit https://github.com/apache/incubator-systemml/commit/f306b0b1ecd97fdb5755989f77728d1ca81358c5

**Pull request closed without merging**
