### PR TITLE
[SYSTEMML-1237] Add input float support to MLContext

### PR DESCRIPTION
**Pull request by deroneriksson**
Implicitly cast float to double in in(String, Object, Metadata) method
of Script class.

### CODE REVIEW

**Comment by deroneriksson** [comment]
Can test in spark shell with code such as:
```
$ spark-shell --executor-memory 4G --driver-memory 4G --driver-class-path=target/SystemML.jar

import org.apache.sysml.api.mlcontext._
import org.apache.sysml.api.mlcontext.ScriptFactory._
val ml = new MLContext(sc)
val scr = dml("c = a + b;")
val a:Float = 1
val b:Float = 2
scr.in("a", a).in("b", b).out("c")
print(ml.execute(scr).getDouble("c"))
```

**Comment by niketanpansare** [comment]
LGTM :+1:

**Comment by deroneriksson** [comment]
Thanks for reviewing @niketanpansare!

**Comment by deroneriksson** [comment]
All tests passed here: https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1084/

**Pull request closed without merging**
