### PR TITLE
[SYSTEMML-1400] Include pandas in required python packages

### PR DESCRIPTION
**Pull request by gweidner**
Updated setup.py to also include pandas for pip install so 'import systemml' is successful since dependency in converters.py.

### CODE REVIEW

**Comment by gweidner** [comment]
Note a minimum version was not included in the requirement specifier.  Observed version 0.19.2 installed in RHEL 7.2 after this change.

**Comment by deroneriksson** [comment]
LGTM. Thank you @gweidner

**Comment by gweidner** [comment]
Thank you @deroneriksson for reviewing!  I will merge.

**Comment by deroneriksson** [comment]
Thank you for fixing this @gweidner. I have run into the same issue.

**Pull request closed without merging**
