### PR TITLE
[SYSTEMML-1192] Delete rmvar instructions via MLContext

### PR DESCRIPTION
**Pull request by deroneriksson**
Remove all rmvar instructions so that variables are maintained in the symbol
table, which is useful in an interactive environment such as the Spark Shell.

### CODE REVIEW

**Comment by deroneriksson** [comment]
Example:
```
scala> val ml = new MLContext(sc)

Welcome to Apache SystemML!

ml: org.apache.sysml.api.mlcontext.MLContext = org.apache.sysml.api.mlcontext.MLContext@2dec57c5

scala> val script = dml("A = matrix('1 2 3 4', rows=2, cols=2); print(toString(A));")
script: org.apache.sysml.api.mlcontext.Script =
Inputs:
None

Outputs:
None

scala> ml.execute(script)
1.000 2.000
3.000 4.000

res0: org.apache.sysml.api.mlcontext.MLResults =
None
scala> script.displaySymbolTable
res1: String =
"Symbol Table:
  [1] (String) _Var3: 1.000 2.000
3.000 4.000

  [2] (String) _Var2: 1.000 2.000
3.000 4.000

  [3] (Matrix) _mVar1: MatrixObject: scratch_space//_p61451_192.168.1.103//_t0/temp1_1, [2 x 2, nnz=4, blocks (1000 x 1000)], binaryblock, dirty
"

**Comment by deroneriksson** [comment]
@mboehm7 Do you think this is OK in its current state (default on), or do you think this should by default be off (due to potential performance/memory issues), but have a MLContext flag that can be set to turn it on? Note that Script does have a clearSymbolTable() method.

**Comment by nakul02** [comment]
@deroneriksson - as we discussed offline, maybe this is useful for debugging.
Maybe we could disable `rmvar` via a flag (from the command line options) to aid in debugging, 
as opposed to disabling it by default.

**Comment by deroneriksson** [comment]
@nakul02 That sounds like a good idea. It can be quite useful for debugging but I was a bit concerned about performance and memory requirements. I'll update to by default use the existing behavior.

**Comment by deroneriksson** [comment]
Updated to by default use existing behavior (only maintain symbol table values for outputs). Added ability to turn on maintaining symbol table values.

Example:
```
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.1.0
      /_/
         
Using Scala version 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_60)
Type in expressions to have them evaluated.
Type :help for more information.

scala> import org.apache.sysml.api.mlcontext._
import org.apache.sysml.api.mlcontext._

scala> import org.apache.sysml.api.mlcontext.ScriptFactory._
import org.apache.sysml.api.mlcontext.ScriptFactory._

scala> val ml = new MLContext(sc)

Welcome to Apache SystemML!

ml: org.apache.sysml.api.mlcontext.MLContext = org.apache.sysml.api.mlcontext.MLContext@f1e1d66

scala> val script = dml("A = matrix('1 2 3 4', rows=2, cols=2); print(toString(A));")
script: org.apache.sysml.api.mlcontext.Script =
Inputs:
None

Outputs:
None

scala> ml.execute(script)
1.000 2.000
3.000 4.000

res0: org.apache.sysml.api.mlcontext.MLResults =
None

scala> script.displaySymbolTable
res1: String =
"Symbol Table:
None
"

scala> ml.setMaintainSymbolTable(true)

scala> ml.execute(script)
1.000 2.000
3.000 4.000

res3: org.apache.sysml.api.mlcontext.MLResults =
None

scala> script.displaySymbolTable
res4: String =
"Symbol Table:
  [1] (String) _Var6: 1.000 2.000
3.000 4.000

  [2] (String) _Var5: 1.000 2.000
3.000 4.000

  [3] (Matrix) _mVar4: MatrixObject: scratch_space//_p63600_192.168.1.103//_t0/temp2_2, [2 x 2, nnz=4, blocks (1000 x 1000)], binaryblock, dirty
"
```

**Comment by nakul02** [comment]
@niketanpansare - thoughts?

**Comment by niketanpansare** [comment]
Conceptually, it feels a bit odd that 'script' has 'symbol table', shouldn't it be part of MLResults or MLContext ?

**Comment by deroneriksson** [comment]
When the new MLContext API was created, the symbol table for a DML script was moved to the Script object, thus allowing multiple scripts to each have their own symbol table. The Script object is what is 'executed' by ScriptExecutor via the new MLContext and the resulting execution has an associated symbol table of values. Conceptually, I agree about MLResults, since an MLResults is associated with the results of an executed script, and MLResults is indeed passed a copy of the symbol table after execution.

This PR simply optionally allows the option of keeping symbol table values around after execution (by default it uses the old behavior). This can be useful when debugging (which I am currently doing via some UI tools).

**Comment by niketanpansare** [comment]
LGTM and also +1 for adding any debugging feature :)

**Comment by bertholdreinwald** [comment]
Thanks, Deron. I guess that this feature is useful for debugging scenarios. However, removing all rmvars is too coarse. 

What you want to accomplish here is to carry vars from 1 DML invocation to the next, which is useful. However, I think that a user needs to specify which vars to hold on to as only the user knows the larger flow in this interactive scenario. Honestly, I thought that the JMLC API has already a method to "pin" vars. Will try to find it tomorrow. Holding on too many vars will make subsequent memory estimates and optimizations challenging. 

Thoughts?

**Comment by mboehm7** [comment]
Overall, there can indeed be memory leaks and performance issues but this really depends on the used API. For MLContext, which runs with caching enabled, unnecessary variables are simply spilled out to disk; variables below 4KB are not subject to caching but it would require tens of thousands of intermediates before this becomes a problem. For JMLC, caching is disabled, and hence we cannot apply it there.

However, I agree with Berthold that removing all rmvar instructions is anyway too coarse-grained. The majority of rmvar instructions refers to intermediates of a DAG which are never bound to logical variables names and hence not accessible for a user. To create a whitelist of variables you want to keep, you can simply iterate over all DAGs and collect the names of transient_write root nodes.

**Comment by deroneriksson** [comment]
@bertholdreinwald @mboehm7 
This is meant as a debugging tool for developers, who can actually care about the intermediate variables that get created. SystemML often does lots of hidden magic, and being able to see the intermediates and their values can shed light on some of that. Anyway, if you would prefer not to have this feature in master, I can keep it in my own branch so that I can use it.

**Comment by deroneriksson** [comment]
I'm going to go ahead and merge this optional troubleshooting feature since it does not affect the existing default behavior and needs to manually be turned on for debugging purposes. If it causes issues for users, I can remove it from master.

**Pull request closed without merging**
