### PR TITLE
[SYSTEMML-777] Restricted Boltzmann Machines implementation

### PR DESCRIPTION
**Pull request by nmanchev**
DML implementation of Restricted Boltzmann Machines. 

rbm_minibatch.dml uses CD-1 mini-batch training to fit an RBM and outputs the model parameters (weights and biases)

rbm_run.dml runs a data set through the trained RBM and outputs p(h=1|v) for each observation.

### CODE REVIEW

**Comment by akchinSTC** [comment]
Can an Admin verify this patch?

**Comment by mboehm7** [comment]
thanks @nmanchev this already looks pretty good - just one minor request: could you please rename the rbm_run.dml to something like rbm-predict.dml to make clear that it's the scoring script for rbm?

**Comment by nmanchev** [comment]
@mboehm7 thanks for your feedback. Renamed as suggested.

**Comment by mboehm7** [comment]
LGTM - thanks @nmanchev

**Pull request closed without merging**
