### PR TITLE
[SYSTEMML-1076] [SYSTEMML-1077] Handle empty blocks in maxpool and maxpool_backward

### PR DESCRIPTION
**Pull request by niketanpansare**
@dusenberrymw @nakul02  Can you please test this using your lenet scripts ?

### CODE REVIEW

**Comment by nakul02** [comment]
I tried this with the example at [SYSTEMML-1077](https://issues.apache.org/jira/browse/SYSTEMML-1077)
But I run it using the CP mode and print a part of the the matrix to make sure its not optimized away.

Program:
```r
N = 2
C = 3
Hin = 10
Win = 10
f = 2
stride = 2
X = matrix(0, rows=N, cols=C*Hin*Win)
out = max_pool(X, input_shape=[N,C,Hin,Win], pool_size=[f,f], stride=[stride,stride], padding=[0,0])

print(toString(out[1:2,1:2]))
```

Works for me.

**Comment by dusenberrymw** [comment]
This fixes the issues with the two simple examples given in SYSTEMML-1076 & SYSTEMML-1077.  I'm running a modified LeNet network now to make sure there are no other regressions, and I'll report back.

**Comment by dusenberrymw** [comment]
Alright, this appears to have fixed those two specific issues.  I say we merge this, and we should also write some test cases as well that cover these two issues.  The Jenkins tests also passed for this PR: https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/817/.

**Comment by niketanpansare** [comment]
Closed by https://github.com/apache/incubator-systemml/commit/e0e60a611190cd78f13cc9af83ebde1db2e9b8a1

**Pull request closed without merging**
