### PR TITLE
[SYSTEMML-534] Add optional console output of stats to Univar-Stats.dml

### PR DESCRIPTION
**Pull request by deroneriksson**
Add optional input parameter to print stats to console (default is off).
Update INPUT/OUTPUT/INVOKE comments at top of script.

### CODE REVIEW

**Comment by deroneriksson** [comment]
Sample (optional) console output:

```
-------------------------------------------------
Feature [1]: Scale
 (01) Minimum             | 30.0
 (02) Maximum             | 83.0
 (03) Range               | 53.0
 (04) Mean                | 52.45751633986928
 (05) Variance            | 116.71458266366658
 (06) Std deviation       | 10.803452349303281
 (07) Std err of mean     | 0.6175922641866753
 (08) Coeff of variation  | 0.20594669940735139
 (09) Skewness            | 0.1450718616532357
 (10) Kurtosis            | -0.6150152487211726
 (11) Std err of skewness | 0.13934809593495995
 (12) Std err of kurtosis | 0.277810485320835
 (13) Median              | 52.0
 (14) Interquartile mean  | 52.16013071895425
-------------------------------------------------
Feature [2]: Scale
 (01) Minimum             | 58.0
 (02) Maximum             | 69.0
 (03) Range               | 11.0
...
```

**Comment by Wenpei** [comment]
@deroneriksson Should be better to add OPTIONAL column for input parameter.

**Comment by deroneriksson** [comment]
Hi @Wenpei . Thank you for reviewing. I wrapped the input parameters on line 39 to a new line for readability. The OPTIONAL column is a nice idea, but the DEFAULT column includes this information, since if a default value is present, the input parameter is optional. If we receive more feedback that this is unclear, maybe we can add an OPTIONAL column to all scripts in the future.

**Comment by shirisht** [comment]
I agree with @deroneriksson ... the fact that a parameter has default value means it is optional.

**Comment by shirisht** [comment]
LGTM

**Comment by Wenpei** [comment]
Thanks, i agree

**Pull request closed without merging**
