### PR TITLE
[SYSTEMML-1136] Remove unreferenced fields and member classes

### PR DESCRIPTION
**Pull request by deroneriksson**
Unreferenced fields and member classes should be removed from the project because they are not being used and are therefore essentially dead code.

Here is a list of unreferenced fields and member classes:

```
org.apache.sysml.lops.Lop.hasTransientParameters
org.apache.sysml.runtime.controlprogram.parfor.RemoteDPParWorkerReducer._rvarFnames
org.apache.sysml.runtime.instructions.gpu.context.JCudaObject.thisThread
org.apache.sysml.runtime.matrix.data.LibMatrixDNN.ConvolutionParameters.tmpData
org.apache.sysml.runtime.matrix.data.LibMatrixDNN.TemporaryConvolutionData.maxCommonIndexS
org.apache.sysml.runtime.matrix.data.LibMatrixDNN.TemporaryConvolutionData.maxIndexArrR
org.apache.sysml.runtime.matrix.data.LibMatrixDNN.TemporaryConvolutionData.maxIndexArrS
org.apache.sysml.runtime.matrix.data.LibMatrixDNN.TemporaryConvolutionData.minCommonIndexS
org.apache.sysml.runtime.matrix.data.LibMatrixDNN.TemporaryConvolutionData.minIndexArrR
org.apache.sysml.runtime.matrix.data.LibMatrixDNN.TemporaryConvolutionData.minIndexArrS
org.apache.sysml.runtime.matrix.data.Tagged.Comparator
org.apache.sysml.runtime.matrix.data.Tagged.TAG_SIZE
org.apache.sysml.runtime.matrix.data.TaggedMatrixIndexes.Comparator
org.apache.sysml.runtime.matrix.data.TaggedTripleIndexes.Comparator
org.apache.sysml.runtime.matrix.data.TaggedTripleIndexes.FirstTwoIndexesPartitioner
org.apache.sysml.runtime.matrix.operators.COVOperator.constant
org.apache.sysml.utils.Statistics.compileTime
org.apache.sysml.utils.Statistics.execTime
org.apache.sysml.yarn.DMLAppMasterStatusReporter.DEFAULT_REPORT_INTERVAL
org.apache.sysml.yarn.ropt.YarnClusterAnalyzer._localJT
```

All tests passed: https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/224/

### CODE REVIEW

**Comment by mboehm7** [comment]
leave RemoteDPParWorkerReducer._rvarFnames, Statistics.compileTime, Statistics.execTime, DMLAppMasterStatusReporter.DEFAULT_REPORT_INTERVAL, YarnClusterAnalyzer._localJT with TODOs to investigate

**Comment by deroneriksson** [comment]
Restored the following fields and added TODOs to investigate:
RemoteDPParWorkerReducer._rvarFnames
Statistics.compileTime
Statistics.execTime
DMLAppMasterStatusReporter.DEFAULT_REPORT_INTERVAL
YarnClusterAnalyzer._localJT

**Comment by dusenberrymw** [comment]
@niketanpansare Do you need the `TemporaryConvolutionData` class in `LibMatrixDNN` still?
@deroneriksson Can you rebase real quick?

**Comment by niketanpansare** [comment]
@dusenberrymw  `TemporaryConvolutionData` was cleanup in the commit https://github.com/apache/incubator-systemml/commit/8c069ed8e54c6941b25ccf8ede41389875e25d0b

**Pull request closed without merging**
