### PR TITLE
[SYSTEMML-145] Remove crc files from local file system

### PR DESCRIPTION
**Pull request by deroneriksson**

### CODE REVIEW

**Comment by deroneriksson** [comment]
Given DML:
```
x = matrix("1 2 3 4", rows=2, cols=2);
write(x, 'm.csv', format='csv')
```

Before PR, produces:
```
.m.csv.crc
.m.csv.mtd.crc
m.csv
m.csv.mtd
```

After PR, produces:
```
m.csv
m.csv.mtd
```

**Comment by deroneriksson** [comment]
BTW, this PR does not modify the Writer*Parallel.java files.

**Comment by gweidner** [comment]
Thanks Deron!  I just want to run test harness overnight on Windows to make sure I haven't missed anything.  Note PR builder passed: https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/569/

**Comment by gweidner** [comment]
No unit test regressions observed on Windows (RewriteFusedRandTest.testRewriteFusedRandNormal failure occurs on my Windows system before this patch and is not related to code changes in this PR).

  RewriteFusedRandTest.testRewriteFusedRandNormal:74->testRewriteFusedRand:107 Wrong result, expected: 1932 expected:<1932.0> but was:<1870.0>

Tests run: 5789, Failures: 1, Errors: 0, Skipped: 0

[INFO]
[INFO] --- maven-failsafe-plugin:2.17:verify (default) @ systemml ---
[INFO] Failsafe report directory: C:\git\incubator-systemml\target\failsafe-reports
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:18 h
[INFO] Finished at: 2016-08-19T02:56:27-07:00
[INFO] Final Memory: 74M/339M
[INFO] ------------------------------------------------------------------------

**Comment by gweidner** [comment]
I have no objections to removing the .crc files and no concerns were raised in the JIRA created Aug'2015.

**Comment by deroneriksson** [comment]
@gweidner Thank you for looking at this Glenn!

@mboehm7 Does the approach in the PR seem correct?

**Comment by deroneriksson** [comment]
@gweidner @mboehm7 @dusenberrymw @niketanpansare 
Unless there are objections, I will merge this tomorrow.

**Comment by mboehm7** [comment]
What is the motivation for removing these files after write? I would say that the crc files are perfectly expected when writing with hadoop io libs to local file system. However, I don't have a strong opinion here as the write with local file system never happens in practice except in our testsuite. But please ensure consistency between single-threaded and multi-threaded writers if this is brought in.

**Comment by deroneriksson** [comment]
I don't mind crc files in a distributed file system, but when matrices are written locally, the hidden crc files can become an annoyance. Since this is how I typically use SystemML (as a developer with little matrices rather than as a data scientist working on big data), this becomes an issue for me.

@mboehm7 What is the best way to test the multi-threaded writers (Writer*Parallel.java files)?

**Comment by deroneriksson** [comment]
Looks like writing a big matrix triggers the multi-threaded write.

**Comment by mboehm7** [comment]
yes, >128MB (one partition) but note that the parallel writers do not overwrite "writeFrameToHDFS" which makes this method a good candidate to add it once for both.

**Comment by deroneriksson** [comment]
@mboehm7 Thank you for the information.

**Comment by deroneriksson** [comment]
@mboehm7 I added some additional code to delete the .crc files for the multipart files when written to the local file system. Tested this on OSX with large and small matrices for csv, ijv, mm, and binary.

**Comment by deroneriksson** [comment]
I will merge this today if there are no objections.

**Pull request closed without merging**
