### PR TITLE
[SYSTEMML-1455] Change the term PLAIN_R2 to R2 in all algorithms

### PR DESCRIPTION
**Pull request by krishnakalyan3**
Changed PLAIN_R2 to R2 in all Algorithms and documentation.
@iyounus @nakul02

### CODE REVIEW

**Comment by akchinSTC** [comment]
Can an Admin verify this patch?

**Comment by nakul02** [comment]
Pinging @niketanpansare, @dusenberrymw, @iyounus 

@krishnakalyan3 - can you provide a brief justification for this PR?

**Comment by deroneriksson** [comment]
cc @iyounus

**Comment by iyounus** [comment]
@krishnakalyan3 There is only one place left where we should remove the word plain. On line 474 in algorithms-regression.md, change R^2_{\textrm{plain}}  to R^2.

After this change, we can merge this PR.

**Comment by krishnakalyan3** [comment]
@iyounus thank you for the review. I have made the changes.

**Comment by deroneriksson** [comment]
LGTM. Thank you @krishnakalyan3. I'll merge.

cc @iyounus

**Pull request closed without merging**
