### PR TITLE
[SYSTEMML-891] Update MLContext Matrix and Frame 'as' methods to 'to'

### PR DESCRIPTION
**Pull request by deroneriksson**
Update 'as' methods to 'to' methods to more closely follow Spark conventions.
Remove 'String' from rdd and JavaRDD access methods for conciseness.

### CODE REVIEW

**Comment by nakul02** [comment]
Pending [Jenkins](https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/203/) Job

**Comment by deroneriksson** [comment]
@dusenberrymw Would you mind trying out this update and see if it has a better feel to Spark developers?

**Comment by deroneriksson** [comment]
cc @bertholdreinwald

**Comment by dusenberrymw** [comment]
The `toDF` looks good.  I might recommend using `toRDDStringIJV` and related variants to make it clear that those methods are for getting a string representation of a row of numbers.  This way, we can add a `toRDDIJV` function that returns a proper tuple of numbers.   The string formats are old anyways, and we should probably deprecate them at some point.

Also, can you double check that the Python MLContext `toDF` function is updated to use this new Java `toDF` function?  Should be a quick change confirmed with tests.

**Comment by deroneriksson** [comment]
Thanks for the feedback @dusenberrymw. I will add the 'String' to the RDD methods to avoid confusion in the future.

**Comment by deroneriksson** [comment]
Requested changes made. I will merge.

**Pull request closed without merging**
