### PR TITLE
[DOC] Updated brew install instructions to install spark1.6.

### PR DESCRIPTION
**Pull request by nakul02**
@deroneriksson @niketanpansare @dusenberrymw

### CODE REVIEW

**Comment by deroneriksson** [comment]
LGTM. Thank you @nakul02.

**Comment by dusenberrymw** [comment]
Good call, @nakul02.  What are the executable names now?  Before, it would have installed `spark-shell`, `pyspark`, etc.  Does it have the version appended now?

**Comment by nakul02** [comment]
I think they're still called `spark-shell`, `pyspark`.
The [homebrew/versions tap](https://github.com/Homebrew/homebrew-versions/blob/master/apache-spark16.rb) recipe just gets Spark 1.6.2 instead of the [default homebrew-core](https://github.com/Homebrew/homebrew-core/blob/master/Formula/apache-spark.rb) recipe

**Comment by niketanpansare** [comment]
Thanks Nakul for looking into this. We should also consider adding Window's instruction in subsequent PR :)

**Comment by nakul02** [comment]
@niketanpansare - Could you please merge this in?

**Comment by dusenberrymw** [comment]
@MadisonJMyers Can you make this change in your blog post?

**Comment by nakul02** [comment]
@deroneriksson or @dusenberrymw - Could you please merge this in, @niketanpansare has a permission issue.

**Comment by MadisonJMyers** [comment]
@dusenberrymw yes! will do.

**Pull request closed without merging**
