### PR TITLE
[WIP] [SYSTEMML-594] Tutorial to run SystemML on Bluemix/Datascientistworkbench using Zeppelin/Jupyter

### PR DESCRIPTION
**Pull request by niketanpansare**
Please DONOT push this PR until the discussion on dev mailing list is complete.

### CODE REVIEW

**Comment by niketanpansare** [comment]
@dusenberrymw @mboehm7 @frreiss @bertholdreinwald @deroneriksson  Should we add a tutorial to import SystemML's notebooks onto bluemix or datascientistworkbench ? If no, then we should close the PR. If yes, then should we also specify using notebook on bluemix/datascientistworkbench in our quickstart guide ?

Note: the notebook approach doesnot require anything dependency (mvn/git/java/spark/..) and allows users to try out SystemML with just few clicks. My personal opinion: we should stage quickstart guide such that first quickstart tutorial should take no more than 15 min (which includes time to read the guide itself) to play with SystemML. The next one can be more involved.

**Comment by bertholdreinwald** [comment]
I think that it is a good idea. It is more of a documentation of the command to upload / pull in the jar file. Am I right?

Will a mechanism be added to include the DML scripts as well including datagen?

**Comment by deroneriksson** [comment]
Hi @niketanpansare . Thank you for creating the Notebook examples. I think Notebooks will be the quickest way for data scientists to try out SystemML.

Couple comments.
1) On import-nb-bluemix.md, could you add 'git clone' before the https://github.com/apache/... url?
2) On import-nb-datascientistworkbench.md, could you use the clone URL from import-nb-bluemix.md (https://github.com/apache/incubator-systemml.git) rather than https://github.com/niketanpansare/systemml_tutorial.git?

We should also add a Databricks notebook example. I created SYSTEMML-610 for this.

Also, at some point in the near future, I think we will need to restructure the Notebook documentation since it needs to be brought together and made more prominent. The current Notebook documentation is a little buried (in the Spark MLContext programming guide), as I believe we discussed a couple weeks ago.

Aside from the minor URL updates, LGTM. Thank you!

**Comment by dusenberrymw** [comment]
I think adding documentation and notebook examples for Bluemix/DSW is good, but I'd only want to put it at the very end of a notebook guide, and not on the main README or quick start guides.  In my opinion, the notebook guide, README, and quick start guides should start and mainly stick with generic Jupyter and Zeppelin.

**Comment by bertholdreinwald** [comment]
I agree that the Bluemix/DSW docu should stay with the Notebooks. 

Today the notebooks docu is unfortunately "hidden" with the MLContext documentation, and people coming from top level looking at the documentation will not find it. I think that it should be separated.

I think that a Notebook entry should be somewhere at top level.

**Comment by deroneriksson** [comment]
Agreed @bertholdreinwald . I just created https://issues.apache.org/jira/browse/SYSTEMML-699 to make notebooks much more prominent.

**Pull request closed without merging**
