### PR TITLE
[SYSTEMML-1198] Ensure jar included in Python release artifact

### PR DESCRIPTION
**Pull request by gweidner**
Added condition in pre_setup.py to match different jar name for release build vs snapshot build.

### CODE REVIEW

**Comment by gweidner** [comment]
A distribution build was tested two ways:
1) Normal development/test build where jar name has -SNAPSHOT.  Verified python artifact contained -SNAPSHOT jar.
2) Simulated release build, i.e., removed SNAPSHOT in pom version name.  Verified python artifact contained release jar (i.e., jar file without snapshot in name.

**Comment by gweidner** [comment]
@dusenberrymw @niketanpansare

**Comment by gweidner** [comment]
Here's link to RC1 artifact which had the issue found during validation testing:
https://dist.apache.org/repos/dist/dev/incubator/systemml/0.12.0-incubating-rc1/systemml-0.12.0-incubating-python.tgz

**Comment by gweidner** [comment]
It looks like classloader.py might also need similar change:
Line 58:             if fnmatch.fnmatch(file, 'systemml-*-incubating-SNAPSHOT.jar'):

**Comment by niketanpansare** [comment]
Thanks @gweidner :+1:

**Comment by gweidner** [comment]
Thank you @dusenberrymw and @niketanpansare for reviewing.  I'm attaching screen captures from Python Notebook where I've uninstalled/re-installed the previous/updated artifact and restarted kernel.

notebook_matrix

notebook_logistic

**Comment by gweidner** [comment]
For reference in case I've mis-interpreted anything, here are examples of error messages observed before making both changes:

notebook_directory_error

notebook_loader_error

**Comment by bertholdreinwald** [comment]
Hah. I noticed that too by analyzing the different artifacts on apache site and maven site. Sent out an email to dev list prior to reading that thread.

**Pull request closed without merging**
