### PR TITLE
change quotation mark from utf-8 to ascii

### PR DESCRIPTION
**Pull request by Wenpei**
There are so many uft-8 quotation mark like
 print(“Hello World”);
This may cause exception when you just copy and paste those sentence.

I change all of it to ascii quotation mark
print("Hello World");

PS: github has some issue to show this quotation " “ " in web browser. So for file compare, it's should not add quota, but replace original utf-8 quota.

### CODE REVIEW

**Comment by Wenpei** [comment]
@shirisht

**Comment by deroneriksson** [comment]
Hello @Wenpei ! You are very right, the curly quotation marks can cause problems when copy/pasted. Thank you for making those updates. Would you also like to make those updates to the dml_language_reference.md file? The dml_language_reference.md file (rendered at http://apache.github.io/incubator-systemml/dml-language-reference.html) is the new online version of the Language Reference and it contains the most recent updates. Thank you!

**Comment by shirisht** [comment]
Hi @Wenpei, Thanks for the PR. The html guide however is old and it is not actively maintained. 
You can make relevant changes to .md files, as Deron suggested. Further, as part of this PR, can you delete .html file altogether? 

Thanks!

**Comment by Wenpei** [comment]
sure, I will do it.
@deroneriksson , @shirisht

**Comment by Wenpei** [comment]
Hi @deroneriksson  @shirisht 

Please review this change.
I try to create a online version to let you review, but failed. Just get something like this (http://wenpei.github.io/incubator-systemml/). 

Wenpei.

**Comment by shirisht** [comment]
@deroneriksson Since you are the expert in md files, could you please review these changes from @Wenpei ? 

Thank you.

**Comment by deroneriksson** [comment]
Thank you for working on this @Wenpei. Your updates look good. However I'm having a little bit of a difficulty. The second commit in the PR contains several updated files but the dml-language-reference.md was not up-to-date before the updates. I would cherrypick the second commit except for the needed dml-language-reference.md which is in the third commit which has 59 files that have already been previously committed. I'm having a little problem doing a diff comparison between my local master and the PR version of dml-language-reference.md (git diff pr-18^..master -- docs/dml-language-reference.md) (Possibly because of the multiple parents of commit 3?).

I hate to ask, but would it be possible to do a new pull request with your updates ((1) delete language reference html file and (2) update other 6 files based off the latest master)?

Also, I noticed you are working on your master branch. Perhaps creating another branch to work on (one branch per pull request) would be a little bit safer and easier than working directly on your master branch? That way you can create a branch based off of the latest code from master, commit your changes to the branch, push the branch to your GitHub, and file a PR for the changes on the branch without affecting your master branch at all. A benefit of this approach would be that you can always pull to your local master from GitHub SystemML and have the latest official code on your master branch. You can then make a branch off of master and commit code, and your commits don't affect your master branch, which is always clean.

@lresende Luciano, our GitHub/git expert, do you have anything to add?

**Comment by Wenpei** [comment]
Great share, @deroneriksson  
I will close this PR and open a new one follow your instruction.

**Pull request closed without merging**
