### PR TITLE
[SYSTEMML-1102] Argument to print top n heavy hitters

### PR DESCRIPTION
**Pull request by nakul02**
Added an argument for "-stats" option to specify the top n heavy hitters.
@deroneriksson - is this useful in general?
@niketanpansare, @bertholdreinwald - this will help with the gpu performance investigation.

### CODE REVIEW

**Comment by nakul02** [comment]
An example of this - 

image

**Comment by deroneriksson** [comment]
LGTM. Great idea @nakul02!

We might also want to eventually add something like a setStatisticsCount() to the new MLContext API.

**Comment by nakul02** [comment]
Thanks @asurve & @deroneriksson !

**Comment by nakul02** [comment]
Thanks @deroneriksson

**Pull request closed without merging**
