### PR TITLE
Update Quick Start and handle release links

### PR DESCRIPTION
**Pull request by deroneriksson**
Remove or hide links to releases until available.
Quick Start updates, such as fix build command,
fix scripts paths, miscellaneous text updates,
and remove trailing whitespace.

### CODE REVIEW

**Comment by deroneriksson** [comment]
Quick Start Guide updates can be seen [here](http://deroneriksson.github.io/incubator-systemml/quick-start-guide.html).
Hadoop Batch Mode updates can be seen [here](http://deroneriksson.github.io/incubator-systemml/hadoop-batch-mode.html).

**Comment by dusenberrymw** [comment]
This looks good to me for now, although we really should replace the `runStandaloneSystemML` scripts with the new `bin/systemml` script soon.  That will require updating the distribution scripts.

**Comment by deroneriksson** [comment]
@dusenberrymw
I agree about the runStandaloneSystemML vs. bin/systemml being an issue. Let's bring up the issue on the dev mailing list. I think the systemml/systemml.bat scripts might also need some minor updating/testing. Right now `systemml` is using `SYSTEM_ML_JAR=\"${BUILD_DIR}/classes\"` so you need to do a 'mvn package' for it to work. However, there is also a `#SYSTEM_ML_JAR=$( find $PROJECT_ROOT_DIR/target/system-ml-*-SNAPSHOT.jar )` line commented out, so it looks like it's ready to use a jar too. Maybe it can be set up to do both?

**Comment by dusenberrymw** [comment]
Yeah we should probably just switch it to always use a JAR.  That way it is ready to go for both custom-built scenarios, and official binary releases.

**Pull request closed without merging**
