### PR TITLE
[SYSTEMML-872] Add new SystemML.py to various artifacts

### PR DESCRIPTION
**Pull request by deroneriksson**
Adds SystemML.py to the root of all artifacts where it makes sense.

### CODE REVIEW

**Comment by niketanpansare** [comment]
@deroneriksson Since SystemML.py is likely going to be replace by a package structure once https://github.com/apache/incubator-systemml/pull/197 is merged in, can you please hold off this PR ? Once the PR 197 is merged, we will have a seperate Python package artifact (as a tar file).

**Comment by deroneriksson** [comment]
@niketanpansare @dusenberrymw 
There is going to be another artifact added to the project devoted to Python? Shouldn't this be packaged with the regular jar and standalone tar.gz/zip?

**Comment by deroneriksson** [comment]
@niketanpansare @dusenberrymw 
BTW I am fine with whatever approach you believe to be the best approach for Python users. If you think this PR should be closed w/o merging, that is fine. :-)

**Comment by niketanpansare** [comment]
The shell script in the python package 'uploadToPyPI.sh' will create a tar.gz in dist/ directory. We can add that artifact into our release. Anyone can use command 'pip install ..tar.gz' and install SystemML.

**Comment by deroneriksson** [comment]
It's probably a good idea to keep @lresende aware of the status of this to be sure that the release will follow Apache requirements.

**Comment by niketanpansare** [comment]
I have created a JIRA: https://issues.apache.org/jira/browse/SYSTEMML-883

@lresende or @deroneriksson Do either one of you want to take it over ?

**Comment by deroneriksson** [comment]
@niketanpansare I'm probably not a good choice for most Python tasks due to my lack of experience with it. :-)
Should I go ahead and close this PR?

**Comment by niketanpansare** [comment]
No worries :) ...  I think we should not release the old SystemML.py (as it is deprecated) and only release the new Python package. Let's go ahead and close this PR.

@lresende commented on the JIRA that he will take a pass at this. If necessary, I too can help with it.

**Comment by deroneriksson** [comment]
I will close this PR and the accompanying JIRA.

**Pull request closed without merging**
