### PR TITLE
Pr 61 fix

### PR DESCRIPTION
**Pull request by dusenberrymw**
@nakul02, @deroneriksson 

I believe this fixes the issue with PR #61 with regards to both keeping the history of the `CustomErrorListener` and allowing all 3 commits to compile.  All of the main work has been squashed into the first commit, and the next two commits only involve the refactoring from `CustomErrorListener` as an inner class of `SyntacticErrorListener` to a full outer class.  Note, that we will still need to commit all 3 commits to the repo to maintain the history.

Please have a look and see if everything checks out.

### CODE REVIEW

**Comment by nakul02** [comment]
Thanks @dusenberrymw, submitted Jenkins [build](https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/100/)

**Comment by dusenberrymw** [comment]
There was an issue with Jenkins on the last build.  Started [build 101](https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/101/).

**Comment by nakul02** [comment]
Thanks @dusenberrymw

**Comment by deroneriksson** [comment]
Verified all tests pass. See https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/102/

**Pull request closed without merging**
