### PR TITLE
[SYSTEMML-148] refactored .parser.{antlr4,python} to .parser.{dml,pydml}

### PR DESCRIPTION
**Pull request by nakul02**

### CODE REVIEW

**Comment by deroneriksson** [comment]
Tests started [here](https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/58/).

**Comment by deroneriksson** [comment]
Tests started [here](https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/59/) with additional files.

**Comment by mboehm7** [comment]
please make sure not to check in generated files.

**Comment by deroneriksson** [comment]
@mboehm7 Good catch.

@nakul02 You should now have access [here](https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/) to have Jenkins run test suite. Let me know if you have any issues.

**Comment by nakul02** [comment]
Thanks @mboehm7. I undid the additions of the generated files and have run [Jenkins](https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/60/) again.

**Comment by deroneriksson** [comment]
@nakul02 Also, should update pom.xml. See apache-rat-plugin for <exclude> entries relating to the generated antlr files.

**Comment by deroneriksson** [comment]
@nakul02 Also, I see in DML.g4 a reference to old package name on line 25 (the commented line).

**Comment by deroneriksson** [comment]
@nakul02 Thank you for updating pom. I checked and looks like the header section of the .g4 files is injected into the top of the generated .java files, so the commented lines end up in the generated .java files as comments. Thank you for updating that too.

**Comment by nakul02** [comment]
Running [Jenkins](https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/61/) on this build.

**Comment by deroneriksson** [comment]
@nakul02 Just found one other thing when examining the PR locally. The .gitignore file in the project needs to be updated for the paths to the 8 generated *.java files.

**Comment by deroneriksson** [comment]
Great. Looks good to me.

**Comment by dusenberrymw** [comment]
Looks like build 61 aborted early.  I've restarted it as [build 62](https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/62/).

Pending the final results, this **LGTM**.

Thanks, @nakul02!

**Comment by nakul02** [comment]
Thanks @dusenberrymw for starting the build!

**Comment by dusenberrymw** [comment]
We've been having issues not related to this... restarting as [build 65](https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/65/).

**Comment by dusenberrymw** [comment]
Restarted again as [build 66](https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/66/).  Also, rebased it on top of the master branch and started [build 68](https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/68/).

**Comment by nakul02** [comment]
Thanks @dusenberrymw!

**Comment by dusenberrymw** [comment]
Test build 66 was successful.

**Comment by dusenberrymw** [comment]
Merged.  Thanks @nakul02!

**Pull request closed without merging**
