### PR TITLE
[SYSTEMML-1157] Project build info via MLContext API

### PR DESCRIPTION
**Pull request by deroneriksson**
Add values to main jar manifest at build time and allow these
values to be read via the MLContext API. These values include
build time and project version number.

### CODE REVIEW

**Comment by deroneriksson** [comment]
Example:

```
scala> val ml = new MLContext(sc)

Welcome to Apache SystemML!

ml: org.apache.sysml.api.mlcontext.MLContext = org.apache.sysml.api.mlcontext.MLContext@c9dcfcd

scala> ml.info
res0: org.apache.sysml.api.mlcontext.ProjectInfo = 
Archiver-Version: Plexus Archiver
Artifact-Id: systemml
Build-Jdk: 1.8.0_60
Build-Time: 2016-12-16 22:38:19 UTC
Built-By: deroneriksson
Created-By: Apache Maven 3.3.9
Group-Id: org.apache.systemml
Main-Class: org.apache.sysml.api.DMLScript
Manifest-Version: 1.0
Version: 0.12.0-incubating-SNAPSHOT


scala> ml.version
res1: String = 0.12.0-incubating-SNAPSHOT

scala> ml.buildTime
res2: String = 2016-12-16 22:38:19 UTC

scala> ml.info.property("Build-Time")
res3: String = 2016-12-16 22:38:19 UTC

scala> ml.info.properties
res4: java.util.SortedMap[String,String] = {Archiver-Version=Plexus Archiver, Artifact-Id=systemml, Build-Jdk=1.8.0_60, Build-Time=2016-12-16 22:38:19 UTC, Built-By=deroneriksson, Created-By=Apache Maven 3.3.9, Group-Id=org.apache.systemml, Main-Class=org.apache.sysml.api.DMLScript, Manifest-Version=1.0, Version=0.12.0-incubating-SNAPSHOT}

scala> 
```

**Comment by deroneriksson** [comment]
cc @bertholdreinwald

**Comment by bertholdreinwald** [comment]
Awesome! Will that also work in Python?

**Comment by deroneriksson** [comment]
I made changes to the Java/Scala MLContext but didn't touch the Python API since I am totally new to Python. I can take a look at it though.

**Comment by bertholdreinwald** [comment]
that would be great! 

It is important to maintain consistency in our APIs across the different languages.

**Comment by deroneriksson** [comment]
Added ml.version() and ml.buildTime() to Python MLContext API.
```
$ mvn clean package -P distribution
$ pip3 install -e . (from src/main/python directory)
$ PYSPARK_PYTHON=python3 pyspark --master local[*] --driver-class-path target/SystemML.jar


Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 1.6.1
      /_/

Using Python version 3.5.2 (default, Jul 28 2016 21:28:07)
SparkContext available as sc, HiveContext available as sqlContext.
>>> from systemml import MLContext, dml
>>> ml = MLContext(sc)

Welcome to Apache SystemML!

>>> ml.version()
'0.12.0-incubating-SNAPSHOT'
>>> ml.buildTime()
'2017-01-05 22:36:07 UTC'
```

**Comment by deroneriksson** [comment]
Also added ml.info() to Python MLContext API.
```
>>> ml.info()
'Archiver-Version: Plexus Archiver\nArtifact-Id: systemml\nBuild-Jdk: 1.8.0_60\nBuild-Time: 2017-01-05 22:36:07 UTC\nBuilt-By: deroneriksson\nCreated-By: Apache Maven 3.3.9\nGroup-Id: org.apache.systemml\nMain-Class: org.apache.sysml.api.DMLScript\nManifest-Version: 1.0\nVersion: 0.12.0-incubating-SNAPSHOT\n'
>>> print(ml.info())
Archiver-Version: Plexus Archiver
Artifact-Id: systemml
Build-Jdk: 1.8.0_60
Build-Time: 2017-01-05 22:36:07 UTC
Built-By: deroneriksson
Created-By: Apache Maven 3.3.9
Group-Id: org.apache.systemml
Main-Class: org.apache.sysml.api.DMLScript
Manifest-Version: 1.0
Version: 0.12.0-incubating-SNAPSHOT
```

**Comment by nakul02** [comment]
LGTM 👍

**Comment by deroneriksson** [comment]
@nakul02 Thank you for reviewing! I'll merge.

**Pull request closed without merging**
