### PR TITLE
[SYSTEMML-971] Remove antlr tool jar from standalone tar.gz and zip

### PR DESCRIPTION
**Pull request by deroneriksson**

### CODE REVIEW

**Comment by deroneriksson** [comment]
This is the same issue addressed by https://github.com/apache/incubator-systemml/pull/261 but for the standalone tar.gz and zip artifacts.

@gweidner Please review.

**Comment by deroneriksson** [comment]
Here are a couple basic checks I did (univar stats and hello world):
```
wget -P data/ http://archive.ics.uci.edu/ml/machine-learning-databases/haberman/haberman.data
echo '{"rows": 306, "cols": 4, "format": "csv"}' > data/haberman.data.mtd
echo '1,1,1,2' > data/types.csv
echo '{"rows": 1, "cols": 4, "format": "csv"}' > data/types.csv.mtd
cd target
tar -xvzf systemml-0.12.0-incubating-SNAPSHOT-standalone.tar.gz
cd systemml-0.12.0-incubating-SNAPSHOT-standalone
./runStandaloneSystemML.sh ../../scripts/algorithms/Univar-Stats.dml -nvargs X=../../data/haberman.data TYPES=../../data/types.csv STATS=../../data/univarOut.mtx CONSOLE_OUTPUT=TRUE
echo "print('hello world');" > hello.dml
./runStandaloneSystemML.sh hello.dml
```

**Comment by gweidner** [comment]
Thanks @deroneriksson - Nice cleanup of the standalone archive!
LGTM

**Comment by deroneriksson** [comment]
I will merge. Thank you for reviewing @gweidner!

**Pull request closed without merging**
