### PR TITLE
rangeReIndex spits out a better error message if a scalar is indexed.

### PR DESCRIPTION
**Pull request by nakul02**
This was discovered when I accidentally indexed a scalar and the error thrown said that a frame cannot be indexed.

@asurve @niketanpansare

### CODE REVIEW

**Comment by dusenberrymw** [comment]
LGTM.

**Comment by mboehm7** [comment]
I would recommend to close this PR - for right indexing (as modified here) the input cannot be a scalar. If indexing on a scalar comes indeed down to the runtime, we need to change the validation in DMLTranslator instead. Furthermore, any related change should be done consistently for left and right indexing (not just right indexing).

**Comment by nakul02** [comment]
@mboehm7 -
When this script is run against master :
```r
B = "hello"
C = B[1,1]
print(C)
```

The following error is printed:
Caused by: org.apache.sysml.runtime.DMLRuntimeException: Variable 'hello' does not exist in the symbol table.

```
16/09/12 11:15:35 INFO api.DMLScript: END DML run 09/12/2016 11:15:35
16/09/12 11:15:35 ERROR api.DMLScript: Failed to execute DML script.
org.apache.sysml.runtime.DMLRuntimeException: org.apache.sysml.runtime.DMLRuntimeException: ERROR: Runtime error in program block generated from statement block between lines 1 and 3 -- Error evaluating instruction: CP°rangeReIndex°hello·SCALAR·STRING·true°1·SCALAR·INT·true°1·SCALAR·INT·true°1·SCALAR·INT·true°1·SCALAR·INT·true°_Var1·SCALAR·STRING
       	at org.apache.sysml.runtime.controlprogram.Program.execute(Program.java:152)
       	at org.apache.sysml.api.DMLScript.execute(DMLScript.java:698)
       	at org.apache.sysml.api.DMLScript.executeScript(DMLScript.java:364)
       	at org.apache.sysml.api.DMLScript.main(DMLScript.java:199)
Caused by: org.apache.sysml.runtime.DMLRuntimeException: ERROR: Runtime error in program block generated from statement block between lines 1 and 3 -- Error evaluating instruction: CP°rangeReIndex°hello·SCALAR·STRING·true°1·SCALAR·INT·true°1·SCALAR·INT·true°1·SCALAR·INT·true°1·SCALAR·INT·true°_Var1·SCALAR·STRING
       	at org.apache.sysml.runtime.controlprogram.ProgramBlock.executeSingleInstruction(ProgramBlock.java:335)
       	at org.apache.sysml.runtime.controlprogram.ProgramBlock.executeInstructions(ProgramBlock.java:224)
       	at org.apache.sysml.runtime.controlprogram.ProgramBlock.execute(ProgramBlock.java:168)
       	at org.apache.sysml.runtime.controlprogram.Program.execute(Program.java:145)
       	... 3 more
Caused by: org.apache.sysml.runtime.DMLRuntimeException: Variable 'hello' does not exist in the symbol table.
       	at org.apache.sysml.runtime.controlprogram.context.ExecutionContext.getFrameObject(ExecutionContext.java:184)
       	at org.apache.sysml.runtime.controlprogram.context.ExecutionContext.getFrameInput(ExecutionContext.java:351)
       	at org.apache.sysml.runtime.instructions.cp.FrameIndexingCPInstruction.processInstruction(FrameIndexingCPInstruction.java:51)
       	at org.apache.sysml.runtime.controlprogram.ProgramBlock.executeSingleInstruction(ProgramBlock.java:305)
       	... 6 more
Exception in thread "main" org.apache.sysml.api.DMLException: org.apache.sysml.runtime.DMLRuntimeException: org.apache.sysml.runtime.DMLRuntimeException: ERROR: Runtime error in program block generated from statement block between lines 1 and 3 -- Error evaluating instruction: CP°rangeReIndex°hello·SCALAR·STRING·true°1·SCALAR·INT·true°1·SCALAR·INT·true°1·SCALAR·INT·true°1·SCALAR·INT·true°_Var1·SCALAR·STRING
       	at org.apache.sysml.api.DMLScript.executeScript(DMLScript.java:378)
       	at org.apache.sysml.api.DMLScript.main(DMLScript.java:199)
Caused by: org.apache.sysml.runtime.DMLRuntimeException: org.apache.sysml.runtime.DMLRuntimeException: ERROR: Runtime error in program block generated from statement block between lines 1 and 3 -- Error evaluating instruction: CP°rangeReIndex°hello·SCALAR·STRING·true°1·SCALAR·INT·true°1·SCALAR·INT·true°1·SCALAR·INT·true°1·SCALAR·INT·true°_Var1·SCALAR·STRING
       	at org.apache.sysml.runtime.controlprogram.Program.execute(Program.java:152)
       	at org.apache.sysml.api.DMLScript.execute(DMLScript.java:698)
       	at org.apache.sysml.api.DMLScript.executeScript(DMLScript.java:364)
       	... 1 more
Caused by: org.apache.sysml.runtime.DMLRuntimeException: ERROR: Runtime error in program block generated from statement block between lines 1 and 3 -- Error evaluating instruction: CP°rangeReIndex°hello·SCALAR·STRING·true°1·SCALAR·INT·true°1·SCALAR·INT·true°1·SCALAR·INT·true°1·SCALAR·INT·true°_Var1·SCALAR·STRING
       	at org.apache.sysml.runtime.controlprogram.ProgramBlock.executeSingleInstruction(ProgramBlock.java:335)
       	at org.apache.sysml.runtime.controlprogram.ProgramBlock.executeInstructions(ProgramBlock.java:224)
       	at org.apache.sysml.runtime.controlprogram.ProgramBlock.execute(ProgramBlock.java:168)
       	at org.apache.sysml.runtime.controlprogram.Program.execute(Program.java:145)
       	... 3 more
Caused by: org.apache.sysml.runtime.DMLRuntimeException: Variable 'hello' does not exist in the symbol table.
       	at org.apache.sysml.runtime.controlprogram.context.ExecutionContext.getFrameObject(ExecutionContext.java:184)
       	at org.apache.sysml.runtime.controlprogram.context.ExecutionContext.getFrameInput(ExecutionContext.java:351)
       	at org.apache.sysml.runtime.instructions.cp.FrameIndexingCPInstruction.processInstruction(FrameIndexingCPInstruction.java:51)
       	at org.apache.sysml.runtime.controlprogram.ProgramBlock.executeSingleInstruction(ProgramBlock.java:305)
       	... 6 more
Failed to run SystemML. Exit code: 1
```
The error being printed out is :  **Variable 'hello' does not exist in the symbol table.** 
Whereas the core issue is of trying to index a scalar.


Here is another more interesting example:
```r
A = matrix(1, rows=1, cols=10)
B = sum(A %*% t(A))
C = B[1,1]
print(C)
```

And the error message:
```
16/09/12 11:23:30 ERROR api.DMLScript: Failed to execute DML script.
org.apache.sysml.runtime.DMLRuntimeException: org.apache.sysml.runtime.DMLRuntimeException: ERROR: Runtime error in program block generated from statement block between lines 1 and 4 -- Error evaluating instruction: CP°rangeReIndex°_Var3·SCALAR·DOUBLE·false°1·SCALAR·INT·true°1·SCALAR·INT·true°1·SCALAR·INT·true°1·SCALAR·INT·true°_Var4·SCALAR·DOUBLE
       	at org.apache.sysml.runtime.controlprogram.Program.execute(Program.java:152)
       	at org.apache.sysml.api.DMLScript.execute(DMLScript.java:698)
       	at org.apache.sysml.api.DMLScript.executeScript(DMLScript.java:364)
       	at org.apache.sysml.api.DMLScript.main(DMLScript.java:199)
Caused by: org.apache.sysml.runtime.DMLRuntimeException: ERROR: Runtime error in program block generated from statement block between lines 1 and 4 -- Error evaluating instruction: CP°rangeReIndex°_Var3·SCALAR·DOUBLE·false°1·SCALAR·INT·true°1·SCALAR·INT·true°1·SCALAR·INT·true°1·SCALAR·INT·true°_Var4·SCALAR·DOUBLE
       	at org.apache.sysml.runtime.controlprogram.ProgramBlock.executeSingleInstruction(ProgramBlock.java:335)
       	at org.apache.sysml.runtime.controlprogram.ProgramBlock.executeInstructions(ProgramBlock.java:224)
       	at org.apache.sysml.runtime.controlprogram.ProgramBlock.execute(ProgramBlock.java:168)
       	at org.apache.sysml.runtime.controlprogram.Program.execute(Program.java:145)
       	... 3 more
Caused by: org.apache.sysml.runtime.DMLRuntimeException: Variable '_Var3' is not a frame.
       	at org.apache.sysml.runtime.controlprogram.context.ExecutionContext.getFrameObject(ExecutionContext.java:186)
       	at org.apache.sysml.runtime.controlprogram.context.ExecutionContext.getFrameInput(ExecutionContext.java:351)
       	at org.apache.sysml.runtime.instructions.cp.FrameIndexingCPInstruction.processInstruction(FrameIndexingCPInstruction.java:51)
       	at org.apache.sysml.runtime.controlprogram.ProgramBlock.executeSingleInstruction(ProgramBlock.java:305)
       	... 6 more
Exception in thread "main" org.apache.sysml.api.DMLException: org.apache.sysml.runtime.DMLRuntimeException: org.apache.sysml.runtime.DMLRuntimeException: ERROR: Runtime error in program block generated from statement block between lines 1 and 4 -- Error evaluating instruction: CP°rangeReIndex°_Var3·SCALAR·DOUBLE·false°1·SCALAR·INT·true°1·SCALAR·INT·true°1·SCALAR·INT·true°1·SCALAR·INT·true°_Var4·SCALAR·DOUBLE
       	at org.apache.sysml.api.DMLScript.executeScript(DMLScript.java:378)
       	at org.apache.sysml.api.DMLScript.main(DMLScript.java:199)
Caused by: org.apache.sysml.runtime.DMLRuntimeException: org.apache.sysml.runtime.DMLRuntimeException: ERROR: Runtime error in program block generated from statement block between lines 1 and 4 -- Error evaluating instruction: CP°rangeReIndex°_Var3·SCALAR·DOUBLE·false°1·SCALAR·INT·true°1·SCALAR·INT·true°1·SCALAR·INT·true°1·SCALAR·INT·true°_Var4·SCALAR·DOUBLE
       	at org.apache.sysml.runtime.controlprogram.Program.execute(Program.java:152)
       	at org.apache.sysml.api.DMLScript.execute(DMLScript.java:698)
       	at org.apache.sysml.api.DMLScript.executeScript(DMLScript.java:364)
       	... 1 more
Caused by: org.apache.sysml.runtime.DMLRuntimeException: ERROR: Runtime error in program block generated from statement block between lines 1 and 4 -- Error evaluating instruction: CP°rangeReIndex°_Var3·SCALAR·DOUBLE·false°1·SCALAR·INT·true°1·SCALAR·INT·true°1·SCALAR·INT·true°1·SCALAR·INT·true°_Var4·SCALAR·DOUBLE
       	at org.apache.sysml.runtime.controlprogram.ProgramBlock.executeSingleInstruction(ProgramBlock.java:335)
       	at org.apache.sysml.runtime.controlprogram.ProgramBlock.executeInstructions(ProgramBlock.java:224)
       	at org.apache.sysml.runtime.controlprogram.ProgramBlock.execute(ProgramBlock.java:168)
       	at org.apache.sysml.runtime.controlprogram.Program.execute(Program.java:145)
       	... 3 more
Caused by: org.apache.sysml.runtime.DMLRuntimeException: Variable '_Var3' is not a frame.
       	at org.apache.sysml.runtime.controlprogram.context.ExecutionContext.getFrameObject(ExecutionContext.java:186)
       	at org.apache.sysml.runtime.controlprogram.context.ExecutionContext.getFrameInput(ExecutionContext.java:351)
       	at org.apache.sysml.runtime.instructions.cp.FrameIndexingCPInstruction.processInstruction(FrameIndexingCPInstruction.java:51)
       	at org.apache.sysml.runtime.controlprogram.ProgramBlock.executeSingleInstruction(ProgramBlock.java:305)
       	... 6 more
Failed to run SystemML. Exit code: 1
```

The error message is : **Variable '_Var3' is not a frame.**

In both cases, `DMLTranslator` is not doing the appropriate error checking.
I think `DMLTranslator` should have that check, but having a redundant check in the runtime is not a bad idea. 
While the current implementation detects the error, a user of DML/PyDML would not be able to comprehend the error messages. 
I faced this error when helping @asurve build his SystemML demo for his meetup.

**Comment by asurve** [comment]
LGTM
Agree with @mboehm7  comments regarding validation at DMLTranslator level. This change won't hurt and will be helpful until DMLTranslator changes. 
@nakul02 Can you open Jira for scalar indexing validation through DMLTranslator?

**Comment by nakul02** [comment]
Thanks @asurve, here is the [JIRA](https://issues.apache.org/jira/browse/SYSTEMML-920)

**Pull request closed without merging**
