### PR TITLE
[SYSTEMML-1084] Change .tar.gz artifact extensions to .tgz

### PR DESCRIPTION
**Pull request by deroneriksson**
Use Apache parent pom assembly plugin version.
Update artifact .tar.gz extensions to .tgz
Change .tar.gz references to .tgz in release-process document.

### CODE REVIEW

**Comment by deroneriksson** [comment]
@lresende 
There is a possibility that this may help with the 'source-release.zip' issue since it switches to using the maven-assembly-plugin version specified in the Apache parent pom (version 2.6 allows .tgz extension while version 2.4 apparently doesn't). BTW, the .tgz extension is also currently used by Apache Spark artifacts (see http://spark.apache.org/downloads.html).

**Comment by gweidner** [comment]
Thank you Deron!  I built locally with -Pdistribution and things look good.  I also searched .md files in docs folder for any other references to tar.gz and found a few hits:
Search "tar.gz" (10 hits in 3 files)
  C:\git\incubator-systemml\docs\beginners-guide-to-dml-and-pydml.md (1 hit)
	Line 53: One way to begin working with SystemML is to [download a standalone tar.gz or zip distribution of SystemML](http://systemml.apache.org/download.html)
  C:\git\incubator-systemml\docs\engine-dev-guide.md (1 hit)
	Line 36: To build the SystemML distributions (`.tar.gz`, `.zip`, etc.), run:
  C:\git\incubator-systemml\docs\hadoop-batch-mode.md (8 hits)
	Line 99: 	[hadoop@host1 ~]$ wget http://mirror.sdunix.com/apache/hadoop/common/hadoop-2.6.2/hadoop-2.6.2.tar.gz
	Line 100: 	[hadoop@host1 ~]$ tar -xvzf hadoop-2.6.2.tar.gz
	Line 138: 	[hadoop@host1 ~]$ tar -xvzf systemml-{{site.SYSTEMML_VERSION}}.tar.gz
	Line 146: 	[hadoop@host1 incubator-systemml]$ tar -xvzf target/systemml-{{site.SYSTEMML_VERSION}}.tar.gz -C ..
	Line 185: 	-rw-rw-r-- 1 hadoop hadoop 195515434 Oct 30 14:04 hadoop-2.6.2.tar.gz
	Line 192: 	-rw-rw-r-- 1 hadoop hadoop   6683281 Oct 27 21:13 systemml-{{site.SYSTEMML_VERSION}}.tar.gz
	Line 350: 	genLinearRegressionData.dml  hadoop-2.6.2  hadoop-2.6.2.tar.gz  systemml-{{site.SYSTEMML_VERSION}}  systemml-{{site.SYSTEMML_VERSION}}.tar.gz
	Line 350: 	genLinearRegressionData.dml  hadoop-2.6.2  hadoop-2.6.2.tar.gz  systemml-{{site.SYSTEMML_VERSION}}  systemml-{{site.SYSTEMML_VERSION}}.tar.gz

I didn't look at the context of the usage, but should these documents also have tar.gz replaced with tgz?

**Comment by deroneriksson** [comment]
@gweidner 
Thank you for the thorough review.

I updated the Engine Dev Guide and Beginner's Guide to DML and PyDML to be more generic so as not to use .tar.gz or .tgz, which makes them easier to maintain.

I also investigated updating the artifacts mentioned in the Hadoop Batch Mode Guide, but given the current changing nature of the artifacts (from 0.10.0 to 0.11.0 to the future 1.0.0) and the added complexity to _config.yml, I think it's probably best to leave the Hadoop Batch Mode Guide as it is for now.

**Comment by gweidner** [comment]
Thank you @deroneriksson  for the updates!

**LGTM**

**Comment by deroneriksson** [comment]
Thank you for reviewing @gweidner!

**Pull request closed without merging**
