### PR TITLE
[SYSTEMML-540] Improved dropout performance

### PR DESCRIPTION
**Pull request by niketanpansare**
The modified script avoids unnecessary dense intermediate and is especially useful in case of low p value

@dusenberrymw can you please review ? We can either fix the rand bug as part of this PR or in separate PR.

### CODE REVIEW

**Comment by niketanpansare** [comment]
Updated the PR to support generic p values. This allows us to continue making progress in optimizing MNIST demo and when https://issues.apache.org/jira/browse/SYSTEMML-515 is resolved, we can update dropout too.

**Comment by niketanpansare** [comment]
Forgot to handle an if case, will update the PR soon :)

**Comment by dusenberrymw** [comment]
@niketanpansare I'm still not a fan of this update.  I think it's great to explore areas of improvement, but optimizing only for single, specific usages (i.e. only for `p=0.5`) is why SystemML is in its current, fragile state.  I.e. `dropout` needs to have the same level of performance for all levels of `p`,  rather than exhibit great performance properties *only* for specific values of `p`.  For more concrete evidence, that demo will involve a hyperparameter search over `p`, rather than always selecting `p=0.5`.

-1 for the temporary patch.  Let's just fix `rand` and fix the issue entirely.

**Comment by niketanpansare** [comment]
Ok, I will close this PR for now. Once https://issues.apache.org/jira/browse/SYSTEMML-515 is resolved, please use `mask = rand(rows=nrow(X), cols=ncol(X), min=1, max=1, sparsity=p)` rather than `mask = rand(rows=nrow(X), cols=ncol(X), min=0, max=1) <= p` as the former has much better performance.

**Pull request closed without merging**
