### PR TITLE
[SYSTEMML-510] Generalization wcemm

### PR DESCRIPTION
**Pull request by gweidner**
This patch adds support to wcemm for handling pattern (sum(X*log(U%*%t(V) + epsilon))).
It leverages functionality from previous PRs under SYSTEMML-510 and SYSTEMML-488 to generalize the wcemm operator with four operands.  Also included are 8 new test cases to cover Dense and Sparse-Dense for CP, MR, and Spark plus reduce-side.

### CODE REVIEW

**Comment by gweidner** [comment]
For reference, below are sample new instructions 

testCrossEntropyEpsDenseCP
CP wcemm _mVar1.MATRIX.DOUBLE _mVar2.MATRIX.DOUBLE _mVar3.MATRIX.DOUBLE 0.1.SCALAR.DOUBLE.true _Var4.SCALAR.DOUBLE BASIC_EPS 8

testCrossEntropyEpsDenseMR
mapper inst    = MR mapwcemm 0.MATRIX.DOUBLE 1.MATRIX.DOUBLE 2.MATRIX.DOUBLE 0.1.SCALAR.DOUBLE.true 3.MATRIX.DOUBLE BASIC_EPS

testCrossEntropyEpsDenseMRRep
other inst     = MR redwcemm 0.MATRIX.DOUBLE 3.MATRIX.DOUBLE 5.MATRIX.DOUBLE 0.1.SCALAR.DOUBLE.true 6.MATRIX.DOUBLE BASIC_EPS false false

testCrossEntropyEpsDenseSP
SPARK mapwcemm _mVar4.MATRIX.DOUBLE _mVar5.MATRIX.DOUBLE _mVar6.MATRIX.DOUBLE 0.1.SCALAR.DOUBLE.true _Var7.SCALAR.DOUBLE BASIC_EPS

testCrossEntropyEpsDenseSPRep
SPARK redwcemm _mVar4.MATRIX.DOUBLE _mVar5.MATRIX.DOUBLE _mVar6.MATRIX.DOUBLE 0.1.SCALAR.DOUBLE.true _Var7.SCALAR.DOUBLE BASIC_EPS false false

For pre-existing pattern (sum(X*log(U%*%t(V)))) where there is no fourth input, default -1.SCALAR.INT.true operand also generated but ignored:
testCrossEntropyDenseCP
CP wcemm _mVar1.MATRIX.DOUBLE _mVar2.MATRIX.DOUBLE _mVar3.MATRIX.DOUBLE -1.SCALAR.INT.true _Var4.SCALAR.DOUBLE BASIC 8

In addition to the unit tests, manual testing done to verify matrixMultWCeMMDense, matrixMultWCeMMSparseDense of LibMatrixMult for parallel (e.g., MatrixMultWCeTask where k=8) and single core.  Also forced matrixMultWCeMMGeneric case via debugger.

All unit tests passed in on-demand build against this branch prior to opening PR:
https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/116/https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/116/

**Comment by gweidner** [comment]
All tests passed in [PR build 214](https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/214/).
Note the branch for this PR includes all commits through March 17.

**Comment by mboehm7** [comment]
Thanks @gweidner - it already looks fine. It would be nice though to simplify the runtime a little bit. Since you deal in any case with scalars (eps or 0), I would recommend to compile for type BASIC a 0 instead of the -1 into the instruction, pass it as a scalar double to libmatrixmult, and simplify the internals of libmatrixmult wcemm accordingly.

**Comment by mboehm7** [comment]
also thanks for the cleanup of the lops construction of other quaternary operator types.

**Comment by gweidner** [comment]
Thank you @mboehm7 for the review.  I've simplified the scalar processing in LibMatrixMult for wcemm and updated the instruction for BASIC type, e.g., 
CP wcemm _mVar1.MATRIX.DOUBLE _mVar2.MATRIX.DOUBLE _mVar3.MATRIX.DOUBLE **0.0.SCALAR.DOUBLE.true** _Var4.SCALAR.DOUBLE BASIC 8

The automated PR build 215 is in progress.

**Comment by mboehm7** [comment]
LGTM

The test failures of PR build 215 are due to my last commit (tested through eclipse in a shared JVM process which has hidden thread-local initialization issues) - I'll deliver the fix tomorrow morning.

**Pull request closed without merging**
