### PR TITLE
[SYSTEMML-1642] Update license with current code change

### PR DESCRIPTION
**Pull request by asurve**
Removed opencsv file which has been removed from artifact, and updated protobuf version information per latest code.

@deroneriksson Can you please review the change?

### CODE REVIEW

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1504/

**Comment by gweidner** [comment]
Thank you Arvind for addressing license early in development process.  Good catch removing opencsv-2.3.jar from list since no longer bundled in lib folder for current build.  Also good catch regarding newer protobuf.  However, new lines 247-250 could be confusing since they are detached from existing protobuf-java license text at lines 293-323.  Maybe just updating the protobuf-java version number from 2.5.0 to 3.2.0 at line 293 would be sufficient assuming the license text for version 3.2.0 hasn't changed.

**Comment by gweidner** [comment]
Thank you @asurve for the update!  LGTM

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1513/

**Pull request closed without merging**
