### PR TITLE
[SYSTEMML-1476][SYSTEMML-1477] Source import from jar

### PR DESCRIPTION
**Pull request by deroneriksson**
Rename AParserWrapper to ParserWrapper.
Create ParserFactory class for createParser method.
Update ParserWrapper to allow source statement to import scripts from the
SystemML jar file if the scripts are not found in the file system.

### CODE REVIEW

**Comment by deroneriksson** [comment]
Can demonstrate with:
```
mvn clean package
cd target
spark-shell --executor-memory 4G --driver-memory 4G --driver-class-path=SystemML.jar
```
Followed by:
```
sc.setLogLevel("DEBUG")
import org.apache.sysml.api.mlcontext._
import org.apache.sysml.api.mlcontext.ScriptFactory._
val ml = new MLContext(spark)
val s = "source(\"scripts/ex.dml\") as blah;x = blah::myfunction(5);print('x:'+x)";
val script = ScriptFactory.dml(s);
ml.execute(script)
```
With the following dml scripts in the following locations (added to the jar file when it is built):
**scripts/ex.dml:**
```
source("scripts/utils/ex2.dml") as ex2ns
source("utils/ex3.dml") as ex3ns
source("utils/ex4.dml") as ex4ns

myfunction = function(double b) return (double a) {
	print('called myfunction with ' + b);
	c = b * 2;
	d = ex2ns::myfunction2(c);
	e = ex3ns::myfunction3(d);
	a = ex4ns::myfunction4(e);
}
z = myfunction(3.0);
print('z:' + z);
```
**scripts/utils/ex2.dml:**
```
myfunction2 = function(double b) return (double a) {
	print('called myfunction2 with ' + b);
	a = b * 2;
}
z = myfunction2(5.0);
print('y:' + z);
```
**scripts/utils/ex3.dml:**
```
myfunction3 = function(double b) return (double a) {
	print('called myfunction3 with ' + b);
	a = b * 2;
}
```
**scripts/utils/ex4.dml:**
```
source("utils/ex3.dml") as ex3ns

myfunction4 = function(double b) return (double a) {
	print('called myfunction4 with ' + b);
	c = b - 1;
	a = ex3ns::myfunction3(c);
}
```

This generates:
```
scala> ml.execute(script)
...
called myfunction with 5.0
called myfunction2 with 10.0
called myfunction3 with 20.0
called myfunction4 with 40.0
called myfunction3 with 39.0
x:78.0
```

**Comment by deroneriksson** [comment]
cc @dusenberrymw

**Comment by dusenberrymw** [comment]
LGTM.  Thanks, @deroneriksson.  This was super necessary, especially for being able to use the `nn` library in the JAR.

**Comment by dusenberrymw** [comment]
cc @niketanpansare Just FYI that the `nn` library should work once we start packaging it in the JAR soon due to this addition.

**Comment by niketanpansare** [comment]
Awesome !! Thanks @deroneriksson for adding this feature :+1: 

@dusenberrymw Looking forward to moving nn from staging to scripts :)

**Pull request closed without merging**
