### PR TITLE
[SYSTEMML-1629] Code format for IntelliJ

### PR DESCRIPTION
**Pull request by deroneriksson**
Add code style file for IntelliJ so that annotation formatting can be
handled in a similar fashion for both Eclipse and IntelliJ.

### CODE REVIEW

**Comment by deroneriksson** [comment]
cc @nakul02

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1498/

**Comment by nakul02** [comment]
LGTM :+1:

**Comment by deroneriksson** [comment]
Thank you for reviewing @nakul02! I'll merge.

**Pull request closed without merging**
