### PR TITLE
[SYSTEMML-1022][SYSTEMML-1035] Update default spark version build property and unit tests

### PR DESCRIPTION
**Pull request by gweidner**
Updated spark.version to 1.6.2 and included jodd-core dependency.

### CODE REVIEW

**Comment by gweidner** [comment]
Previously jodd provided through spark version 1.4.1:
jodd-dependency

Changing to newer spark version (1.5+) resulted in compilation error so also added maven dependency.  Used 'provided' scope so not bundled and no license update necessary.

**Comment by mboehm7** [comment]
thanks @gweidner - the import of jodd was actually a bug and is now fixed - I guess we can completely remove this dependency now.

**Comment by gweidner** [comment]
Thank you @mboehm7 for catching that!  My bad for not recognizing as I thought it was intended as part of optimization for [SYSTEMML-557].  I've removed the dependency and rebased this branch to pick up the latest changes.  Also successfully built with distribution profile locally on my dev system.

**Comment by gweidner** [comment]
There were unit test failures in [PR build 717](https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/717/) - at one time I had them all passing for spark 1.6.

**Comment by gweidner** [comment]
Some of the tests are new since I last investigated Spark 1.6/2.0.  One example below:
13:45:54 Running org.apache.sysml.test.integration.mlcontext.MLContextFrameTest
13:45:54 Tests run: 21, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 38.046 sec <<< FAILURE! - in org.apache.sysml.test.integration.mlcontext.MLContextFrameTest

13:45:54 	at org.apache.sysml.test.integration.mlcontext.MLContextFrameTest.testFrameDataFrame_CSV_DML(MLContextFrameTest.java:167)
13:45:54 Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
13:45:54 	at scala.runtime.BoxesRunTime.unboxToLong(BoxesRunTime.java:110)

**Comment by gweidner** [comment]
I've pushed new commit as work-around to prevent the ClassCastException for DataFrameVectorFrameConversionTest and DataFrameVectorScriptTest.  Each of the failures for those 2 suites (16 each suite) were identical where only the "ID" test cases were failing with:
java.lang.ClassCastException: java.lang.Integer incompatible with java.lang.Double
which was raised when calling df.first() in FrameRDDConverterUtils.dataFrameToBinaryBlock as part of intializing clen.
The work-around simply casts the integer to double when creating the index column for the Row although not sure if this should be handled within converter (e.g., for schema, observed Int mapped to DataType.LongType).
Both tests suites pass on my local Eclipse environment.  The MLContext failures will be looked at next.  Note this push should reduce the failures from 46 to 14.  PR build in progress:
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/728/

**Comment by gweidner** [comment]
The PR build completed with DataFrameVectorScript and DataFrameVectorFrameConversion tests passing with 14 failures remaining as expected in MLContextTest and MLContextFrameTest.  Pushed new commit for MLContextTest to resolve it's failures (10) where each one had 
java.lang.ClassCastException: java.lang.Double incompatible with java.lang.Integer
at RDDConverterUtils.dataFrameToBinaryBlock(RDDConverterUtils.java:290
    long rlen = tmp.count();  //tmp is JavaRDD<Row>
Note this latest commit will reduce the failures from 14 to 4.  PR build in progress:
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/729/

**Comment by gweidner** [comment]
All tests are now passing at [PR build 730](https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/730/).  However, the latest commit for MLContextFrameTest involved changing schema since Long, Double, Boolean were not being converted for input type DataFrame.

**Comment by gweidner** [comment]
Checking if the 4 cast exceptions for MLContextFrameTest similar issue as [SYSTEMML-956](https://issues.apache.org/jira/browse/SYSTEMML-956) fixed in #257 since indexing used in test script.

**Comment by gweidner** [comment]
@asurve I've fixed the four MLContextFrame tests with recent push that reverts the previous change for MLContextFrameTest and includes overloaded method in FrameRDDConverterUtils to incorporate schema information when converting to JavaRDD<Row>.  This approach is similar to updated FrameConverterTest from PR #223.

**Comment by gweidner** [comment]
I've rebased this branch to pick up latest changes from master.  I've also pushed a new commit to set spark version to 1.6.0.  The changes in this PR fix the test failures for [SYSTEMML-1112](https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/840/).
Note the ID column type can be addressed in separate JIRA/PR.

**Comment by gweidner** [comment]
Thank you Arvind for reviewing.   All tests passed:
[PR build 841](https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/841/).

I will merge to master.

**Pull request closed without merging**
