### PR TITLE
[SYSTEMML-1377] Add processing of custom configuration file for GDFO …

### PR DESCRIPTION
**Pull request by gweidner**
…tests

This patch allows tests that provide their own configuration to have the file processed by base test class which may relocate the scratch_space.  This prevents potential test failures in global data flow optimization tests due to folder hierarchy not publicly accessible.

### CODE REVIEW

**Comment by gweidner** [comment]
Other unit tests which require custom configuration can be addressed in separate PR.

**Comment by mboehm7** [comment]
thanks @gweidner - could you please also modify the tests in codegen?

**Comment by gweidner** [comment]
I've pushed second commit which applies similar updates to all codegen tests plus one compress test.  The first commit passed all unit tests in [PR build 1195](https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1195/).

**Comment by mboehm7** [comment]
LGTM - thanks @gweidner

**Pull request closed without merging**
