### PR TITLE
[SYSTEMML-1461] multi-threaded parfor for gpu

### PR DESCRIPTION
**Pull request by nakul02**
This PR is some initial work towards enabling the use of multiple GPUs in a single machine using `parfor` loop bodies.

Ping @niketanpansare

### CODE REVIEW

**Comment by niketanpansare** [comment]
LGTM, I particularly like multiple GPU context. I would recommend waiting for 0.14 branch to be created. Also, it would be nice if we double-check setGPU feature with this PR. I can test setGPU feature on deep-learning networks once https://github.com/apache/incubator-systemml/pull/422 is merged in :)

**Comment by niketanpansare** [comment]
@nakul02 Can you please rebase this PR with master ? I want to run some sanity tests on it.

**Comment by nakul02** [comment]
Will do, thanks!

**Comment by nakul02** [comment]
@niketanpansare  - rebased against master.

**Comment by niketanpansare** [comment]
Thanks @nakul02 ... I noticed that when setGPU is enabled, we initialize CUDA, but no GPU instructions gets invoked.

Here is a simple scala script to test it:

```scala
import org.apache.sysml.api.mlcontext._
import org.apache.sysml.api.mlcontext.ScriptFactory._
val ml = new MLContext(spark)
ml.setGPU(true)
ml.setStatistics(true)
val script = dml("X = rand(rows=100, cols=100); print(sum(X %*% t(X)));")
ml.execute(script)
```

```bash
254797.91226422403
SystemML Statistics:
Total elapsed time:             7.119 sec.
Total compilation time:         0.000 sec.
Total execution time:           7.119 sec.
Number of compiled Spark inst:  0.
Number of executed Spark inst:  0.
CUDA/CuLibraries init time:     6.759/0.592 sec.
Number of executed GPU inst:    0.
GPU mem tx time  (alloc/dealloc/set0/toDev/fromDev):    0.000/0.000/0.000/0.000/0.000 sec.
GPU mem tx count (alloc/dealloc/set0/toDev/fromDev/evict):      0/0/0/0/0/0/0.
GPU conversion time  (sparseConv/sp2dense/dense2sp):    0.000/0.000/0.000 sec.
GPU conversion count (sparseConv/sp2dense/dense2sp):    0/0/0.
Cache hits (Mem, WB, FS, HDFS): 3/0/0/0.
Cache writes (WB, FS, HDFS):    1/0/0.
Cache times (ACQr/m, RLS, EXP): 0.000/0.000/0.001/0.000 sec.
HOP DAGs recompiled (PRED, SB): 0/0.
HOP DAGs recompile time:        0.000 sec.
Spark ctx create time (lazy):   0.000 sec.
Spark trans counts (par,bc,col):0/0/0.
Spark trans times (par,bc,col): 0.000/0.000/0.000 secs.
Total JIT compile time:         1.421 sec.
Total JVM GC count:             11.
Total JVM GC time:              0.491 sec.
Heavy hitter instructions (name, time, count):
-- 1)   rand    0.026 sec       1
-- 2)   uack+   0.008 sec       1
-- 3)   tsmm    0.005 sec       1
-- 4)   createvar       0.002 sec       3
-- 5)   print   0.000 sec       1
-- 6)   rmvar   0.000 sec       5
-- 7)   castdts         0.000 sec       1

res2: org.apache.sysml.api.mlcontext.MLResults =

```

I have also tested it with my wrappers and observe the same behavior.

**Comment by nakul02** [comment]
Can you please try setting the `force=true` argument ?

**Comment by niketanpansare** [comment]
we donot have `force=true` in mlcontext :(

**Comment by nakul02** [comment]
for now, can you either quickly add one, or just hard-code in the source and try it out?

**Comment by deroneriksson** [comment]
How about
```
scala> org.apache.sysml.api.DMLScript.FORCE_ACCELERATOR = true
```

**Comment by niketanpansare** [comment]
I tried running above script with `force` on current master and it works.

**Comment by nakul02** [comment]
great, thanks @niketanpansare & @deroneriksson

**Comment by niketanpansare** [comment]
To summarize,
1. Current master: works without force
2. This PR: works with force, but not without force.

If this is known issue that you intend to fix in subsequent PR, then LGTM for this PR.

**Comment by nakul02** [comment]
@niketanpansare 
I shall, since 0.14 is now on a separate branch, can I merge this?

**Comment by niketanpansare** [comment]
LGTM :+1:  ... please fix the force issue in a separate PR.

**Comment by nakul02** [comment]
Thanks, I shall merge

**Pull request closed without merging**
