### PR TITLE
[SYSTEMML-1170] Clean Up Python Documentation For Next Release

### PR DESCRIPTION
**Pull request by dusenberrymw**
Cleanup of Python documentation.

### CODE REVIEW

**Comment by dusenberrymw** [comment]
[Preview available here.](dusenberrymw.github.io/incubator-systemml)

**Comment by dusenberrymw** [comment]
cc @deroneriksson

**Comment by deroneriksson** [comment]
LGTM. Thank you @dusenberrymw!

Did you require "gem install bundler"?

**Comment by dusenberrymw** [comment]
@deroneriksson Thanks!  Yeah I had to install `bundler` in order to run jekyll.

**Comment by deroneriksson** [comment]
cool, thanks for getting our docs up-to-date.

**Pull request closed without merging**
