### PR TITLE
[SYSTEMML-670] Fix PyDML built-in functions random and cdf

### PR DESCRIPTION
**Pull request by gweidner**
This patch fixes parsing of PyDML built-in functions random.normal, random.uniform, norm.cdf, expon.cdf, chi.cdf, f.cdf, and t.cdf.  Also added test script to invoke each function to verify parsing issue no longer occurs for PyDML.

### CODE REVIEW

**Comment by dusenberrymw** [comment]
Thanks for this, @gweidner.  I came across an interesting PyDML error:

This code blows up:
```
def rand(x: int) -> (y: int, z: matrix[float]):
  print("hi")
  z = full(x, rows=4, cols=2)
  y = x*2

N = 4
D = 3
X = random.normal(N, D, 1)
print(sum(X))

[Y, Z] = rand(3)
print(sum(Z))
```
```
: org.apache.sysml.parser.LanguageException: ERROR: null -- line 5, column 0 -- Assignment statement cannot return multiple values
	at org.apache.sysml.parser.Statement.raiseValidateError(Statement.java:167)
	at org.apache.sysml.parser.Statement.raiseValidateError(Statement.java:140)
	at org.apache.sysml.parser.StatementBlock.rewriteFunctionCallStatements(StatementBlock.java:503)
	at org.apache.sysml.parser.StatementBlock.validate(StatementBlock.java:552)
	at org.apache.sysml.parser.DMLTranslator.validateParseTree(DMLTranslator.java:133)
	at org.apache.sysml.api.MLContext.executeUsingSimplifiedCompilationChain(MLContext.java:1355)
	at org.apache.sysml.api.MLContext.compileAndExecuteScript(MLContext.java:1257)
	at org.apache.sysml.api.MLContext.executeScript(MLContext.java:1195)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:207)
	at java.lang.Thread.run(Thread.java:745)
```
However, if you comment out the `X = random.normal....` and associated `print...` statement, it works:
```
def rand(x: int) -> (y: int, z: matrix[float]):
  print("hi")
  z = full(x, rows=4, cols=2)
  y = x*2

N = 4
D = 3
#X = random.normal(N, D, 1)
#print(sum(X))

[Y, Z] = rand(3)
print(sum(Z))
```
```
hi
24.0
```
Now it gets stranger. Alternatively, just rename `rand` to something else (but keep the `X = random.normal...` lines) and it also works:
```
def rando(x: int) -> (y: int, z: matrix[float]):
  print("hi")
  z = full(x, rows=4, cols=2)
  y = x*2

N = 4
D = 3
X = random.normal(N, D, 1)
print(sum(X))

[Y, Z] = rando(3)
print(sum(Z))
```
```
hi
-4.866772632314475
24.0
```

**Comment by gweidner** [comment]
Good catch @dusenberrymw.  The PyDML built-in function 'random.normal' gets converted internally to dml syntax built-in 'rand' function which was overridden by 'def rand' statement.  Let me debug this scenario in more detail and will update this PR accordingly.  Thanks!

**Comment by dusenberrymw** [comment]
Thinking about this more, it would probably be better to actually move `rand(...)` in PyDML to `random.rand(...)` to be more in line with NumPy [1].

1: http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.random.rand.html

**Comment by gweidner** [comment]
I've created [SYSTEMML-696](https://issues.apache.org/jira/browse/SYSTEMML-696/) for handling conflict between overridden built-in and converted PyDML syntax.

**Comment by gweidner** [comment]
For supporting random.rand(...) in PyDML, created [SYSTEMML-697](https://issues.apache.org/jira/browse/SYSTEMML-697/) under [Improve PyDML](https://issues.apache.org/jira/browse/SYSTEMML-669).

**Comment by dusenberrymw** [comment]
LGTM.  We can address the other cases in the JIRA issues created.

Thanks, @gweidner!

**Pull request closed without merging**
