### PR TITLE
Refactor project package to org.apache.sysml

### PR DESCRIPTION
**Pull request by lresende**
The refactor from com.ibm.bi.dml to org.apache.sysml
is being done in two phases to avoid loosing the file
history: 

- In the first phase, files are being moved to new location.
- In the second phase, update references to new project structure.

Build has been started [here](https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/19/)

### CODE REVIEW

**Comment by dusenberrymw** [comment]
Nit: The *committers* for the first two commits (Deron's and your pom.xml changes) are still not attached to your account, although the *authors* are correct.

The tests ran successfully.

**LGTM**.

**Comment by lresende** [comment]
@dusenberrymw I think i was able to fix all now, could you please double check.

**Comment by dusenberrymw** [comment]
LGTM.

**Comment by lresende** [comment]
PR Merged

**Pull request closed without merging**
