### PR TITLE
Clean up and reorganize the existing documentation.

### PR DESCRIPTION
**Pull request by dusenberrymw**
This update cleans up and reorganizes a lot of the existing documentation. The goal here is to work towards cleaning up our external message and targeting specific types of users in order to increase ease of adoption.

My vision is that we target data scientists using Spark first and foremost.  Without this focus in our documentation, the project is seemingly too confusing, and will deter this key user demographic from adoption.  Once these users are onboard, engine developers will follow.

This PR is a first effort towards this goal, and provides a nicer, cleaned-up version of the docs.  We should *collectively* work to improve these, with clear separation between data scientists, systems engineers/researchers, etc.

A preview can be [found here](http://dusenberrymw.github.io/incubator-systemml/).

@frreiss, @mboehm7, @niketanpansare, @nakul02, @gweidner, @asurve, @deroneriksson, @MadisonJMyers

### CODE REVIEW

**Comment by deroneriksson** [comment]
I see you have moved the Quick Start Guide to a Standalone Guide. Great! You should be able to close [SYSTEMML-457 - Create Standalone mode guide](https://issues.apache.org/jira/browse/SYSTEMML-457) with this PR.

**Comment by deroneriksson** [comment]
I also like moving the test/R information out of the README and into the new Engine Developer Guide. That way we don't confuse our users into thinking they need to run the whole test suite with R to be able to use SystemML.

**Comment by deroneriksson** [comment]
This PR also addresses [SYSTEMML-458 - Create Spark batch mode guide](https://issues.apache.org/jira/browse/SYSTEMML-458). Great!

**Comment by deroneriksson** [comment]
LGTM. This is a great move towards reorganizing our documentation to benefit all our users, especially data scientists, our primary audience.

**Comment by niketanpansare** [comment]
The reorg looks good :+1:  Thanks !!

**Comment by MadisonJMyers** [comment]
Very exciting! I really like the reorganization. Even the READ.me is much less confusing. Great step in the right direction! Also really love that you have clearly stated our audience and our goals.

**Pull request closed without merging**
