### PR TITLE
[SYSTEMML-1380] Kmeans isY and verb parameters should be boolean

### PR DESCRIPTION
**Pull request by krishnakalyan3**
In the Kmeans.dml script, the 'isY' and 'verb' input parameters are integers. However, they are basically on/off switches, so replacing the integer types with boolean types could potentially be a little clearer to users.

I tested this on my local system.

### CODE REVIEW

**Comment by akchinSTC** [comment]
Can an Admin verify this patch?

**Comment by krishnakalyan3** [comment]
cc @deroneriksson

**Comment by deroneriksson** [comment]
@iyounus Are you aware of any code invoking Kmeans.dml in the project (such as performance suite) where any updates are needed for these parameters? I looked at runKmeans.sh and I don't see any other updates needed.

**Comment by krishnakalyan3** [comment]
@deroneriksson thank you for the review. I am sorry for missing out conditional if updates.

**Comment by deroneriksson** [comment]
LGTM. Thank you @krishnakalyan3!

**Pull request closed without merging**
