### PR TITLE
[SYSTEMML-617] Override default namespace for imported custom functions

### PR DESCRIPTION
**Pull request by gweidner**
This patch with dml/pydml tests is intended to incrementally improve namespace handling to facilitate defining and reusing functions across multiple scripts.  It includes isolated changes to target a specific scenario where dependent functions (e.g., function1 internally calls function2 defined in same script) but are also imported by another script.  The change to StatementBlock was not required but included to help compare blocks when inspecting variables under IDE debugger.
Prior to this patch, the internal call would fail as described in [SYSTEMML-590] which is covered under 'testFunctionSourceNS'.  The other 2 tests were included to show this patch does not change expected behavior where imported custom function was not fully qualified (testFunctionWithoutNS) and internal custom function call without namespace ok when run directly (testFunctionDefaultNS).
A few built-in functions were also ran to verify built-ins still found in defaultns.

### CODE REVIEW

**Comment by gweidner** [comment]
Example of error which would occur when running Functions1.dml prior to this patch:

org.apache.sysml.parser.LanguageException: ERROR: null -- line 0, column 0 -- function square is undefined in namespace .defaultNS
	at org.apache.sysml.parser.StatementBlock.isMergeableFunctionCallBlock(StatementBlock.java:201)
	at org.apache.sysml.parser.StatementBlock.mergeFunctionCalls(StatementBlock.java:328)
	at org.apache.sysml.parser.DMLTranslator.liveVariableAnalysis(DMLTranslator.java:165)
	at org.apache.sysml.api.DMLScript.execute(DMLScript.java:585)
	at org.apache.sysml.api.DMLScript.executeScript(DMLScript.java:332)
	at org.apache.sysml.api.DMLScript.main(DMLScript.java:191)

**Comment by gweidner** [comment]
All tests passed in [PR build 240](https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/240/).

**Comment by gweidner** [comment]
All tests also passed in [OnDemand build 134](https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/134/) which was rerun since previous [OnDemand build 133](https://sparktc.ibmcloud.com/jenkins/job/SystemML-OnDemand/133/) showed 1 failure in  org.apache.sysml.test.integration.applications.pydml.L2SVMPyDMLTest.

Note pre-existing behavior sets namespace to '.defaultNS' in CommonSyntacticValidator.getQualifiedNames for any function call that does not specify namespace.  The approach in this PR was to override that setting for an imported custom (i.e., non-built-in) non-qualified function call using the namespace specified in source statement which gets passed to the SyntacticValidator for validating the imported file.

**Comment by gweidner** [comment]
Added commits to cover custom functions with multiple return values.  PR 242 in progress.  Thank you @dusenberrymw for finding this case in grad_check.dml of deep learning library.

**Comment by dusenberrymw** [comment]
@gweidner Excellent!  I can confirm that the latest version works as intended.  I think this approach is simple, and introduces a good suite of tests to support the next stages of the UDF improvements.  Thanks!

LGTM.

**Comment by dusenberrymw** [comment]
@gweidner Looks like there are some merge conflicts now, can you fix them and then I can merge?

**Comment by gweidner** [comment]
I've resolved the merge conflicts in DMLParserWrapper,java, PyDMLParserWrapper.java and force pushed the rebased commits.  The new tests added with this PR passed locally.  Full tests in progress at [PR build 243](https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/243/).
Thanks again for reviewing and merging!

**Comment by dusenberrymw** [comment]
Merged. Thanks @gweidner!

**Pull request closed without merging**
