### PR TITLE
[SYSTEMML-573] Frame read-write test

### PR DESCRIPTION
**Pull request by asurve**

### CODE REVIEW

**Comment by mboehm7** [comment]
thanks @asurve - could you please consolidate writeAndVerifyBinaryBlockData, writeAndVerifyTextCSVData, and writeAndVerifyTextCellData into a single method that simply goes through FrameWriterFactory?

**Comment by asurve** [comment]
thanks, addressed the change

**Comment by mboehm7** [comment]
it goes into the right direction but why can't we just use FrameReaderFactory and FrameWriterFactory to avoid handling input and output infos - that's exactly what they're meant for, right?

**Comment by asurve** [comment]
yes, I should have. I did the change. I have added another signature FrameReaderFactory.createFrameReader(iinfo, prop) to be consistent with FrameWriterFactory and to avoid burden on caller.

**Comment by mboehm7** [comment]
ok great - just two more things:
1) you don't need to specify both InputInfo and OutputInfo - you can always get the corresponding input/output with InputInfo.getMatchingOutputInfo or OutputInfo.getMatchingInputInfo
2) there is a redundant semicolon in FrameReadWriteTest, line 170

**Comment by mboehm7** [comment]
LGTM - @asurve could you please double check that the tests are still working after merging. Thanks.

**Pull request closed without merging**
