### PR TITLE
[SYSTEMML-292] Fix PyDML boolean output case

### PR DESCRIPTION
**Pull request by deroneriksson**
Create global ScriptType variable in DMLScript.
Set global ScriptType in DMLScript, MLContext APIs, and JMLC API.
Add correct case boolean string output method to BooleanObject.
Update ScalarBuiltinCPInstruction, ScalarScalarArithmeticCPInstruction, and
ScalarScalarBuiltinCPInstruction for boolean display.

### CODE REVIEW

**Comment by deroneriksson** [comment]
Before this PR, the following PYDML code:

```
a = True
print(a)
print('2' + a)
print(a + '3')
print('4' + a + '5')
print(2>1)
b = False
print(a & b)
print('abc'+(2>1))
print((2>1)+'def')
```

generates:
```
TRUE
2TRUE
TRUE3
4TRUE5
TRUE
FALSE
abcTRUE
TRUEdef
```

After PR, it generates:
```
True
2True
True3
4True5
True
False
abcTrue
Truedef
```

**Comment by deroneriksson** [comment]
All tests pass here: https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/911/console
(except 1 unrelated FrameMatrixReblockTest test)

**Comment by gweidner** [comment]
Checked out the PR to my local environment and verified new tests passed.  For example:

This test case will use SystemML config file target\testTemp\org\apache\sysml\api\mlcontext\MLContext\SystemML-config.xml
MLContextTest - display boolean PYDML
True

Thank you @deroneriksson for this improvement!
LGTM

**Comment by deroneriksson** [comment]
Thank you @gweidner for reviewing!

**Pull request closed without merging**
