### PR TITLE
[SYSTEMML-1240] Cleanup crc files when write scalar

### PR DESCRIPTION
**Pull request by deroneriksson**
Cleanup crc files when write scalar to local file system.

### CODE REVIEW

**Comment by deroneriksson** [comment]
Can test with (MLContext-style test):
```
@Test
public void testScalarWrite() {
	String s = "A = 2.0; write(A,\"scalar.txt\")";
	Script script = dml(s);
	ml.execute(script);
}
```

**Comment by gweidner** [comment]
Thank you @deroneriksson for making scalar crc file cleanup consistent with matrix crc file cleanup.
LGTM

**Comment by deroneriksson** [comment]
Thank you for reviewing @gweidner!

**Comment by deroneriksson** [comment]
BTW all tests passed: https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1100/

**Pull request closed without merging**
