### PR TITLE
[SYSTEMML]Fix DMLAppMasterStatusReporter.java thread cancel bug.

### PR DESCRIPTION
**Pull request by GrapeBaBa**
# Summary
This PR created for fixing multiple thread bug in DMLAppMasterStatusReporter.java.
1.Use a volatile variable for flag.
2.Invoke interrupt method to avoid block method such as Thread.sleep invocation.

### CODE REVIEW

**Comment by mboehm7** [comment]
thanks @GrapeBaBa - since you explicitly interrupt the thread, could you please also add the related  handling of InterruptedException (e.g., something like LOG.warn("Status reporter interrupted with stop="+_stop)

**Comment by GrapeBaBa** [comment]
@mboehm7 Done.

**Comment by mboehm7** [comment]
LGTM

**Comment by deroneriksson** [comment]
Thank you @GrapeBaBa . I will merge.

**Pull request closed without merging**
