### PR TITLE
[SYSTEMML-486] Java opts to standalone scripts

### PR DESCRIPTION
**Pull request by deroneriksson**
Allow Java options to be set via SYSTEMML_JAVA_OPTS env var.

### CODE REVIEW

**Comment by shirisht** [comment]
Is this the best way to provide java opts to standalone execution? It may misled users into thinking that they can pass  such java opts for driver/CP process in distributed execution as well -- something similar to `HADOOP_CLIENT_OPTS` in Hadoop.

Two options:
1. Either change the env var to make it explicit that it is applicable only for standalone execution
2. Instead of env var, have such property in the config file .. just like the way we had jvm properties for distributed execution. I prefer this but does not have a strong opinion.

**Comment by deroneriksson** [comment]
@shirisht WRT option 1, I renamed the env var to SYSTEMML_STANDALONE_OPTS to attempt to clarify the standalone/singlenode execution. Does that seem clearer? Thank you for reviewing.

**Comment by deroneriksson** [comment]
@shirisht @mboehm7 Are any other modifications required, or is this ready for merging? Thank you.

**Comment by shirisht** [comment]
LGTM.

**Pull request closed without merging**
