### PR TITLE
[SYSTEMML-503] License for source distro

### PR DESCRIPTION
**Pull request by deroneriksson**
Created LICENSE for source distribution. In assembly, replaced root LICENSE with source LICENSE for the source distribution.

@lresende Please review.

### CODE REVIEW

**Comment by deroneriksson** [comment]
@lresende Please review.

**Comment by lresende** [comment]
@deroneriksson , sorry, didn't see this, I have added the license last night, could you please rebase

**Comment by lresende** [comment]
Other then rebasing, LGTM.

**Comment by deroneriksson** [comment]
@lresende Great. I rebased this commit so it only has the update to assembly/source.xml. Thank you for reviewing.

**Pull request closed without merging**
