### PR TITLE
[SYSTEMML-1201] Update -standalone tgz and zip to -bin

### PR DESCRIPTION
**Pull request by deroneriksson**
Rename assembly id for binary artifacts to 'bin'.
Rename binary artifact base directory from '-standalone' to '-bin'.
Rename standalone.xml to bin.xml.
Rename src/assembly/standalone to src/assembly/bin.

### CODE REVIEW

**Comment by deroneriksson** [comment]
Tested locally with:
```
# build distribution artifacts
mvn clean package -P distribution

cd target

# verify main jar works
java -cp ./lib/*:systemml-0.13.0-incubating-SNAPSHOT.jar org.apache.sysml.api.DMLScript -s "print('hello world');"

# verify SystemML.jar works
java -cp ./lib/*:SystemML.jar org.apache.sysml.api.DMLScript -s "print('hello world');"

# verify src works
tar -xvzf systemml-0.13.0-incubating-SNAPSHOT-src.tgz
cd systemml-0.13.0-incubating-SNAPSHOT-src
mvn clean package -P distribution
cd target/
java -cp ./lib/*:systemml-0.13.0-incubating-SNAPSHOT.jar org.apache.sysml.api.DMLScript -s "print('hello world');"
java -cp ./lib/*:SystemML.jar org.apache.sysml.api.DMLScript -s "print('hello world');"
cd ..
cd ..

# verify bin tgz works
tar -xvzf systemml-0.13.0-incubating-SNAPSHOT-bin.tgz
cd systemml-0.13.0-incubating-SNAPSHOT-bin
echo "print('hello world');" > hello.dml
./runStandaloneSystemML.sh hello.dml
cd ..

# verify bin without libs tgz works
tar -xvzf systemml-0.13.0-incubating-SNAPSHOT.tgz
cd systemml-0.13.0-incubating-SNAPSHOT
java -cp ../lib/*:SystemML.jar org.apache.sysml.api.DMLScript -s "print('hello world');"

# verify spark batch mode
export SPARK_HOME=/Users/deroneriksson/spark-2.1.0-bin-hadoop2.7
$SPARK_HOME/bin/spark-submit SystemML.jar -s "print('hello world');" -exec hybrid_spark

# verify hadoop batch mode
hadoop jar SystemML.jar -s "print('hello world');"
```

**Comment by deroneriksson** [comment]
cc @bertholdreinwald

**Comment by deroneriksson** [comment]
All tests passed (except random FullReblockTest)
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1053/

cc @gweidner @asurve

**Comment by gweidner** [comment]
Thank you Deron!
LGTM

(The FullReblockTest tracked under [SYSTEMML-1110].)

**Comment by deroneriksson** [comment]
Thank you for reviewing @gweidner!

**Pull request closed without merging**
