### PR TITLE
[SYSTEMML-657]  Deprecate `ppred(...)` Built-In Function

### PR DESCRIPTION
**Pull request by nishi-t**
This PR updates the dml scripts, the dml parser and the manual for replacing deprecated `ppred(...)`. I ran `mvn verify` and the performance test script (perftest/runAll.sh), and I made sure that it was finished without any problems. Please review.

### CODE REVIEW

**Comment by mboehm7** [comment]
great - thanks @nishi-t , I would recommend just a few additional cleanups and then we're good to go: 

1) Cox-predict.dml: Please fix the condition >max_event_time (instead of <max_event_time).

2) Style: Could we also globally change any comparison with 0.0 to 0? This PR is a good opportunity to clean this up once and for all.

3) Documentation: Please update the "output" column in https://apache.github.io/incubator-systemml/dml-language-reference.html#operators to "Matrix or Scalar" for the comparison operators and refer to footnotes 1 and 2.

4) Validation DMLSyntacticValidator: I would recommend to move this deprecation check into BuiltinFunctionExpression (ppred validation) to make it independent of the frontend language.

**Comment by nishi-t** [comment]
Thank you for your comments @mboehm7, I'm going to fix my PR following the comments.

**Comment by nishi-t** [comment]
addressed for the comments. Could you please review again @mboehm7 .

**Comment by mboehm7** [comment]
great - thanks @nishi-t this looks already pretty good. Just one final cleanup:

ad 4) Please move the warning to BuiltinFunctionExpression.validateExpression() which allows you to call raiseValidateError(message, true) in the base class in order to ensure consistency of warning messages. With that you can also remove the custom method for warnings (this raises a good point to cleanup the warning messages across syntactic parsers and validation; feel free to file a jira).

**Comment by nishi-t** [comment]
Thank you for your review @mboehm7. I fixed the PR.

**Comment by nishi-t** [comment]
If my these changes to raise waring look good, I'm going to apply it for other deprecated operator(e.g.  castAsScalar) too.

**Comment by mboehm7** [comment]
LGTM - thanks @nishi-t

**Pull request closed without merging**
