### PR TITLE
[SYSTEMML-1549] Cox.dml - return S & T in usable format

### PR DESCRIPTION
**Pull request by bdwyer2**
Returns `S` & `T` as a matrix instead of string.

### CODE REVIEW

**Comment by dusenberrymw** [comment]
@bdwyer2 I agree that this is definitely useful.  I need to think about whether there is a way to do it without affecting the regular usage of the existing scripts.  Or perhaps we can just update it with the upcoming 1.0 release.

**Comment by aloknsingh** [comment]
@dusenberrymw @bdwyer2 The above will not break the existing script. I believe it is returning extra matrixes so it should be safe

**Comment by deroneriksson** [comment]
@dusenberrymw I don't see any tests in the project that test Cox.dml (including scripts/perftest/runAll.sh, where there is a comment where the test should be), so I don't think this change would break anything.

Is line 213 ok (`write (S_str, fileS, format = fmtO)`)?

**Comment by dusenberrymw** [comment]
Is this comment still applicable to the matrices (vs. the original string format)?
```
# Two log files containing a summary of some statistics of the fitted model:
 # 1- File S with the following format 
 #	- line 1: no. of observations
 #	- line 2: no. of events
 #   - line 3: log-likelihood 
 #	- line 4: AIC
 #	- line 5: Rsquare (Cox & Snell)
 #	- line 6: max possible Rsquare
 # 2- File T with the following format
 #	- line 1: Likelihood ratio test statistic, degree of freedom, P-value
 #	- line 2: Wald test statistic, degree of freedom, P-value
 #	- line 3: Score (log-rank) test statistic, degree of freedom, P-value
```

**Comment by deroneriksson** [comment]
LGTM. Thank you @bdwyer2! I'll merge.

**Comment by akchinSTC** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://sparktc.ibmcloud.com/jenkins/job/SystemML-PullRequestBuilder/1482/

**Pull request closed without merging**
