### PR TITLE
[SYSTEMML-134] Update standalone readme.txt

### PR DESCRIPTION
**Pull request by deroneriksson**

### CODE REVIEW

**Comment by shirisht** [comment]
@deroneriksson 

1. Could you please add the following lines from Quickstart guide: *The standalone release packages all required libraries into a single distribution file. In standalone mode, all operations occur on a single node in a non-Hadoop environment. Standalone mode is not appropriate for large datasets.*

2. As part of this PR or a new one, could you modify the java invocation in `.sh` and `.bat` scripts to accept JVM size as configuration parameters -- with a default value of `4g` (or `2g`)?  This would give users a bit of flexibility when they are prototyping on their laptops. You could also mention a couple of lines reg. this setting in readme.txt.

**Comment by dusenberrymw** [comment]
@deroneriksson Can you also rename this to `README.txt` for more consistency?

**Comment by deroneriksson** [comment]
@shirisht 
(1) Updated to integrate that information into the readme.
(2) Created SYSTEMML-486 to do JVM size in a separate PR.

@dusenberrymw 
Updated readme.txt to README.txt. Modified standalone.xml accordingly.

**Comment by dusenberrymw** [comment]
LGTM.

**Pull request closed without merging**
