### PR TITLE
Troubleshoot document for java heap size error

### PR DESCRIPTION
**Pull request by ethanyxu**
Added a troubleshoot section about OOM errors in reduce phase.

### CODE REVIEW

**Comment by shirisht** [comment]
Ethan, thank you for preparing this section under Troubleshooting guide.
I am, however, not sure about the need for this -- especially because these are Hadoop settings that are relevant for any application running on Hadoop. We are also not providing any recommended settings specific to SystemML -- for example, we recommend three times the HDFS block size for `mapreduce.task.io.sort.mb` based on the way SystemML operates. In contrast, we are not providing any SystemML-specific recommended settings here.

I would like to see what others think about it.

**Comment by deroneriksson** [comment]
I am in favor of accepting this PR. @ethanyxu is running SystemML on a large dataset on a large Hadoop cluster. Another user in a similar situation may find this information helpful.

**Comment by deroneriksson** [comment]
If accepted, my one request would be to update the absolute link to `http://apache.github.io/incubator-systemml/hadoop-batch-mode.html` to a relative link `[Invoking SystemML in Hadoop Batch Mode](hadoop-batch-mode.html)`

**Comment by dusenberrymw** [comment]
I too am in favor of adding this, as it represents a simple solution to a particular Hadoop issue that has presented itself in the course of running SystemML on a real problem.

@ethanyxu Thanks for continuing to bring to our attention the various issues and scenarios that you have encountered.

**Comment by shirisht** [comment]
Couple of comments:

1. Can you include at least first few lines from the stack trace insteadof just `java.lang.OutOfMemoryError`, so that the cause of such an error is more explicit.
2. Change the wording `per-task basis` -- the word 'task' can be misled to mean individual map reduce tasks.
3. How do the Hadoop configuration parameters specified in `SystemML-config.xml` are propagated to individual MR jobs that are created?

**Comment by ethanyxu** [comment]
Oops I missed the discussion. Thanks all for the suggestions and comments. I understand these are general hadoop settings, but in my use case changing the global configuration was not an option as the cluster was shared with other people. Modifying the configurations via `SystemML-config.xml` (as suggested by @mboehm7) worked great. 

@shirisht I ran into this problem twice with different OOM errors. One traceback is attached. The wording `per-task basis` is changed to `per SystemML-task basis`. As for how the configs were propagated, it looks from the server side logs that they were just passed to all MR jobs generated by SystemML. I am not able to elaborate in more technical depth. 

@deroneriksson The link is changed to a relative link as you suggested. 

Thank you @dusenberrymw I'm glad to share my experience:)

**Comment by mboehm7** [comment]
I'm also in favor of extending our trouble shooting guide as we go, even if these issues are not always related to SystemML core. Thanks @ethanyxu

**Comment by deroneriksson** [comment]
LGTM. Thank you @ethanyxu

**Pull request closed without merging**
