### PR TITLE
[SYSTEMML-1193] Update perftest script and doc of naive-bayes-predict.dml for required probabilities parameter

### PR DESCRIPTION
**Pull request by gweidner**
Restore conditional for checking $probabilities before attempting to use in write() to resolve error when running performance tests.

### CODE REVIEW

**Comment by gweidner** [comment]
Below was the observed error mentioned in JIRA:

ERROR api.DMLScript: ../algorithms/naive-bayes-predict.dml line 58:13 The parameter $probabilities either needs to be passed through commandline or initialized to default value.

--------------------------------------------------------------
The following parse issue was encountered:
../algorithms/naive-bayes-predict.dml [line 58:13] [Validation error] -> write(probs, $probabilities, format=cmdLine_fmt)
   The parameter $probabilities either needs to be passed through commandline or initialized to default value.
--------------------------------------------------------------

Successfully ran the performance test with updated naive-bayes-predict.dml.

**Comment by deroneriksson** [comment]
LGTM

**Comment by deroneriksson** [comment]
@gweidner @bertholdreinwald Is this PR needed for the currently implementation of the performance tests?

**Comment by gweidner** [comment]
Yes, the error was also observed in latest round of performance testing (but can be worked-around).

Instead added probabilities argument in runNaiveBayes.sh for executing naive-bayes-predict.dml to prevent error when running parent runAllMultinomial.sh of performance test suite.  Reverted naive-bayes-predict.dml to previous version without ifdef that was removed in [SYSTEMML-234][SYSTEMML-208].  Also removed "Note this is an optional argument" from naive bayes predict description in algorithms reference.
Verified error no longer occurred, naive-bayes-predict ran successfully from runNaiveBayes.sh using local small private cluster, and probabilities files created in hdfs.

**Comment by deroneriksson** [comment]
LGTM. Thanks for the additional updates @gweidner!

**Pull request closed without merging**
