### PR TITLE
Update pom.xml with respect to Apache Incubator status

### PR DESCRIPTION
**Pull request by deroneriksson**
License comment updated, groupId updated for Apache, name updated to more proper name, description added, project url added, license added, JIRA added, mailing lists added.

### CODE REVIEW

**Comment by lresende** [comment]
LGTM

**Comment by lresende** [comment]
Jenkins test this

**Comment by oza** [comment]
@lresende Is Jenkins integrated with this project?

**Comment by lresende** [comment]
@oza, looks like after the move to Apache we need to update it.

**Comment by lresende** [comment]
PR Merged

**Pull request closed without merging**
